// site/src/components/CatalogBrowser.tsx
import { createSignal, createEffect, onMount, onCleanup, For, Show } from "solid-js";
import { Button, Skeleton, TextField } from "./ui";
import { formatTokens, modelPrefix, modelSuffix } from "../utils/format";

interface AccessInfo {
  available?: boolean;
  requires_seems_legit?: boolean;
  required_discord_roles?: string[];
}

interface Model {
  id: string;
  prefix: string;
  visibility?: string;
  context_window?: number;
  max_input_tokens?: number;
  max_output_tokens?: number;
  supports_images?: boolean;
  supports_audio?: boolean;
  requires_seems_legit?: boolean;
  required_roles: string[];
}

interface Policy {
  seems_legit_required_prefixes?: string[];
  seems_legit_required_role_label?: string;
  seems_legit_required_role_public?: boolean;
}

const LIVE_ENDPOINT = "https://api.freetheai.xyz/v1/models/full";
const LIVE_KEY = "freetheai.xyz";
const DISABLED = new Set<string>();
const PAGE_SIZE = 80;

// ── Field validation helpers ──
const str = (v: unknown): string | undefined => typeof v === "string" && v.trim() ? v.trim() : undefined;
const posInt = (v: unknown): number | undefined => typeof v === "number" && Number.isFinite(v) && v > 0 ? v : undefined;

const SUPPORTED_ROUTES: Array<{
  path: string;
  label: string;
  description: string;
}> = [
  {
    path: "/v1/chat/completions",
    label: "Chat Completions",
    description: "OpenAI-compatible chat with streaming and tool calling.",
  },
  {
    path: "/v1/messages",
    label: "Messages",
    description: "Anthropic-compatible Messages route with system prompts and tool use.",
  },
  {
    path: "/v1/responses",
    label: "Responses",
    description: "Responses-style route with the same key and model alias.",
  },
];

const collator = new Intl.Collator(undefined, { sensitivity: "base", numeric: true });

const formatTokensFull = (n: number): string => n.toLocaleString();

const FILTER_OPTIONS = ["chat", "images", "audio", "gated", "long"] as const;
type FilterKey = typeof FILTER_OPTIONS[number];

const FILTER_LABELS: Record<FilterKey, string> = {
  chat: "Chat",
  images: "Images",
  audio: "Audio",
  long: "128k+ context",
  gated: "Verified members",
};

const modelSupportsImages = (model: Model): boolean =>
  model.supports_images === true ||
  model.prefix === "img" ||
  model.prefix === "vhr" ||
  /image|vision|gpt-image/i.test(model.id);

const modelSupportsAudio = (model: Model): boolean =>
  model.supports_audio === true ||
  /(^|\/)(grok-stt|grok-tts)$/i.test(model.id) ||
  /tts|stt|speech|transcription/i.test(model.id);

const modelContext = (model: Model): number => model.context_window ?? model.max_input_tokens ?? 0;

const TYPE_PREDICATES: Record<FilterKey, (m: Model) => boolean> = {
  chat: (m) => !modelSupportsAudio(m),
  images: (m) => modelSupportsImages(m),
  audio: (m) => modelSupportsAudio(m),
  gated: (m) => m.requires_seems_legit,
  long: (m) => modelContext(m) >= 128_000,
};

const matchesAnyType = (m: Model, types: Set<FilterKey>): boolean => {
  for (const key of types) { if (TYPE_PREDICATES[key](m)) return true; }
  return false;
};

const modelRoutes = (model: Model) => {
  const suffix = modelSuffix(model.id).toLowerCase();
  if (suffix.includes("stt") || suffix.includes("transcription")) {
    return [
      { path: "/v1/audio/transcriptions", label: "Speech to text", description: "OpenAI-compatible multipart audio transcription." },
    ];
  }
  if (suffix.includes("tts") || suffix.includes("speech")) {
    return [
      { path: "/v1/audio/speech", label: "Text to speech", description: "OpenAI-compatible speech generation." },
    ];
  }
  if (model.prefix === "img" || model.prefix === "vhr" || /gpt-image|image/i.test(suffix)) {
    return [
      { path: "/v1/images/generations", label: "Image generation", description: "OpenAI-compatible image generation." },
      { path: "/v1/images/edits", label: "Image edits", description: "Image editing with an input image." },
    ];
  }
  return SUPPORTED_ROUTES;
};

// ── Pure helpers extracted from CatalogBrowser ──

const parseModel = (i: any): Model | null => {
  const _id = str(i?.id);
  if (!_id) return null;
  const pfx = str(i?.prefix) ?? modelPrefix(_id);
  const access = (i?.access ?? {}) as AccessInfo;
  const requiredRoles = Array.isArray(access.required_discord_roles)
    ? access.required_discord_roles.filter((r): r is string => typeof r === "string")
    : [];
  const requiresSeemsLegit =
    i?.requires_seems_legit === true ||
    access.requires_seems_legit === true ||
    requiredRoles.includes("seems_legit");
  const out: Model = { id: _id, prefix: pfx, required_roles: requiredRoles };
  for (const f of [["visibility", str], ["context_window", posInt], ["max_input_tokens", posInt], ["max_output_tokens", posInt]] as [string, typeof str][]) {
    const v = f[1]((i as any)[f[0]]);
    if (v) (out as any)[f[0]] = v;
  }
  for (const k of ["supports_images", "supports_audio"]) {
    if (typeof (i as any)[k] === "boolean") (out as any)[k] = (i as any)[k];
  }
  if (requiresSeemsLegit) out.requires_seems_legit = true;
  return out;
};

const filterModels = (models: Model[], prefixSet: Set<string>, typeSet: Set<FilterKey>, query: string): Model[] => {
  if (prefixSet.size > 0) models = models.filter((m) => prefixSet.has(m.prefix));
  if (typeSet.size > 0) models = models.filter((m) => matchesAnyType(m, typeSet));
  const q = query.trim().toLowerCase();
  if (q) models = models.filter((m) => m.id.toLowerCase().includes(q));
  return [...models].sort((a, b) => {
    const access = Number(a.requires_seems_legit === true) - Number(b.requires_seems_legit === true);
    if (access !== 0) return access;
    const ctx = modelContext(b) - modelContext(a);
    return ctx !== 0 ? ctx : collator.compare(a.id, b.id);
  });
};

const prefixLabel = (sel: Set<string>): string => {
  if (sel.size === 0) return "all providers";
  if (sel.size === 1) { const [only] = sel; return `${only}/*`; }
  return `${sel.size} providers`;
};

const prefixButtonLabel = (sel: Set<string>): string => {
  if (sel.size === 0) return "All prefixes";
  if (sel.size === 1) { const [only] = sel; return `${only}/*`; }
  return `${sel.size} prefixes`;
};

const typeButtonLabel = (sel: Set<FilterKey>, labels: Record<FilterKey, string>): string => {
  if (sel.size === 0) return "All capabilities";
  if (sel.size === 1) { const [only] = sel; return labels[only]; }
  return `${sel.size} capabilities`;
};

const fetchModels = async (): Promise<{ payload: any; src: "live" | "snapshot" }> => {
  try {
    const res = await fetch(LIVE_ENDPOINT, {
      headers: { Accept: "application/json", Authorization: `Bearer ${LIVE_KEY}` },
    });
    if (!res.ok) throw new Error(`Status ${res.status}`);
    return { payload: await res.json(), src: "live" };
  } catch (error) {
    const res = await fetch("/models.json", { headers: { Accept: "application/json" } });
    if (!res.ok) throw new Error(`Status ${res.status}`);
    console.warn("Falling back to bundled model catalog snapshot.", error);
    return { payload: await res.json(), src: "snapshot" };
  }
};

const readCatalogParams = () => {
  if (typeof window === "undefined") return { prefixes: [] as string[], types: [] as FilterKey[], query: "" };
  const params = new URLSearchParams(window.location.search);
  const rawPrefix = params.get("prefix")?.trim() || "";
  const prefixes = rawPrefix && !/^(all|\*)$/.test(rawPrefix)
    ? rawPrefix.split(",").map(p => p.trim()).filter(Boolean)
    : [];
  const legacyType = params.get("type")?.trim() ||
    (params.get("images") === "1" ? "images" : "") ||
    (params.get("seemslegit") === "1" ? "gated" : "");
  const validKeys = new Set<string>(FILTER_OPTIONS);
  return {
    prefixes,
    types: legacyType ? legacyType.split(",").map(t => t.trim()).filter(t => validKeys.has(t)) as FilterKey[] : [],
    query: params.get("q")?.trim() || "",
  };
};

// ── Model Card ──

function ModelCard({ model, onSelect }: { model: Model; onSelect: (m: Model) => void }) {
    const ctx = modelContext(model);
    const out = model.max_output_tokens;
    return (
        <article
            class={`model-card${model.requires_seems_legit ? " is-gated" : ""}`}
            role="button"
            tabindex="0"
            aria-haspopup="dialog"
            aria-label={`Open details for ${model.id}`}
            data-sound="interaction.tap"
            onClick={(e) => {
                if ((e.target as HTMLElement).closest(".model-copy")) return;
                onSelect(model);
            }}
            onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    onSelect(model);
                }
            }}
        >
            <div class="model-card-top">
                <span class="model-prefix">{model.prefix}/*</span>
            </div>
            <code class="model-id">{model.id}</code>
            <div class="model-meta">
                {ctx > 0 && (
                    <span class="model-chip" title="Total context window">
                        <strong>{formatTokens(ctx)}</strong> ctx
                    </span>
                )}
                {out !== undefined && (
                    <span class="model-chip" title="Maximum output tokens">
                        <strong>{formatTokens(out)}</strong> out
                    </span>
                )}
                {modelSupportsImages(model) && (
                    <span class="model-chip is-images" title="Supports image inputs or generation">
                        <span class="material-symbols-outlined model-chip-icon" aria-hidden="true">image</span>
                        Images
                    </span>
                )}
                {modelSupportsAudio(model) && (
                    <span class="model-chip is-audio" title="Supports an audio route">
                        <span class="material-symbols-outlined model-chip-icon" aria-hidden="true">graphic_eq</span>
                        Audio
                    </span>
                )}
            </div>
            <button
                class="model-copy"
                title="Copy model alias"
                aria-label={"Copy " + model.id}
                data-sound="interaction.confirm"
                onClick={(e) => {
                    e.preventDefault();
                    e.stopPropagation();
                    navigator.clipboard.writeText(model.id).catch((error) => {
                        console.error("Failed to copy model alias", error);
                    });
                    const btn = e.currentTarget as HTMLElement;
                    const icon = btn.querySelector(".material-symbols-outlined");
                    if (icon) {
                        icon.textContent = "check";
                        setTimeout(() => { icon.textContent = "content_copy"; }, 1500);
                    }
                }}
            >
                <span class="material-symbols-outlined">content_copy</span>
            </button>
        </article>
    );
}

// ── Model Detail Modal ──

function ModelDetailModal({ model, onClose, verifiedLabel }: { model: Model; onClose: () => void; verifiedLabel: string }) {
    return (
        <div
            class="model-modal-backdrop"
            role="dialog"
            aria-modal="true"
            aria-label={`${model.id} details`}
            data-sound="overlay.close"
            onClick={onClose}
        >
            <article
                class={`model-modal${model.requires_seems_legit ? " is-gated" : ""}`}
                onClick={(e) => e.stopPropagation()}
            >
                <header class="model-modal-head">
                    <div>
                        <span class="model-modal-prefix">{model.prefix}/*</span>
                        <code class="model-modal-id">{model.id}</code>
                    </div>
                    <button
                        type="button"
                        class="model-modal-close"
                        aria-label="Close"
                        data-sound="overlay.close"
                        onClick={onClose}
                    >
                        <span class="material-symbols-outlined" aria-hidden="true">close</span>
                    </button>
                </header>

                <section class="model-modal-meta">
                    {model.context_window !== undefined && (
                        <div>
                            <span>Context window</span>
                            <strong>{formatTokensFull(model.context_window)} tokens</strong>
                        </div>
                    )}
                    {model.max_input_tokens !== undefined && model.max_input_tokens !== model.context_window && (
                        <div>
                            <span>Max input</span>
                            <strong>{formatTokensFull(model.max_input_tokens)} tokens</strong>
                        </div>
                    )}
                    {model.max_output_tokens !== undefined && (
                        <div>
                            <span>Max output</span>
                            <strong>{formatTokensFull(model.max_output_tokens)} tokens</strong>
                        </div>
                    )}
                    <div>
                        <span>Provider prefix</span>
                        <strong>{model.prefix}/*</strong>
                    </div>
                    <div>
                        <span>Image support</span>
                        <strong>{modelSupportsImages(model) ? "Yes" : "No"}</strong>
                    </div>
                    <div>
                        <span>Audio route</span>
                        <strong>{modelSupportsAudio(model) ? "Yes" : "No"}</strong>
                    </div>
                    <Show when={model.visibility}>
                        <div>
                            <span>Visibility</span>
                            <strong>{model.visibility === "role_gated" ? "Verified members" : "Public catalog"}</strong>
                        </div>
                    </Show>
                    <Show when={model.requires_seems_legit}>
                        <div>
                            <span>Access</span>
                            <strong>Verified members only</strong>
                        </div>
                    </Show>
                </section>

                <Show when={model.requires_seems_legit}>
                    <p class="model-modal-gate">
                        <span class="material-symbols-outlined" aria-hidden="true">verified_user</span>
                        <span>
                            This model is available to {verifiedLabel} on the FreeTheAi Discord server.
                            Run <code>/checkin</code> daily once you have access.
                        </span>
                    </p>
                </Show>

                <section class="model-modal-routes">
                    <h4>Supported API routes</h4>
                    <p>Use the same API key and model alias on the supported route for this model.</p>
                    <ul>
                        <For each={modelRoutes(model)}>
                            {(route) => (
                                <li>
                                    <code>POST {route.path}</code>
                                    <span>{route.description}</span>
                                </li>
                            )}
                        </For>
                    </ul>
                </section>

                <footer class="model-modal-foot">
                    <button
                        type="button"
                        class="model-modal-copy"
                        data-sound="interaction.confirm"
                        onClick={(e) => {
                            navigator.clipboard.writeText(model.id).catch((error) => {
                                console.error("Failed to copy model alias", error);
                            });
                            const btn = e.currentTarget as HTMLButtonElement;
                            const original = btn.textContent;
                            btn.textContent = "Copied";
                            setTimeout(() => { btn.textContent = original; }, 1500);
                        }}
                    >
                        Copy alias
                    </button>
                    <a class="model-modal-docs" href="/docs#compatibility">View API docs</a>
                </footer>
            </article>
        </div>
    );
}

// ── Catalog Filters Toolbar sub-component ──

function CatalogFiltersToolbar(props: {
  query: string; setQuery: (v: string) => void; setPage: (v: number | ((p: number) => number)) => void;
  prefixes: Set<string>; togglePrefix: (p: string) => void; prefixCounts: [string, number][];
  typeFilters: Set<FilterKey>; toggleType: (k: FilterKey) => void; visibleTypeOptions: FilterKey[];
  prefixButtonLabel: string; typeButtonLabel: string;
}) {
  return (
    <div class="catalog-toolbar">
      <div class="catalog-search-field">
        <span class="material-symbols-outlined catalog-search-icon">search</span>
        <TextField
          class="catalog-search-input"
          value={props.query}
          placeholder="Search model aliases..."
          onChange={(v: string) => { props.setQuery(v); props.setPage(1); }}
        />
      </div>
      <div class="catalog-filter-group">
        <details class="catalog-filter">
          <summary class={`catalog-filter-trigger ${props.prefixes.size > 0 ? "is-active" : ""}`} data-sound="overlay.expand">
            <span class="catalog-filter-label">Prefix</span>
            <span class="catalog-filter-value">{props.prefixButtonLabel}</span>
            <Show when={props.prefixes.size > 0}>
              <span class="catalog-filter-count">{props.prefixes.size}</span>
            </Show>
            <span class="material-symbols-outlined catalog-filter-caret" aria-hidden="true">expand_more</span>
          </summary>
          <div class="catalog-filter-menu" role="group" aria-label="Filter by prefix">
            <For each={props.prefixCounts}>
              {([pfx, count]) => (
                <label class={`catalog-filter-option ${props.prefixes.has(pfx) ? "is-active" : ""}`}>
                  <input name="prefix-filter" type="checkbox" checked={props.prefixes.has(pfx)} onChange={() => props.togglePrefix(pfx)} data-sound="interaction.toggle" />
                  <span class="catalog-filter-option-name">{pfx}/*</span>
                  <span class="catalog-filter-option-count">{count}</span>
                </label>
              )}
            </For>
          </div>
        </details>
        <details class="catalog-filter">
          <summary class={`catalog-filter-trigger ${props.typeFilters.size > 0 ? "is-active" : ""}`} data-sound="overlay.expand">
            <span class="catalog-filter-label">Capability</span>
            <span class="catalog-filter-value">{props.typeButtonLabel}</span>
            <Show when={props.typeFilters.size > 0}>
              <span class="catalog-filter-count">{props.typeFilters.size}</span>
            </Show>
            <span class="material-symbols-outlined catalog-filter-caret" aria-hidden="true">expand_more</span>
          </summary>
          <div class="catalog-filter-menu" role="group" aria-label="Filter by capability">
            <For each={props.visibleTypeOptions}>
              {(key) => (
                <label class={`catalog-filter-option ${props.typeFilters.has(key) ? "is-active" : ""}`}>
                  <input name="capability-filter" type="checkbox" checked={props.typeFilters.has(key)} onChange={() => props.toggleType(key)} data-sound="interaction.toggle" />
                  <span class="catalog-filter-option-name">{FILTER_LABELS[key]}</span>
                </label>
              )}
            </For>
          </div>
        </details>
      </div>
    </div>
  );
}

// ── Catalog Pagination sub-component ──

function CatalogPagination({ page, pageCount, filteredCount, totalCount, setPage }: {
  page: number; pageCount: number; filteredCount: number; totalCount: number;
  setPage: (v: number | ((p: number) => number)) => void;
}) {
  return (
    <div class="catalog-pagination">
      <span class="catalog-pagination-count">
        {totalCount === 0 ? "Loading..." : `${filteredCount.toLocaleString()} model${filteredCount !== 1 ? "s" : ""}`}
      </span>
      <Button variant="ghost" class="pagination-button" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Previous</Button>
      <span class="catalog-pagination-text">{page} / {pageCount}</span>
      <Button variant="ghost" class="pagination-button" disabled={page >= pageCount} onClick={() => setPage((p) => p + 1)}>Next</Button>
    </div>
  );
}

export default function CatalogBrowser() {
  const [allModels, setAllModels] = createSignal<Model[]>([]);
  const [policy, setPolicy] = createSignal<Policy | null>(null);
  const [query, setQuery] = createSignal("");
  const [page, setPage] = createSignal(1);
  const [prefixes, setPrefixes] = createSignal<Set<string>>(new Set());
  const [typeFilters, setTypeFilters] = createSignal<Set<FilterKey>>(new Set());
  const [source, setSource] = createSignal<"live" | "snapshot" | "error">("live");
  const [loadError, setLoadError] = createSignal("");
  const [selected, setSelected] = createSignal<Model | null>(null);

  const togglePrefix = (pfx: string) => {
    setPrefixes((prev) => {
      const next = new Set(prev);
      if (next.has(pfx)) next.delete(pfx);
      else next.add(pfx);
      return next;
    });
    setPage(1);
  };

  const toggleType = (key: FilterKey) => {
    setTypeFilters((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
    setPage(1);
  };

  const prefixCounts = () => {
    const m = new Map<string, number>();
    for (const { prefix: pfx } of allModels()) m.set(pfx, (m.get(pfx) ?? 0) + 1);
    return [...m.entries()].sort((a, b) => b[1] - a[1]);
  };

  const hasImageModel = () => allModels().some(modelSupportsImages);
  const hasAudioModel = () => allModels().some(modelSupportsAudio);
  const hasGatedModel = () => allModels().some((m) => m.requires_seems_legit);

  const filteredModels = () => filterModels(allModels(), prefixes(), typeFilters(), query());

  const pageCount = () => Math.max(1, Math.ceil(filteredModels().length / PAGE_SIZE));
  const visibleModels = () => {
    const start = (page() - 1) * PAGE_SIZE;
    return filteredModels().slice(start, start + PAGE_SIZE);
  };

  createEffect(() => {
    if (page() > pageCount()) setPage(pageCount());
  });

  createEffect(() => {
    const sel = prefixes();
    if (sel.size === 0) return;
    if (allModels().length === 0) return;
    const valid = new Set(prefixCounts().map(([pfx]) => pfx));
    let dirty = false;
    const next = new Set<string>();
    for (const pfx of sel) {
      if (valid.has(pfx)) next.add(pfx);
      else dirty = true;
    }
    if (dirty) {
      setPrefixes(next);
      setPage(1);
    }
  });

  createEffect(() => {
    if (typeof window === "undefined") return;
    const params = new URLSearchParams(window.location.search);
    const pfxList = [...prefixes()];
    const typeList = [...typeFilters()];
    const search = query().trim();
    if (pfxList.length === 0) params.delete("prefix");
    else params.set("prefix", pfxList.join(","));
    params.delete("images");
    params.delete("seemslegit");
    params.delete("sort");
    if (typeList.length === 0) params.delete("type");
    else params.set("type", typeList.join(","));
    if (search) params.set("q", search);
    else params.delete("q");
    const next = `${window.location.pathname}${params.toString() ? `?${params}` : ""}${window.location.hash}`;
    if (next !== `${window.location.pathname}${window.location.search}${window.location.hash}`) {
      window.history.replaceState(null, "", next);
    }
  });

  onMount(() => {
    const params = readCatalogParams();
    if (params.query) setQuery(params.query);
    if (params.prefixes.length > 0) setPrefixes(new Set(params.prefixes));
    if (params.types.length > 0) setTypeFilters(new Set(params.types));

    const handleKey = (event: KeyboardEvent) => {
      if (event.key === "Escape" && selected()) setSelected(null);
    };
    document.addEventListener("keydown", handleKey);
    onCleanup(() => document.removeEventListener("keydown", handleKey));
  });

  onMount(async () => {
    try {
      const { payload, src } = await fetchModels();
      const items = Array.isArray(payload?.data) ? payload.data : [];
      setAllModels(
        items
          .map(parseModel)
          .filter((m: Model | null): m is Model => m !== null)
          .filter((m: Model) => !DISABLED.has(m.prefix))
          .sort((a, b) => collator.compare(a.id, b.id))
      );
      if (payload?.policy && typeof payload.policy === "object") setPolicy(payload.policy as Policy);
      setSource(src);
    } catch (err) {
      setSource("error");
      setLoadError(err instanceof Error ? err.message : "Failed to load model catalog.");
    }
  });

  const providerLabel = () => prefixLabel(prefixes());

  const resultLabel = () => {
    if (allModels().length === 0 && source() !== "error") return "Loading model catalog...";
    const count = filteredModels().length;
    const plural = count === 1 ? "model" : "models";
    return `${count.toLocaleString()} ${plural} across ${providerLabel()}`;
  };

  const filtersActive = () =>
    query().trim() !== "" ||
    prefixes().size > 0 ||
    typeFilters().size > 0;

  const clearFilters = () => {
    setQuery("");
    setPrefixes(new Set());
    setTypeFilters(new Set());
    setPage(1);
  };

  const verifiedMemberLabel = () => {
    const label = policy()?.seems_legit_required_role_label;
    const normalized = label?.toLowerCase().replace(/[\s-]+/g, "_");
    if (!normalized || normalized === "seems_legit") return "Verified members";
    return label;
  };

  const visibleTypeOptions = (): FilterKey[] => {
    const list: FilterKey[] = ["chat"];
    if (hasImageModel()) list.push("images");
    if (hasAudioModel()) list.push("audio");
    list.push("long");
    if (hasGatedModel()) list.push("gated");
    return list;
  };

  return (
    <div class="panel catalog-panel">
      <div class="catalog-panel-head">
        <div>
          <h3>Models</h3>
        </div>
      </div>

      <CatalogFiltersToolbar
        query={query()} setQuery={setQuery} setPage={setPage}
        prefixes={prefixes()} togglePrefix={togglePrefix} prefixCounts={prefixCounts()}
        typeFilters={typeFilters()} toggleType={toggleType} visibleTypeOptions={visibleTypeOptions()}
        prefixButtonLabel={prefixButtonLabel(prefixes())} typeButtonLabel={typeButtonLabel(typeFilters(), FILTER_LABELS)}
      />

      <Show when={hasGatedModel()}>
        <blockquote class="catalog-note">
          Orange-outlined models are available to {verifiedMemberLabel()}.
        </blockquote>
      </Show>

      <div class="catalog-summary" aria-live="polite">
        <span>{resultLabel()}</span>
        <Show when={filtersActive()}>
          <button type="button" onClick={clearFilters} data-sound="interaction.subtle">
            Clear filters
          </button>
        </Show>
      </div>

      <div class={`catalog-results ${visibleModels().length <= 6 ? "is-short" : ""}`}>
        <Show
          when={visibleModels().length > 0}
          fallback={
            <div class="catalog-empty">
              {source() === "error"
                ? loadError()
                : allModels().length === 0
                ? <Skeleton width="200" height="14" />
                : "No models match your search."}
            </div>
          }
        >
          <For each={visibleModels()}>
            {(model) => <ModelCard model={model} onSelect={setSelected} />}
          </For>
        </Show>
      </div>

      <CatalogPagination
        page={page()} pageCount={pageCount()} filteredCount={filteredModels().length}
        totalCount={allModels().length} setPage={setPage}
      />

      <Show when={selected()}>
        {(model) => <ModelDetailModal model={model()} onClose={() => setSelected(null)} verifiedLabel={verifiedMemberLabel()} />}
      </Show>
    </div>
  );
}

// site/src/features/model-catalog-search/ui/CatalogBrowser.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import type { CatalogPolicy, Model } from "@/entities/model";
import { parseModel, modelSupportsAudio, modelSupportsImage } from "@/entities/model";
import { modelPrefix } from "@/shared/lib/format";
import { Button, DropdownMenu, Skeleton, TextField } from "@/shared/ui";
import type { DropdownMenuOption } from "@/shared/ui";
import { fetchModels } from "../lib/fetchModels";
import {
    FILTER_LABELS,
    filterModels,
    prefixButtonLabel,
    prefixLabel,
    readCatalogParams,
    typeButtonLabel,
    collatorCompare,
    type FilterKey,
} from "../lib/filters";
import ModelCard from "./ModelCard.vue";
import ModelDetailModal from "./ModelDetailModal.vue";

const PAGE_SIZE = 80;
const DISABLED = new Set<string>();

const allModels = ref<Model[]>([]);
const policy = ref<CatalogPolicy | null>(null);
const query = ref("");
const page = ref(1);
const prefixes = ref<Set<string>>(new Set());
const typeFilters = ref<Set<FilterKey>>(new Set());
const source = ref<"live" | "snapshot" | "error">("live");
const loadError = ref("");
const selected = ref<Model | null>(null);
let mounted = false;

function togglePrefix(pfx: string): void {
    const next = new Set(prefixes.value);
    if (next.has(pfx)) next.delete(pfx);
    else next.add(pfx);
    prefixes.value = next;
    page.value = 1;
}

function toggleType(key: string): void {
    const filterKey = key as FilterKey;
    const next = new Set(typeFilters.value);
    if (next.has(filterKey)) next.delete(filterKey);
    else next.add(filterKey);
    typeFilters.value = next;
    page.value = 1;
}

const prefixCounts = computed<[string, number][]>(() => {
    const m = new Map<string, number>();
    for (const { prefix } of allModels.value) m.set(prefix, (m.get(prefix) ?? 0) + 1);
    return [...m.entries()].sort((a, b) => b[1] - a[1]);
});

const hasAudioModel = computed(() => allModels.value.some((m) => modelSupportsAudio(m)));
const hasImageModel = computed(() => allModels.value.some((m) => modelSupportsImage(m)));
const hasGatedModel = computed(() => allModels.value.some((m) => m.requires_seems_legit));

const filteredModels = computed(() => filterModels(allModels.value, prefixes.value, typeFilters.value, query.value));
const pageCount = computed(() => Math.max(1, Math.ceil(filteredModels.value.length / PAGE_SIZE)));
const visibleModels = computed(() => {
    const start = (page.value - 1) * PAGE_SIZE;
    return filteredModels.value.slice(start, start + PAGE_SIZE);
});

watch([page, pageCount], () => {
    if (page.value > pageCount.value) page.value = pageCount.value;
});

watch([prefixes, allModels], () => {
    if (prefixes.value.size === 0 || allModels.value.length === 0) return;
    const valid = new Set(prefixCounts.value.map(([pfx]) => pfx));
    let dirty = false;
    const next = new Set<string>();
    for (const pfx of prefixes.value) {
        if (valid.has(pfx)) next.add(pfx);
        else dirty = true;
    }
    if (dirty) {
        prefixes.value = next;
        page.value = 1;
    }
});

watch([prefixes, typeFilters, query], () => {
    if (typeof window === "undefined" || !mounted) return;
    const params = new URLSearchParams(window.location.search);
    const pfxList = [...prefixes.value];
    const typeList = [...typeFilters.value];
    const search = query.value.trim();
    if (pfxList.length === 0) params.delete("prefix");
    else params.set("prefix", pfxList.join(","));
    params.delete("images");
    params.delete("seemslegit");
    params.delete("sort");
    if (typeList.length === 0) params.delete("type");
    else params.set("type", typeList.join(","));
    if (search) params.set("q", search);
    else params.delete("q");
    const next = `${window.location.pathname}${params.toString() ? `?${params}` : ""}${window.location.hash}`;
    if (next !== `${window.location.pathname}${window.location.search}${window.location.hash}`) {
        window.history.replaceState(null, "", next);
    }
});

function onEscape(event: KeyboardEvent): void {
    if (event.key === "Escape") selected.value = null;
}

onMounted(async () => {
    const params = readCatalogParams();
    if (params.query) query.value = params.query;
    if (params.prefixes.length > 0) prefixes.value = new Set(params.prefixes);
    if (params.types.length > 0) typeFilters.value = new Set(params.types);
    mounted = true;

    document.addEventListener("keydown", onEscape);

    try {
        const { payload, src } = await fetchModels();
        const payloadRecord = payload && typeof payload === "object" ? (payload as Record<string, unknown>) : null;
        const items = Array.isArray(payloadRecord?.data) ? (payloadRecord.data as unknown[]) : [];
        allModels.value = items
            .map(parseModel)
            .filter((m): m is Model => m !== null)
            .filter((m) => !DISABLED.has(m.prefix))
            .sort((a, b) => collatorCompare(a.id, b.id));
        if (payloadRecord?.policy && typeof payloadRecord.policy === "object") policy.value = payloadRecord.policy as CatalogPolicy;
        source.value = src;

        const livePrefixes = new Set(
            items
                .map((m) => {
                    const record = m as Record<string, unknown>;
                    const id = typeof record.id === "string" ? record.id : "";
                    return typeof record.prefix === "string" && record.prefix ? record.prefix : modelPrefix(id);
                })
                .filter(Boolean),
        );
        const heroChips = document.querySelectorAll(".models-hero-chip");
        heroChips.forEach((chip, i) => {
            const value = i === 0 ? items.length : livePrefixes.size;
            const label = i === 0 ? "model" : "provider";
            const labelPlural = value === 1 ? label : `${label}s`;
            chip.innerHTML = `<strong>${value}</strong> ${labelPlural}`;
        });
        const lede = document.querySelector(".models-lede");
        if (lede) {
            lede.textContent = `${items.length} OpenAI-compatible chat, image, and audio model aliases across ${livePrefixes.size} provider prefixes. Search, filter, and copy any alias into your client.`;
        }
    } catch (err) {
        source.value = "error";
        loadError.value = err instanceof Error ? err.message : "Failed to load model catalog.";
    }
});

onBeforeUnmount(() => {
    document.removeEventListener("keydown", onEscape);
});

const providerLabel = computed(() => prefixLabel(prefixes.value));

const resultLabel = computed(() => {
    if (allModels.value.length === 0 && source.value !== "error") return "Loading model catalog...";
    const count = filteredModels.value.length;
    const plural = count === 1 ? "model" : "models";
    return `${count.toLocaleString()} ${plural} across ${providerLabel.value}`;
});

const filtersActive = computed(() => query.value.trim() !== "" || prefixes.value.size > 0 || typeFilters.value.size > 0);

function clearFilters(): void {
    query.value = "";
    prefixes.value = new Set();
    typeFilters.value = new Set();
    page.value = 1;
}

const verifiedMemberLabel = computed(() => {
    const label = policy.value?.seems_legit_required_role_label;
    const normalized = label?.toLowerCase().replace(/[\s-]+/g, "_");
    if (!normalized || normalized === "seems_legit") return "Verified members";
    return label ?? "Verified members";
});

const visibleTypeOptions = computed<FilterKey[]>(() => {
    const list: FilterKey[] = ["chat"];
    if (hasImageModel.value) list.push("image");
    if (hasAudioModel.value) list.push("audio");
    list.push("long");
    if (hasGatedModel.value) list.push("gated");
    return list;
});

const prefixMenuOptions = computed<DropdownMenuOption[]>(() =>
    prefixCounts.value.map(([pfx, count]) => ({ value: pfx, label: `${pfx}/*`, count, checked: prefixes.value.has(pfx) })),
);

const typeMenuOptions = computed<DropdownMenuOption[]>(() =>
    visibleTypeOptions.value.map((key) => ({ value: key, label: FILTER_LABELS[key], checked: typeFilters.value.has(key) })),
);

function onQueryChange(value: string): void {
    query.value = value;
    page.value = 1;
}
</script>

<template>
    <div class="panel catalog-panel">
        <div class="catalog-toolbar">
            <div class="catalog-search-field">
                <span class="material-symbols-outlined catalog-search-icon">search</span>
                <TextField class="catalog-search-input" :model-value="query" placeholder="Search model aliases..." @update:model-value="onQueryChange" />
            </div>
            <div class="catalog-filter-group">
                <DropdownMenu
                    trigger-label="Prefix"
                    :value-label="prefixButtonLabel(prefixes)"
                    :active-count="prefixes.size"
                    :options="prefixMenuOptions"
                    @toggle="togglePrefix"
                />
                <DropdownMenu
                    trigger-label="Capability"
                    :value-label="typeButtonLabel(typeFilters, FILTER_LABELS)"
                    :active-count="typeFilters.size"
                    :options="typeMenuOptions"
                    @toggle="toggleType"
                />
            </div>
        </div>

        <blockquote v-if="hasGatedModel" class="catalog-note">
            Orange-outlined models are available to {{ verifiedMemberLabel }}.
        </blockquote>

        <div class="catalog-summary" aria-live="polite">
            <span>{{ resultLabel }}</span>
            <button v-if="filtersActive" type="button" data-sound="interaction.subtle" @click="clearFilters">Clear filters</button>
        </div>

        <div class="catalog-results">
            <template v-if="visibleModels.length > 0">
                <ModelCard v-for="model in visibleModels" :key="model.id" :model="model" @select="selected = $event" />
            </template>
            <div v-else class="catalog-empty">
                <template v-if="source === 'error'">{{ loadError }}</template>
                <Skeleton v-else-if="allModels.length === 0" width="200" height="14" />
                <template v-else>No models match your search.</template>
            </div>
        </div>

        <div class="catalog-pagination">
            <span class="catalog-pagination-count">
                {{ allModels.length === 0 ? "Loading..." : `${filteredModels.length.toLocaleString()} model${filteredModels.length !== 1 ? "s" : ""}` }}
            </span>
            <Button variant="ghost" class="pagination-button" :disabled="page <= 1" @click="page -= 1">Previous</Button>
            <span class="catalog-pagination-text">{{ page }} / {{ pageCount }}</span>
            <Button variant="ghost" class="pagination-button" :disabled="page >= pageCount" @click="page += 1">Next</Button>
        </div>

        <ModelDetailModal v-if="selected" :model="selected" :verified-label="verifiedMemberLabel" @close="selected = null" />
    </div>
</template>
