// site/src/lib/features/model-catalog-search/ui/CatalogBrowser.svelte
<script lang="ts">
    import { onDestroy, onMount } from "svelte";
    import type { CatalogPolicy, Model } from "@/entities/model";
    import { modelSupportsAudio, modelSupportsImage, parseModel } from "@/entities/model";
    import { modelPrefix } from "@/shared/lib/format";
    import { watchDeps } from "@/shared/lib/watchDeps";
    import { Button, DropdownMenu, Skeleton, TextField } from "@/shared/ui";
    import type { DropdownMenuOption } from "@/shared/ui";
    import { fetchModels } from "../lib/fetchModels";
    import {
        FILTER_LABELS,
        filterModels,
        prefixButtonLabel,
        prefixLabel,
        readCatalogParams,
        typeButtonLabel,
        collatorCompare,
        type FilterKey,
    } from "../lib/filters";
    import ModelCard from "./ModelCard.svelte";
    import ModelDetailModal from "./ModelDetailModal.svelte";
    import CatalogOverview from "./CatalogOverview.svelte";

    const PAGE_SIZE = 80;
    const DISABLED = new Set<string>();

    let allModels = $state<Model[]>([]);
    let policy = $state<CatalogPolicy | null>(null);
    let query = $state("");
    let page = $state(1);
    let prefixes = $state<Set<string>>(new Set());
    let typeFilters = $state<Set<FilterKey>>(new Set());
    let source = $state<"live" | "snapshot" | "error">("live");
    let loadError = $state("");
    let selected = $state<Model | null>(null);
    let mounted = false;

    function togglePrefix(pfx: string): void {
        const next = new Set(prefixes);
        if (next.has(pfx)) next.delete(pfx);
        else next.add(pfx);
        prefixes = next;
        page = 1;
    }

    function toggleType(key: string): void {
        const filterKey = key as FilterKey;
        const next = new Set(typeFilters);
        if (next.has(filterKey)) next.delete(filterKey);
        else next.add(filterKey);
        typeFilters = next;
        page = 1;
    }

    const prefixCounts = $derived.by((): [string, number][] => {
        const m = new Map<string, number>();
        for (const { prefix } of allModels) m.set(prefix, (m.get(prefix) ?? 0) + 1);
        return [...m.entries()].sort((a, b) => b[1] - a[1]);
    });

    const hasAudioModel = $derived(allModels.some((m) => modelSupportsAudio(m)));
    const hasImageModel = $derived(allModels.some((m) => modelSupportsImage(m)));
    const hasGatedModel = $derived(allModels.some((m) => m.requires_seems_legit));

    const filteredModels = $derived(filterModels(allModels, prefixes, typeFilters, query));
    const pageCount = $derived(Math.max(1, Math.ceil(filteredModels.length / PAGE_SIZE)));
    const visibleModels = $derived.by(() => {
        const start = (page - 1) * PAGE_SIZE;
        return filteredModels.slice(start, start + PAGE_SIZE);
    });

    const clampPage = watchDeps(() => {
        if (page > pageCount) page = pageCount;
    });

    const pruneStalePrefixes = watchDeps(() => {
        if (prefixes.size === 0 || allModels.length === 0) return;
        const valid = new Set(prefixCounts.map(([pfx]) => pfx));
        let dirty = false;
        const next = new Set<string>();
        for (const pfx of prefixes) {
            if (valid.has(pfx)) next.add(pfx);
            else dirty = true;
        }
        if (dirty) {
            prefixes = next;
            page = 1;
        }
    });

    const syncUrl = watchDeps(() => {
        if (typeof window === "undefined" || !mounted) return;
        const params = new URLSearchParams(window.location.search);
        const pfxList = [...prefixes];
        const typeList = [...typeFilters];
        const search = query.trim();
        if (pfxList.length === 0) params.delete("prefix");
        else params.set("prefix", pfxList.join(","));
        params.delete("images");
        params.delete("seemslegit");
        params.delete("sort");
        if (typeList.length === 0) params.delete("type");
        else params.set("type", typeList.join(","));
        if (search) params.set("q", search);
        else params.delete("q");
        const next = `${window.location.pathname}${params.toString() ? `?${params}` : ""}${window.location.hash}`;
        if (next !== `${window.location.pathname}${window.location.search}${window.location.hash}`) {
            window.history.replaceState(null, "", next);
        }
    });

    function onEscape(event: KeyboardEvent): void {
        if (event.key === "Escape") selected = null;
    }

    onMount(async () => {
        const params = readCatalogParams();
        if (params.query) query = params.query;
        if (params.prefixes.length > 0) prefixes = new Set(params.prefixes);
        if (params.types.length > 0) typeFilters = new Set(params.types);
        mounted = true;

        document.addEventListener("keydown", onEscape);

        try {
            const { payload, src } = await fetchModels();
            const payloadRecord = payload && typeof payload === "object" ? (payload as Record<string, unknown>) : null;
            const items = Array.isArray(payloadRecord?.data) ? (payloadRecord.data as unknown[]) : [];
            allModels = items
                .map(parseModel)
                .filter((m): m is Model => m !== null)
                .filter((m) => !DISABLED.has(m.prefix))
                .sort((a, b) => collatorCompare(a.id, b.id));
            if (payloadRecord?.policy && typeof payloadRecord.policy === "object") policy = payloadRecord.policy as CatalogPolicy;
            source = src;

            const livePrefixes = new Set(
                items
                    .map((m) => {
                        const record = m as Record<string, unknown>;
                        const id = typeof record.id === "string" ? record.id : "";
                        return typeof record.prefix === "string" && record.prefix ? record.prefix : modelPrefix(id);
                    })
                    .filter(Boolean),
            );
            const heroChips = document.querySelectorAll(".models-hero-chip");
            heroChips.forEach((chip, i) => {
                const value = i === 0 ? items.length : livePrefixes.size;
                const label = i === 0 ? "model" : "provider";
                const labelPlural = value === 1 ? label : `${label}s`;
                chip.innerHTML = `<strong>${value}</strong> ${labelPlural}`;
            });
            const lede = document.querySelector(".models-lede");
            if (lede) {
                lede.textContent = `${items.length} OpenAI-compatible chat, image, and audio model aliases across ${livePrefixes.size} provider prefixes. Search, filter, and copy any alias into your client.`;
            }
        } catch (err) {
            source = "error";
            loadError = err instanceof Error ? err.message : "Failed to load model catalog.";
        }
    });

    onDestroy(() => {
        if (typeof document !== "undefined") document.removeEventListener("keydown", onEscape);
    });

    const providerLabel = $derived(prefixLabel(prefixes));

    const resultLabel = $derived.by(() => {
        if (allModels.length === 0 && source !== "error") return "Loading model catalog...";
        const count = filteredModels.length;
        const plural = count === 1 ? "model" : "models";
        return `${count.toLocaleString()} ${plural} across ${providerLabel}`;
    });

    const filtersActive = $derived(query.trim() !== "" || prefixes.size > 0 || typeFilters.size > 0);

    function clearFilters(): void {
        query = "";
        prefixes = new Set();
        typeFilters = new Set();
        page = 1;
    }

    const verifiedMemberLabel = $derived.by(() => {
        const label = policy?.seems_legit_required_role_label;
        const normalized = label?.toLowerCase().replace(/[\s-]+/g, "_");
        if (!normalized || normalized === "seems_legit") return "Verified members";
        return label ?? "Verified members";
    });

    const visibleTypeOptions = $derived.by((): FilterKey[] => {
        const list: FilterKey[] = ["chat"];
        if (hasImageModel) list.push("image");
        if (hasAudioModel) list.push("audio");
        list.push("long");
        if (hasGatedModel) list.push("gated");
        return list;
    });

    const prefixMenuOptions = $derived<DropdownMenuOption[]>(
        prefixCounts.map(([pfx, count]) => ({ value: pfx, label: `${pfx}/*`, count, checked: prefixes.has(pfx) })),
    );

    const typeMenuOptions = $derived<DropdownMenuOption[]>(
        visibleTypeOptions.map((key) => ({ value: key, label: FILTER_LABELS[key], checked: typeFilters.has(key) })),
    );

    function onQueryChange(value: string): void {
        query = value;
        page = 1;
    }
</script>

<div class="panel catalog-panel" use:clampPage={[page, pageCount]} use:pruneStalePrefixes={[prefixes, allModels]} use:syncUrl={[prefixes, typeFilters, query]}>
    <CatalogOverview models={allModels} />
    <div class="catalog-toolbar">
        <div class="catalog-search-field">
            <TextField class="catalog-search-input" value={query} placeholder="Search model aliases..." oninput={(e) => onQueryChange((e.target as HTMLInputElement).value)} />
        </div>
        <div class="catalog-filter-group">
            <DropdownMenu
                triggerLabel="Prefix"
                valueLabel={prefixButtonLabel(prefixes)}
                activeCount={prefixes.size}
                options={prefixMenuOptions}
                ontoggle={togglePrefix}
            />
            <DropdownMenu
                triggerLabel="Capability"
                valueLabel={typeButtonLabel(typeFilters, FILTER_LABELS)}
                activeCount={typeFilters.size}
                options={typeMenuOptions}
                ontoggle={toggleType}
            />
        </div>
    </div>

    {#if hasGatedModel}
        <blockquote class="catalog-note">
            Orange-outlined models are available to {verifiedMemberLabel}.
        </blockquote>
    {/if}

    <div class="catalog-summary" aria-live="polite">
        <span>{resultLabel}</span>
        {#if filtersActive}
            <button type="button" data-sound="interaction.subtle" onclick={clearFilters}>Clear filters</button>
        {/if}
    </div>

    <div class="catalog-results">
        {#if visibleModels.length > 0}
            {#each visibleModels as model (model.id)}
                <ModelCard {model} onselect={(m) => (selected = m)} />
            {/each}
        {:else}
            <div class="catalog-empty">
                {#if source === "error"}
                    {loadError}
                {:else if allModels.length === 0}
                    <Skeleton width="200" height="14" />
                {:else}
                    No models match your search.
                {/if}
            </div>
        {/if}
    </div>

    <div class="catalog-pagination">
        <span class="catalog-pagination-count">
            {allModels.length === 0 ? "Loading..." : `${filteredModels.length.toLocaleString()} model${filteredModels.length !== 1 ? "s" : ""}`}
        </span>
        <Button variant="ghost" class="pagination-button" disabled={page <= 1} onclick={() => (page -= 1)}>Previous</Button>
        <span class="catalog-pagination-text">{page} / {pageCount}</span>
        <Button variant="ghost" class="pagination-button" disabled={page >= pageCount} onclick={() => (page += 1)}>Next</Button>
    </div>

    {#if selected}
        <ModelDetailModal model={selected} verifiedLabel={verifiedMemberLabel} onclose={() => (selected = null)} />
    {/if}
</div>

// site/src/features/model-catalog-search/ui/CatalogBrowser.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import type { CatalogPolicy, Model } from "@/entities/model";
import { parseModel, modelSupportsAudio, modelSupportsImage } from "@/entities/model";
import { modelPrefix } from "@/shared/lib/format";
import { Button, DropdownMenu, Skeleton, TextField } from "@/shared/ui";
import type { DropdownMenuOption } from "@/shared/ui";
import { fetchModels } from "../lib/fetchModels";
import {
    FILTER_LABELS,
    filterModels,
    prefixButtonLabel,
    prefixLabel,
    readCatalogParams,
    typeButtonLabel,
    collatorCompare,
    type FilterKey,
} from "../lib/filters";
import ModelCard from "./ModelCard.vue";
import ModelDetailModal from "./ModelDetailModal.vue";
import CatalogOverview from "./CatalogOverview.vue";

const PAGE_SIZE = 80;
const DISABLED = new Set<string>();

const allModels = ref<Model[]>([]);
const policy = ref<CatalogPolicy | null>(null);
const query = ref("");
const page = ref(1);
const prefixes = ref<Set<string>>(new Set());
const typeFilters = ref<Set<FilterKey>>(new Set());
const source = ref<"live" | "snapshot" | "error">("live");
const loadError = ref("");
const selected = ref<Model | null>(null);
let mounted = false;

function togglePrefix(pfx: string): void {
    const next = new Set(prefixes.value);
    if (next.has(pfx)) next.delete(pfx);
    else next.add(pfx);
    prefixes.value = next;
    page.value = 1;
}

function toggleType(key: string): void {
    const filterKey = key as FilterKey;
    const next = new Set(typeFilters.value);
    if (next.has(filterKey)) next.delete(filterKey);
    else next.add(filterKey);
    typeFilters.value = next;
    page.value = 1;
}

const prefixCounts = computed<[string, number][]>(() => {
    const m = new Map<string, number>();
    for (const { prefix } of allModels.value) m.set(prefix, (m.get(prefix) ?? 0) + 1);
    return [...m.entries()].sort((a, b) => b[1] - a[1]);
});

const hasAudioModel = computed(() => allModels.value.some((m) => modelSupportsAudio(m)));
const hasImageModel = computed(() => allModels.value.some((m) => modelSupportsImage(m)));
const hasGatedModel = computed(() => allModels.value.some((m) => m.requires_seems_legit));

const filteredModels = computed(() => filterModels(allModels.value, prefixes.value, typeFilters.value, query.value));
const pageCount = computed(() => Math.max(1, Math.ceil(filteredModels.value.length / PAGE_SIZE)));
const visibleModels = computed(() => {
    const start = (page.value - 1) * PAGE_SIZE;
    return filteredModels.value.slice(start, start + PAGE_SIZE);
});

watch([page, pageCount], () => {
    if (page.value > pageCount.value) page.value = pageCount.value;
});

watch([prefixes, allModels], () => {
    if (prefixes.value.size === 0 || allModels.value.length === 0) return;
    const valid = new Set(prefixCounts.value.map(([pfx]) => pfx));
    let dirty = false;
    const next = new Set<string>();
    for (const pfx of prefixes.value) {
        if (valid.has(pfx)) next.add(pfx);
        else dirty = true;
    }
    if (dirty) {
        prefixes.value = next;
        page.value = 1;
    }
});

watch([prefixes, typeFilters, query], () => {
    if (typeof window === "undefined" || !mounted) return;
    const params = new URLSearchParams(window.location.search);
    const pfxList = [...prefixes.value];
    const typeList = [...typeFilters.value];
    const search = query.value.trim();
    if (pfxList.length === 0) params.delete("prefix");
    else params.set("prefix", pfxList.join(","));
    params.delete("images");
    params.delete("seemslegit");
    params.delete("sort");
    if (typeList.length === 0) params.delete("type");
    else params.set("type", typeList.join(","));
    if (search) params.set("q", search);
    else params.delete("q");
    const next = `${window.location.pathname}${params.toString() ? `?${params}` : ""}${window.location.hash}`;
    if (next !== `${window.location.pathname}${window.location.search}${window.location.hash}`) {
        window.history.replaceState(null, "", next);
    }
});

function onEscape(event: KeyboardEvent): void {
    if (event.key === "Escape") selected.value = null;
}

onMounted(async () => {
    const params = readCatalogParams();
    if (params.query) query.value = params.query;
    if (params.prefixes.length > 0) prefixes.value = new Set(params.prefixes);
    if (params.types.length > 0) typeFilters.value = new Set(params.types);
    mounted = true;

    document.addEventListener("keydown", onEscape);

    try {
        const { payload, src } = await fetchModels();
        const payloadRecord = payload && typeof payload === "object" ? (payload as Record<string, unknown>) : null;
        const items = Array.isArray(payloadRecord?.data) ? (payloadRecord.data as unknown[]) : [];
        allModels.value = items
            .map(parseModel)
            .filter((m): m is Model => m !== null)
            .filter((m) => !DISABLED.has(m.prefix))
            .sort((a, b) => collatorCompare(a.id, b.id));
        if (payloadRecord?.policy && typeof payloadRecord.policy === "object") policy.value = payloadRecord.policy as CatalogPolicy;
        source.value = src;

        const livePrefixes = new Set(
            items
                .map((m) => {
                    const record = m as Record<string, unknown>;
                    const id = typeof record.id === "string" ? record.id : "";
                    return typeof record.prefix === "string" && record.prefix ? record.prefix : modelPrefix(id);
                })
                .filter(Boolean),
        );
        const heroChips = document.querySelectorAll(".models-hero-chip");
        heroChips.forEach((chip, i) => {
            const value = i === 0 ? items.length : livePrefixes.size;
            const label = i === 0 ? "model" : "provider";
            const labelPlural = value === 1 ? label : `${label}s`;
            chip.innerHTML = `<strong>${value}</strong> ${labelPlural}`;
        });
        const lede = document.querySelector(".models-lede");
        if (lede) {
            lede.textContent = `${items.length} OpenAI-compatible chat, image, and audio model aliases across ${livePrefixes.size} provider prefixes. Search, filter, and copy any alias into your client.`;
        }
    } catch (err) {
        source.value = "error";
        loadError.value = err instanceof Error ? err.message : "Failed to load model catalog.";
    }
});

onBeforeUnmount(() => {
    document.removeEventListener("keydown", onEscape);
});

const providerLabel = computed(() => prefixLabel(prefixes.value));

const resultLabel = computed(() => {
    if (allModels.value.length === 0 && source.value !== "error") return "Loading model catalog...";
    const count = filteredModels.value.length;
    const plural = count === 1 ? "model" : "models";
    return `${count.toLocaleString()} ${plural} across ${providerLabel.value}`;
});

const filtersActive = computed(() => query.value.trim() !== "" || prefixes.value.size > 0 || typeFilters.value.size > 0);

function clearFilters(): void {
    query.value = "";
    prefixes.value = new Set();
    typeFilters.value = new Set();
    page.value = 1;
}

const verifiedMemberLabel = computed(() => {
    const label = policy.value?.seems_legit_required_role_label;
    const normalized = label?.toLowerCase().replace(/[\s-]+/g, "_");
    if (!normalized || normalized === "seems_legit") return "Verified members";
    return label ?? "Verified members";
});

const visibleTypeOptions = computed<FilterKey[]>(() => {
    const list: FilterKey[] = ["chat"];
    if (hasImageModel.value) list.push("image");
    if (hasAudioModel.value) list.push("audio");
    list.push("long");
    if (hasGatedModel.value) list.push("gated");
    return list;
});

const prefixMenuOptions = computed<DropdownMenuOption[]>(() =>
    prefixCounts.value.map(([pfx, count]) => ({ value: pfx, label: `${pfx}/*`, count, checked: prefixes.value.has(pfx) })),
);

const typeMenuOptions = computed<DropdownMenuOption[]>(() =>
    visibleTypeOptions.value.map((key) => ({ value: key, label: FILTER_LABELS[key], checked: typeFilters.value.has(key) })),
);

function onQueryChange(value: string): void {
    query.value = value;
    page.value = 1;
}
</script>

<template>
    <div class="panel catalog-panel">
        <CatalogOverview :models="allModels" />
        <div class="catalog-toolbar">
            <div class="catalog-search-field">
                <TextField class="catalog-search-input" :model-value="query" placeholder="Search model aliases..." @update:model-value="onQueryChange" />
            </div>
            <div class="catalog-filter-group">
                <DropdownMenu
                    trigger-label="Prefix"
                    :value-label="prefixButtonLabel(prefixes)"
                    :active-count="prefixes.size"
                    :options="prefixMenuOptions"
                    @toggle="togglePrefix"
                />
                <DropdownMenu
                    trigger-label="Capability"
                    :value-label="typeButtonLabel(typeFilters, FILTER_LABELS)"
                    :active-count="typeFilters.size"
                    :options="typeMenuOptions"
                    @toggle="toggleType"
                />
            </div>
        </div>

        <blockquote v-if="hasGatedModel" class="catalog-note">
            Orange-outlined models are available to {{ verifiedMemberLabel }}.
        </blockquote>

        <div class="catalog-summary" aria-live="polite">
            <span>{{ resultLabel }}</span>
            <button v-if="filtersActive" type="button" data-sound="interaction.subtle" @click="clearFilters">Clear filters</button>
        </div>

        <div class="catalog-results">
            <template v-if="visibleModels.length > 0">
                <ModelCard v-for="model in visibleModels" :key="model.id" :model="model" @select="selected = $event" />
            </template>
            <div v-else class="catalog-empty">
                <template v-if="source === 'error'">{{ loadError }}</template>
                <Skeleton v-else-if="allModels.length === 0" width="200" height="14" />
                <template v-else>No models match your search.</template>
            </div>
        </div>

        <div class="catalog-pagination">
            <span class="catalog-pagination-count">
                {{ allModels.length === 0 ? "Loading..." : `${filteredModels.length.toLocaleString()} model${filteredModels.length !== 1 ? "s" : ""}` }}
            </span>
            <Button variant="ghost" class="pagination-button" :disabled="page <= 1" @click="page -= 1">Previous</Button>
            <span class="catalog-pagination-text">{{ page }} / {{ pageCount }}</span>
            <Button variant="ghost" class="pagination-button" :disabled="page >= pageCount" @click="page += 1">Next</Button>
        </div>

        <ModelDetailModal v-if="selected" :model="selected" :verified-label="verifiedMemberLabel" @close="selected = null" />
    </div>
</template>
