// site/src/shared/ui/charts/Area.vue
<script setup lang="ts">
import CartesianSeries from "./CartesianSeries.vue";
import type { AreaVariant, StrokeVariant } from "@/shared/lib/dither/chart-types";

defineProps<{
    dataKey: string;
    variant?: AreaVariant;
    strokeVariant?: StrokeVariant;
    isClickable?: boolean;
}>();
</script>

<template>
    <CartesianSeries part="Area" kind="area" v-bind="$props"><slot /></CartesianSeries>
</template>

// site/src/lib/shared/ui/charts/Area.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import CartesianSeries from "./CartesianSeries.svelte";
    import type { AreaVariant, StrokeVariant } from "@/shared/lib/dither/chart-types";

    let {
        dataKey,
        variant,
        strokeVariant,
        isClickable,
        children,
    }: {
        dataKey: string;
        variant?: AreaVariant;
        strokeVariant?: StrokeVariant;
        isClickable?: boolean;
        children?: Snippet;
    } = $props();
</script>

<CartesianSeries part="Area" kind="area" {dataKey} {variant} {strokeVariant} {isClickable}>
    {@render children?.()}
</CartesianSeries>
