// site/_src_vue_backup/shared/ui/charts/Grid.vue
<script setup lang="ts">
import { computed } from "vue";
import { useChartPart } from "@/shared/lib/dither/chart-context";

const props = withDefaults(
    defineProps<{ horizontal?: boolean; vertical?: boolean; strokeDasharray?: string }>(),
    { horizontal: true, vertical: false, strokeDasharray: "3 3" },
);

const ctx = useChartPart("Grid");
const hTicks = computed(() => (props.horizontal ? ctx.y.ticks(4) : []));
</script>

<template>
    <svg v-if="ctx.ready" class="dk-layer dk-back">
        <g
            class="dk-grid"
            :stroke-dasharray="strokeDasharray"
            :transform="`translate(${ctx.margins.left},${ctx.margins.top})`"
        >
            <line
                v-for="t in hTicks"
                :key="`h-${t}`"
                :x1="0"
                :x2="ctx.plot.width"
                :y1="ctx.y(t)"
                :y2="ctx.y(t)"
            />
            <template v-if="vertical">
                <line
                    v-for="(_, i) in ctx.data"
                    :key="`v-${i}`"
                    :x1="ctx.xCenter(i)"
                    :x2="ctx.xCenter(i)"
                    :y1="0"
                    :y2="ctx.plot.height"
                />
            </template>
        </g>
    </svg>
</template>

// site/src/lib/shared/ui/charts/Grid.svelte
<script lang="ts">
    import { useChartPart } from "@/shared/lib/dither/chart-context";

    let {
        horizontal = true,
        vertical = false,
        strokeDasharray = "3 3",
    }: { horizontal?: boolean; vertical?: boolean; strokeDasharray?: string } = $props();

    const ctx = useChartPart("Grid");
    const hTicks = $derived(horizontal ? ctx.y.ticks(4) : []);
</script>

{#if ctx.ready}
    <svg class="dk-layer dk-back">
        <g class="dk-grid" stroke-dasharray={strokeDasharray} transform={`translate(${ctx.margins.left},${ctx.margins.top})`}>
            {#each hTicks as t (t)}
                <line x1={0} x2={ctx.plot.width} y1={ctx.y(t)} y2={ctx.y(t)} />
            {/each}
            {#if vertical}
                {#each ctx.data as _, i (i)}
                    <line x1={ctx.xCenter(i)} x2={ctx.xCenter(i)} y1={0} y2={ctx.plot.height} />
                {/each}
            {/if}
        </g>
    </svg>
{/if}
