// site/src/shared/ui/charts/Radar.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, watch } from "vue";
import { usePolarPart } from "@/shared/lib/dither/chart-context";
import type { AreaVariant } from "@/shared/lib/dither/chart-types";

const props = withDefaults(defineProps<{ dataKey: string; variant?: AreaVariant }>(), {
    variant: "gradient",
});

const ctx = usePolarPart("Radar", "radar");

if (import.meta.env.DEV && !ctx.config[props.dataKey]) {
    console.warn(
        `<Radar dataKey="${props.dataKey}">: "${props.dataKey}" is not in the chart \`config\`. Add it so the series has a colour and label.`,
    );
}

onMounted(() => ctx.registerVariant(props.dataKey, props.variant));
watch(
    () => [props.dataKey, props.variant],
    () => ctx.registerVariant(props.dataKey, props.variant),
);
onBeforeUnmount(() => ctx.unregisterVariant(props.dataKey));
</script>

<template><span hidden /></template>

// site/src/lib/shared/ui/charts/Radar.svelte
<script lang="ts">
    import { onDestroy } from "svelte";
    import { usePolarPart } from "@/shared/lib/dither/chart-context";
    import type { AreaVariant } from "@/shared/lib/dither/chart-types";
    import { watchDeps } from "@/shared/lib/watchDeps";

    let { dataKey, variant = "gradient" }: { dataKey: string; variant?: AreaVariant } = $props();

    const ctx = usePolarPart("Radar", "radar");

    if (import.meta.env.DEV && !ctx.config[dataKey]) {
        console.warn(
            `<Radar dataKey="${dataKey}">: "${dataKey}" is not in the chart \`config\`. Add it so the series has a colour and label.`,
        );
    }

    const syncVariant = watchDeps(() => {
        ctx.registerVariant(dataKey, variant);
    });
    onDestroy(() => ctx.unregisterVariant(dataKey));
</script>

<span hidden use:syncVariant={[dataKey, variant]}></span>
