// site/src/lib/shared/ui/Button.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import { soundPlay } from "@/shared/lib/sound/singleton";
    import type { SoundRole } from "@/shared/lib/sound/types";

    let {
        variant = "ghost",
        size = "md",
        sound,
        volume,
        disabled,
        type = "button",
        onclick,
        class: className,
        children,
    }: {
        variant?: "primary" | "ghost" | "danger";
        size?: "sm" | "md" | "lg";
        sound?: SoundRole | false;
        volume?: number;
        disabled?: boolean;
        type?: "button" | "submit" | "reset";
        onclick?: (event: MouseEvent) => void;
        class?: string;
        children?: Snippet;
    } = $props();

    function handleClick(event: MouseEvent): void {
        if (sound !== false) soundPlay(sound ?? "interaction.tap", { volume });
        onclick?.(event);
    }
</script>

<button
    class={["kb-button", className]}
    {type}
    data-variant={variant}
    data-size={size === "md" ? undefined : size}
    {disabled}
    onclick={handleClick}
>
    {@render children?.()}
</button>

// site/src/components/ui/Button.tsx
import { Button as BaseButton } from '@base-ui/react/button';
import { soundPlay } from '../../lib/sound/singleton';
import type { SoundRole } from '../../lib/sound/types';

type ButtonVariant = 'primary' | 'ghost' | 'danger';
type ButtonSize = 'sm' | 'md' | 'lg';

interface ButtonProps extends Omit<React.ComponentProps<typeof BaseButton>, 'render'> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  sound?: SoundRole | false;
  volume?: number;
}

export default function Button({
  variant = 'ghost',
  size = 'md',
  sound,
  volume,
  className,
  onClick,
  ...rest
}: ButtonProps) {
  return (
    <BaseButton
      data-variant={variant}
      data-size={size === 'md' ? undefined : size}
      data-sound=""
      className={['kb-button', className].filter(Boolean).join(' ')}
      onClick={(e) => {
        if (sound !== false) soundPlay(sound ?? 'interaction.tap', { volume });
        onClick?.(e);
      }}
      {...rest}
    />
  );
}
