// site/src/lib/shared/ui/Skeleton.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import { styleToCss } from "@/shared/lib/dom";

    let {
        width,
        height,
        radius,
        circle = false,
        animate = true,
        visible = true,
        className,
        children,
    }: {
        width?: string;
        height?: string;
        radius?: number;
        circle?: boolean;
        animate?: boolean;
        visible?: boolean;
        className?: string;
        children?: Snippet;
    } = $props();

    const styleAttr = $derived(
        styleToCss({
            width,
            height,
            borderRadius: circle ? "50%" : radius !== undefined ? `${radius}px` : undefined,
        }),
    );
</script>

{#if visible}
    <div class={className ?? "kb-skeleton"}>
        <div data-animate={animate ? "" : undefined} style={styleAttr}></div>
        {@render children?.()}
    </div>
{:else}
    {@render children?.()}
{/if}

// site/src/components/ui/Skeleton.tsx
interface SkeletonProps {
  width?: string;
  height?: string;
  radius?: number;
  circle?: boolean;
  animate?: boolean;
  visible?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export default function Skeleton({
  width,
  height,
  radius,
  circle,
  animate = true,
  visible = true,
  className,
  children,
}: SkeletonProps) {
  if (!visible) return <>{children}</>;

  const style: React.CSSProperties = {
    width: width,
    height: height,
    borderRadius: circle ? '50%' : radius,
  };

  return (
    <div className={className ?? 'kb-skeleton'}>
      <div data-animate={animate ? '' : undefined} style={style} />
      {children}
    </div>
  );
}
