// site/src/shared/ui/Skeleton.vue
<script setup lang="ts">
import { computed } from "vue";

const props = withDefaults(
    defineProps<{
        width?: string;
        height?: string;
        radius?: number;
        circle?: boolean;
        animate?: boolean;
        visible?: boolean;
        className?: string;
    }>(),
    { animate: true, visible: true },
);

const style = computed(() => ({
    width: props.width,
    height: props.height,
    borderRadius: props.circle ? "50%" : props.radius !== undefined ? `${props.radius}px` : undefined,
}));
</script>

<template>
    <div v-if="visible" :class="className ?? 'kb-skeleton'">
        <div :data-animate="animate ? '' : undefined" :style="style" />
        <slot />
    </div>
    <slot v-else />
</template>

// site/src/components/ui/Skeleton.tsx
interface SkeletonProps {
  width?: string;
  height?: string;
  radius?: number;
  circle?: boolean;
  animate?: boolean;
  visible?: boolean;
  className?: string;
  children?: React.ReactNode;
}

export default function Skeleton({
  width,
  height,
  radius,
  circle,
  animate = true,
  visible = true,
  className,
  children,
}: SkeletonProps) {
  if (!visible) return <>{children}</>;

  const style: React.CSSProperties = {
    width: width,
    height: height,
    borderRadius: circle ? '50%' : radius,
  };

  return (
    <div className={className ?? 'kb-skeleton'}>
      <div data-animate={animate ? '' : undefined} style={style} />
      {children}
    </div>
  );
}
