// site/src/components/ProviderStatusGrid.tsx
import { useEffect, useMemo, useState } from "react";
import ProviderPopover from "./ProviderPopover";
import { TextField, Menu } from "./ui";
import { CheckmarkIcon } from "./ui/icons";
import { siteConfig } from "../config/site";
import { formatPercent } from "../utils/format";

type ProviderStatus = "up" | "degraded" | "down" | "unknown";

export type ProviderHealth = {
    error_rate_30m: number;
    error_rate_60m: number;
    errors_30m: number;
    errors_60m: number;
    last_error_at?: string | null;
    last_success_at?: string | null;
    model_count: number;
    prefix: string;
    requests_30m: number;
    requests_60m: number;
    status: ProviderStatus;
    successes_30m: number;
    successes_60m: number;
};

type HealthPayload = {
    providers?: ProviderHealth[];
};

const providerOrder = [
    "fth",
    "rev",
    "bbg",
    "glm",
    "opc",
    "cat",
    "yng",
    "bbl",
    "cwy",
    "woo",
    "img",
    "kai",
    "or",
    "vhr",
    "wsf",
];

const STATUS_OPTIONS: ProviderStatus[] = ["up", "degraded", "down"];
const STATUS_LABELS: Record<ProviderStatus, string> = {
    up: "Up",
    degraded: "Degraded",
    down: "Down",
    unknown: "Unknown",
};

function FilterCheckbox({ checked, onToggle, label, count }: {
    checked: boolean;
    onToggle: () => void;
    label: string;
    count?: number;
}) {
    return (
        <Menu.CheckboxItem
            className={`catalog-filter-menu-item${checked ? " is-active" : ""}`}
            checked={checked}
            onCheckedChange={() => onToggle()}
            data-sound="interaction.toggle"
        >
            <Menu.CheckboxItemIndicator className="catalog-filter-checkbox">
                <CheckmarkIcon />
            </Menu.CheckboxItemIndicator>
            <span className="catalog-filter-option-name">{label}</span>
            {count !== undefined && <span className="catalog-filter-option-count">{count}</span>}
        </Menu.CheckboxItem>
    );
}

function StatusFiltersToolbar(props: {
    query: string;
    setQuery: (v: string) => void;
    prefixFilters: Set<string>;
    togglePrefix: (p: string) => void;
    prefixCounts: [string, number][];
    statusFilter: Set<ProviderStatus>;
    toggleStatus: (s: ProviderStatus) => void;
    statusCounts: Record<ProviderStatus, number>;
    prefixButtonLabel: string;
    statusButtonLabel: string;
}) {
    return (
        <div className="catalog-toolbar">
            <div className="catalog-search-field">
                <span className="material-symbols-outlined catalog-search-icon">search</span>
                <TextField
                    className="catalog-search-input"
                    value={props.query}
                    placeholder="Search providers..."
                    onChange={(v: string) => props.setQuery(v)}
                />
            </div>
            <div className="catalog-filter-group" aria-label="Provider filters">
                <Menu.Root>
                    <Menu.Trigger className={`catalog-filter-trigger${props.prefixFilters.size > 0 ? " is-active" : ""}`} sound="overlay.expand">
                        <span className="catalog-filter-label">Prefix</span>
                        <span className="catalog-filter-value">{props.prefixButtonLabel}</span>
                        {props.prefixFilters.size > 0 && <span className="catalog-filter-count">{props.prefixFilters.size}</span>}
                    </Menu.Trigger>
                    <Menu.Content side="bottom" align="start" className="catalog-filter-content">
                        <Menu.Group>
                            {props.prefixCounts.map(([pfx, count]) => (
                                <FilterCheckbox
                                    key={pfx}
                                    checked={props.prefixFilters.has(pfx)}
                                    onToggle={() => props.togglePrefix(pfx)}
                                    label={`${pfx}/*`}
                                    count={count}
                                />
                            ))}
                        </Menu.Group>
                    </Menu.Content>
                </Menu.Root>
                <Menu.Root>
                    <Menu.Trigger className={`catalog-filter-trigger${props.statusFilter.size > 0 ? " is-active" : ""}`} sound="overlay.expand">
                        <span className="catalog-filter-label">Status</span>
                        <span className="catalog-filter-value">{props.statusButtonLabel}</span>
                        {props.statusFilter.size > 0 && <span className="catalog-filter-count">{props.statusFilter.size}</span>}
                    </Menu.Trigger>
                    <Menu.Content side="bottom" align="start" className="catalog-filter-content">
                        <Menu.Group>
                            {STATUS_OPTIONS.map((status) => (
                                <FilterCheckbox
                                    key={status}
                                    checked={props.statusFilter.has(status)}
                                    onToggle={() => props.toggleStatus(status)}
                                    label={STATUS_LABELS[status]}
                                    count={props.statusCounts[status]}
                                />
                            ))}
                        </Menu.Group>
                    </Menu.Content>
                </Menu.Root>
            </div>
        </div>
    );
}

function SkeletonCard() {
    return (
        <div className="status-grid">
            <article className="status-card is-unknown" aria-live="polite">
                <div className="status-card-top">
                    <strong>providers/</strong>
                    <span>loading</span>
                </div>
                <div className="status-card-main">
                    <span>...</span>
                    <small>models</small>
                </div>
                <div className="status-card-blast-slot" />
                <div className="status-card-meta">
                    <span>30m errors</span>
                    <strong>...</strong>
                    <span>requests</span>
                    <strong>...</strong>
                </div>
            </article>
        </div>
    );
}

function StatusCard({ provider, isSelected, onSelect, closePopover }: {
    provider: ProviderHealth;
    isSelected: boolean;
    onSelect: () => void;
    closePopover: () => void;
}) {
    const isAffected = provider.status === "degraded" || provider.status === "down";
    const modelCount = provider.model_count;
    const showBlast = isAffected && modelCount > 0;
    const handleClick = () => (isSelected ? closePopover() : onSelect());
    return (
        <article
            className={`status-card is-${provider.status}${isSelected ? " is-selected" : ""}`}
            tabIndex={0}
            role="button"
            aria-label={`${provider.prefix} provider status ${provider.status}`}
            data-sound="interaction.tap"
            onClick={handleClick}
            onKeyDown={(e) => {
                if (e.key === "Enter" || e.key === " ") { e.preventDefault(); handleClick(); }
            }}
        >
            <div className="status-card-top">
                <strong>{provider.prefix}/</strong>
                <span>{provider.status}</span>
            </div>
            <div className="status-card-main">
                <span>{modelCount.toLocaleString()}</span>
                <small>{modelCount === 1 ? "model" : "models"}</small>
            </div>
            <div className="status-card-blast-slot">
                {showBlast && (
                    <span className="status-card-blast">
                        {provider.status === "down" ? "Affected" : "At risk"}
                        {" "}<strong>{modelCount.toLocaleString()}</strong>
                        {" "}{modelCount === 1 ? "model" : "models"}
                    </span>
                )}
            </div>
            <div className="status-card-meta">
                <span>30m errors</span>
                <strong>{formatPercent(provider.error_rate_30m)}</strong>
                <span>requests</span>
                <strong>{provider.requests_30m.toLocaleString()}</strong>
            </div>
        </article>
    );
}

export default function ProviderStatusGrid() {
    const [health, setHealth] = useState<HealthPayload | null>(null);
    const [loadedAt, setLoadedAt] = useState<Date | null>(null);
    const [failed, setFailed] = useState(false);
    const [selectedPrefix, setSelectedPrefix] = useState<string | null>(null);
    const [query, setQuery] = useState("");
    const [prefixFilters, setPrefixFilters] = useState<Set<string>>(new Set());
    const [statusFilter, setStatusFilter] = useState<Set<ProviderStatus>>(new Set());

    const togglePrefix = (prefix: string) => {
        setPrefixFilters((prev) => {
            const next = new Set(prev);
            if (next.has(prefix)) next.delete(prefix);
            else next.add(prefix);
            return next;
        });
    };

    const toggleStatus = (status: ProviderStatus) => {
        setStatusFilter((prev) => {
            const next = new Set(prev);
            if (next.has(status)) next.delete(status);
            else next.add(status);
            return next;
        });
    };

    useEffect(() => {
        const fetchHealth = async () => {
            try {
                const response = await fetch(`${siteConfig.socials.api}/v1/health`, { cache: "no-store" });
                if (!response.ok) throw new Error(`health ${response.status}`);
                setHealth(await response.json());
                setLoadedAt(new Date());
                setFailed(false);
            } catch (error) {
                console.error("Failed to load provider health", error);
                setFailed(true);
            }
        };

        fetchHealth();
        const interval = window.setInterval(fetchHealth, 30000);
        return () => window.clearInterval(interval);
    }, []);

    const openPopover = (prefix: string) => {
        setSelectedPrefix(prefix);
    };

    const closePopover = () => {
        setSelectedPrefix(null);
    };

    const providers = useMemo(() => {
        const items = [...(health?.providers ?? [])];
        return items.sort((left, right) => {
            const leftIndex = providerOrder.indexOf(left.prefix);
            const rightIndex = providerOrder.indexOf(right.prefix);
            if (leftIndex !== -1 || rightIndex !== -1) {
                return (
                    (leftIndex === -1 ? 999 : leftIndex) -
                    (rightIndex === -1 ? 999 : rightIndex)
                );
            }
            return left.prefix.localeCompare(right.prefix);
        });
    }, [health]);

    const prefixCounts = useMemo(() => {
        const m = new Map<string, number>();
        for (const { prefix } of providers) m.set(prefix, (m.get(prefix) ?? 0) + 1);
        return [...m.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    }, [providers]);

    const statusCounts = useMemo(() => {
        const counts: Record<ProviderStatus, number> = { up: 0, degraded: 0, down: 0, unknown: 0 };
        for (const p of providers) counts[p.status]++;
        return counts;
    }, [providers]);

    const filteredProviders = useMemo(() => {
        let items = providers;
        const q = query.trim().toLowerCase();
        if (q) items = items.filter((p) => p.prefix.toLowerCase().includes(q));
        if (prefixFilters.size > 0) items = items.filter((p) => prefixFilters.has(p.prefix));
        if (statusFilter.size > 0) items = items.filter((p) => statusFilter.has(p.status));
        return items;
    }, [providers, query, prefixFilters, statusFilter]);

    const selectedProvider = useMemo(() => {
        if (!selectedPrefix) return null;
        return providers.find((p) => p.prefix === selectedPrefix) ?? null;
    }, [selectedPrefix, providers]);

    const prefixButtonLabel = () => {
        if (prefixFilters.size === 0) return "All prefixes";
        if (prefixFilters.size === 1) return `${[...prefixFilters][0]}/*`;
        return `${prefixFilters.size} prefixes`;
    };

    const statusButtonLabel = () => {
        if (statusFilter.size === 0) return "All statuses";
        if (statusFilter.size === 1) return STATUS_LABELS[[...statusFilter][0]];
        return `${statusFilter.size} statuses`;
    };

    const filtersActive = query.trim() !== "" || prefixFilters.size > 0 || statusFilter.size > 0;

    const resultLabel = () => {
        const count = filteredProviders.length;
        const plural = count === 1 ? "provider" : "providers";
        const prefixLabel = prefixFilters.size === 0
            ? "all prefixes"
            : prefixFilters.size === 1
            ? `${[...prefixFilters][0]}/*`
            : `${prefixFilters.size} prefixes`;
        return `${count.toLocaleString()} ${plural} across ${prefixLabel}`;
    };

    const clearFilters = () => {
        setQuery("");
        setPrefixFilters(new Set());
        setStatusFilter(new Set());
    };

    return (
        <div className="status-board">
            <div className="status-board-head">
                <div>
                    <h1>Status</h1>
                </div>
            </div>

            {failed && (
                <div className="status-alert">
                    Health data did not load. Retrying automatically.
                </div>
            )}

            {providers.length > 0 ? (
                <>
                    <StatusFiltersToolbar
                        query={query}
                        setQuery={setQuery}
                        prefixFilters={prefixFilters}
                        togglePrefix={togglePrefix}
                        prefixCounts={prefixCounts}
                        statusFilter={statusFilter}
                        toggleStatus={toggleStatus}
                        statusCounts={statusCounts}
                        prefixButtonLabel={prefixButtonLabel()}
                        statusButtonLabel={statusButtonLabel()}
                    />

                    <div className="catalog-summary" aria-live="polite">
                        <span>{resultLabel()}</span>
                        {filtersActive && (
                            <button type="button" onClick={clearFilters} data-sound="interaction.subtle">
                                Clear filters
                            </button>
                        )}
                    </div>

                    <div className="status-grid">
                        {filteredProviders.length > 0 ? (
                            filteredProviders.map((provider) => (
                                <StatusCard
                                    key={provider.prefix}
                                    provider={provider}
                                    isSelected={selectedPrefix === provider.prefix}
                                    onSelect={() => openPopover(provider.prefix)}
                                    closePopover={closePopover}
                                />
                            ))
                        ) : (
                            <div className="status-grid-empty">
                                No providers match your filters.
                                <button
                                    type="button"
                                    className="status-grid-empty-clear"
                                    data-sound="interaction.subtle"
                                    onClick={clearFilters}
                                >
                                    Clear filters
                                </button>
                            </div>
                        )}
                    </div>
                </>
            ) : (
                <SkeletonCard />
            )}

            {selectedProvider && (
                <ProviderPopover
                    provider={selectedProvider}
                    onClose={closePopover}
                />
            )}

            <div className="status-footnote">
                Updated{" "}
                {loadedAt
                    ? loadedAt.toLocaleTimeString([], {
                          hour: "2-digit",
                          minute: "2-digit",
                      })
                    : "..."}
                .
            </div>
        </div>
    );
}

// site/src/features/provider-status/ui/ProviderStatusGrid.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import type { HealthPayload, ProviderHealth, ProviderStatus } from "@/entities/provider";
import { PROVIDER_ORDER, STATUS_LABELS, STATUS_OPTIONS } from "@/entities/provider";
import { siteConfig } from "@/shared/config/site";
import { DropdownMenu, TextField } from "@/shared/ui";
import type { DropdownMenuOption } from "@/shared/ui";
import StatusCard from "./StatusCard.vue";
import ProviderPopover from "./ProviderPopover.vue";

const health = ref<HealthPayload | null>(null);
const loadedAt = ref<Date | null>(null);
const failed = ref(false);
const selectedPrefix = ref<string | null>(null);
const query = ref("");
const prefixFilters = ref<Set<string>>(new Set());
const statusFilter = ref<Set<ProviderStatus>>(new Set());
let interval: number | undefined;

function togglePrefix(prefix: string): void {
    const next = new Set(prefixFilters.value);
    if (next.has(prefix)) next.delete(prefix);
    else next.add(prefix);
    prefixFilters.value = next;
}

function toggleStatus(status: string): void {
    const key = status as ProviderStatus;
    const next = new Set(statusFilter.value);
    if (next.has(key)) next.delete(key);
    else next.add(key);
    statusFilter.value = next;
}

async function fetchHealth(): Promise<void> {
    try {
        const response = await fetch(`${siteConfig.socials.api}/v1/health`, { cache: "no-store" });
        if (!response.ok) throw new Error(`health ${response.status}`);
        health.value = await response.json();
        loadedAt.value = new Date();
        failed.value = false;
    } catch (error) {
        console.error("Failed to load provider health", error);
        failed.value = true;
    }
}

onMounted(() => {
    fetchHealth();
    interval = window.setInterval(fetchHealth, 30000);
});
onBeforeUnmount(() => {
    if (interval) window.clearInterval(interval);
});

function openPopover(prefix: string): void {
    selectedPrefix.value = prefix;
}
function closePopover(): void {
    selectedPrefix.value = null;
}

const providers = computed(() => {
    const items = [...(health.value?.providers ?? [])];
    return items.sort((left, right) => {
        const leftIndex = PROVIDER_ORDER.indexOf(left.prefix);
        const rightIndex = PROVIDER_ORDER.indexOf(right.prefix);
        if (leftIndex !== -1 || rightIndex !== -1) {
            return (leftIndex === -1 ? 999 : leftIndex) - (rightIndex === -1 ? 999 : rightIndex);
        }
        return left.prefix.localeCompare(right.prefix);
    });
});

const prefixCounts = computed<[string, number][]>(() => {
    const m = new Map<string, number>();
    for (const { prefix } of providers.value) m.set(prefix, (m.get(prefix) ?? 0) + 1);
    return [...m.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
});

const statusCounts = computed(() => {
    const counts: Record<ProviderStatus, number> = { up: 0, degraded: 0, down: 0, unknown: 0 };
    for (const p of providers.value) counts[p.status]++;
    return counts;
});

const filteredProviders = computed(() => {
    let items = providers.value;
    const q = query.value.trim().toLowerCase();
    if (q) items = items.filter((p) => p.prefix.toLowerCase().includes(q));
    if (prefixFilters.value.size > 0) items = items.filter((p) => prefixFilters.value.has(p.prefix));
    if (statusFilter.value.size > 0) items = items.filter((p) => statusFilter.value.has(p.status));
    return items;
});

const selectedProvider = computed<ProviderHealth | null>(() => {
    if (!selectedPrefix.value) return null;
    return providers.value.find((p) => p.prefix === selectedPrefix.value) ?? null;
});

const prefixButtonLabel = computed(() => {
    if (prefixFilters.value.size === 0) return "All prefixes";
    if (prefixFilters.value.size === 1) return `${[...prefixFilters.value][0]}/*`;
    return `${prefixFilters.value.size} prefixes`;
});

const statusButtonLabel = computed(() => {
    if (statusFilter.value.size === 0) return "All statuses";
    if (statusFilter.value.size === 1) return STATUS_LABELS[[...statusFilter.value][0]];
    return `${statusFilter.value.size} statuses`;
});

const total = computed(() => providers.value.length);
const healthy = computed(() => providers.value.filter((p) => p.status === "up").length);
const degraded = computed(() => providers.value.filter((p) => p.status === "degraded").length);
const down = computed(() => providers.value.filter((p) => p.status === "down").length);
const affected = computed(() => degraded.value + down.value);

const overallState = computed(() => (affected.value === 0 ? "healthy" : down.value > 0 ? "down" : "degraded"));
const stateText = computed(() =>
    affected.value === 0
        ? "All providers operational"
        : down.value > 0
          ? `${down.value.toLocaleString()} provider${down.value === 1 ? "" : "s"} down`
          : `${degraded.value.toLocaleString()} provider${degraded.value === 1 ? "" : "s"} degraded`,
);

const filtersActive = computed(() => query.value.trim() !== "" || prefixFilters.value.size > 0 || statusFilter.value.size > 0);

const resultLabel = computed(() => {
    const count = filteredProviders.value.length;
    return `${count.toLocaleString()} ${count === 1 ? "provider" : "providers"}`;
});

function clearFilters(): void {
    query.value = "";
    prefixFilters.value = new Set();
    statusFilter.value = new Set();
}

const prefixMenuOptions = computed<DropdownMenuOption[]>(() =>
    prefixCounts.value.map(([pfx, count]) => ({ value: pfx, label: `${pfx}/*`, count, checked: prefixFilters.value.has(pfx) })),
);

const statusMenuOptions = computed<DropdownMenuOption[]>(() =>
    STATUS_OPTIONS.map((status) => ({ value: status, label: STATUS_LABELS[status], count: statusCounts.value[status], checked: statusFilter.value.has(status) })),
);
</script>

<template>
    <div class="status-board">
        <div v-if="failed" class="status-alert">Health data did not load. Retrying automatically.</div>

        <template v-if="providers.length > 0">
            <div class="status-bar">
                <span :class="`status-bar-state is-${overallState}`">{{ stateText }}</span>
                <div class="status-bar-counts">
                    <span class="is-healthy-count"><strong>{{ healthy }}</strong> healthy</span>
                    <span class="is-degraded-count"><strong>{{ degraded }}</strong> degraded</span>
                    <span class="is-down-count"><strong>{{ down }}</strong> down</span>
                    <span><strong>{{ total }}</strong> total</span>
                </div>
            </div>

            <div class="catalog-toolbar">
                <div class="catalog-search-field">
                    <span class="material-symbols-outlined catalog-search-icon">search</span>
                    <TextField class="catalog-search-input" :model-value="query" placeholder="Search providers..." @update:model-value="(v) => (query = v)" />
                </div>
                <div class="catalog-filter-group" aria-label="Provider filters">
                    <DropdownMenu
                        trigger-label="Prefix"
                        :value-label="prefixButtonLabel"
                        :active-count="prefixFilters.size"
                        :options="prefixMenuOptions"
                        @toggle="togglePrefix"
                    />
                    <DropdownMenu
                        trigger-label="Status"
                        :value-label="statusButtonLabel"
                        :active-count="statusFilter.size"
                        :options="statusMenuOptions"
                        @toggle="toggleStatus"
                    />
                </div>
            </div>

            <div class="catalog-summary" aria-live="polite">
                <span>{{ resultLabel }}</span>
                <button v-if="filtersActive" type="button" data-sound="interaction.subtle" @click="clearFilters">Clear filters</button>
            </div>

            <div class="status-grid">
                <template v-if="filteredProviders.length > 0">
                    <StatusCard
                        v-for="provider in filteredProviders"
                        :key="provider.prefix"
                        :provider="provider"
                        :is-selected="selectedPrefix === provider.prefix"
                        @select="openPopover(provider.prefix)"
                        @close="closePopover"
                    />
                </template>
                <div v-else class="status-grid-empty">
                    No providers match your filters.
                    <button type="button" class="status-grid-empty-clear" data-sound="interaction.subtle" @click="clearFilters">Clear filters</button>
                </div>
            </div>
        </template>

        <div v-else class="status-grid">
            <article class="status-card is-unknown" aria-live="polite">
                <div class="status-card-top">
                    <strong>providers/</strong>
                    <span>loading</span>
                </div>
                <div class="status-card-main">
                    <span>...</span>
                    <small>models</small>
                </div>
                <div class="status-card-blast-slot" />
                <div class="status-card-meta">
                    <span>30m errors</span>
                    <strong>...</strong>
                    <span>requests</span>
                    <strong>...</strong>
                </div>
            </article>
        </div>

        <ProviderPopover v-if="selectedProvider" :provider="selectedProvider" @close="closePopover" />

        <div class="status-footnote">
            Updated {{ loadedAt ? loadedAt.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "..." }}.
        </div>
    </div>
</template>
