// site/src/components/PaidPlanExplorer.tsx
import { createEffect, createMemo, createSignal, For, onMount, Show } from "solid-js";
import PaidModelTable from "./PaidModelTable";
import { siteModelContextWindow } from "../utils/format";

interface PaidLimit {
  limit?: number;
  unit?: string;
}

interface PaidPrice {
  amount?: number;
  amount_milli?: number;
  currency?: string;
  period?: string;
}

interface PaidPlan {
  id: string;
  display_name: string;
  description?: string;
  highlights?: string[];
  limits?: Record<string, PaidLimit>;
  model_count?: number;
  concurrency_limit?: number;
  providers?: string[];
  models?: string[];
  billing_period?: string;
  price?: string | PaidPrice;
  price_usd?: number;
  price_usd_milli?: number;
  purchasable?: boolean;
}

interface PaidModel {
  id: string;
  name?: string;
  unit_cost: number;
  unit_label: string;
  route: string;
  plans?: string[];
  context_window?: number;
  max_input_tokens?: number;
  max_output_tokens?: number;
  supports_images?: boolean;
  supports_streaming?: boolean;
  supports_tool_call?: boolean;
  supports_response_schema?: boolean;
}

interface PaidModelGroup {
  id: string;
  label: string;
  description: string;
  models: PaidModel[];
}

interface PaidPlanSnapshot {
  updated_at?: string;
  plan?: {
    price?: string;
    period?: string;
    summary?: string;
  };
  plans?: PaidPlan[];
  model_groups?: PaidModelGroup[];
}

interface CatalogState {
  plans: PaidPlan[];
  groups: PaidModelGroup[];
}

interface PaidPlanExplorerProps {
  snapshot: PaidPlanSnapshot;
  discordUrl: string;
}

const CATALOG_ENDPOINT = "https://paid.freetheai.xyz/v1/models/full";
const PLANS_ENDPOINT = "https://paid.freetheai.xyz/v1/plans";
const SITE_KEY = "freetheai.xyz";

const PLAN_COPY: Record<string, { tag: string; bestFor: string; accent: string }> = {
  coding: {
    tag: "Full catalog",
    bestFor: "IDE agents, CLI tools, long coding runs, and general assistant work.",
    accent: "Full model spread, more concurrency, higher request-unit limits.",
  },
  roleplay: {
    tag: "Curated chat",
    bestFor: "Roleplay clients, story chats, companion bots, and lighter chat usage.",
    accent: "Smaller model set, simpler routing, built around chat-first usage.",
  },
};

const PLAN_PRICE_FALLBACKS: Record<string, string> = {
  coding: "$8",
  roleplay: "$5",
};

const PLAN_ORDER = ["roleplay", "coding"];
const LIMIT_ORDER = ["five_hour", "hourly", "daily", "weekly", "monthly"];
const LIMIT_LABELS: Record<string, string> = {
  five_hour: "5-hour units",
  hourly: "hourly units",
  daily: "daily units",
  weekly: "weekly units",
  monthly: "monthly units",
};

const str = (value: unknown): string | undefined =>
  typeof value === "string" && value.trim() ? value.trim() : undefined;

const num = (value: unknown): number | undefined =>
  typeof value === "number" && Number.isFinite(value) ? value : undefined;

const formatNumber = (value: number): string => value.toLocaleString();

const formatUnitCost = (value: number): string =>
  Number.isInteger(value) ? String(value) : String(value);

const formatUSD = (value: number): string =>
  `$${Number.isInteger(value) ? value.toLocaleString() : value.toLocaleString(undefined, { maximumFractionDigits: 2 })}`;

const formatPlanPrice = (plan: PaidPlan): string => {
  const milli = num(plan.price_usd_milli);
  if (milli !== undefined) return formatUSD(milli / 1000);
  const usd = num(plan.price_usd);
  if (usd !== undefined) return formatUSD(usd);
  if (typeof plan.price === "string" && plan.price.trim()) return plan.price.trim();
  if (typeof plan.price === "object" && plan.price !== null) {
    const amount = num(plan.price.amount);
    const amountMilli = num(plan.price.amount_milli);
    if (amount !== undefined) return formatUSD(amount);
    if (amountMilli !== undefined) return formatUSD(amountMilli / 1000);
  }
  return PLAN_PRICE_FALLBACKS[plan.id] ?? "Paid";
};

const planPeriod = (plan: PaidPlan, fallback?: string): string | undefined => {
  if (plan.billing_period) return plan.billing_period;
  if (typeof plan.price === "object" && plan.price !== null && plan.price.period) return plan.price.period;
  return fallback;
};

const modelPrefix = (id: string): string => id.includes("/") ? id.slice(0, id.indexOf("/")) : "other";

const routeForModel = (id: string): string => {
  const lower = id.toLowerCase();
  if (lower.includes("embedding")) return "embeddings";
  if (lower.includes("rerank")) return "rerank";
  return "chat";
};

const limitEntries = (plan: PaidPlan) =>
  LIMIT_ORDER
    .map((key) => ({ key, value: plan.limits?.[key] }))
    .filter((entry): entry is { key: string; value: PaidLimit } =>
      typeof entry.value?.limit === "number" && Number.isFinite(entry.value.limit),
    );

const normalizePlan = (raw: any): PaidPlan | null => {
  const id = str(raw?.id);
  if (!id) return null;
  if (raw?.display === false || raw?.visible === false || raw?.purchasable === false) return null;
  const rawPrice = raw?.price;
  const price = typeof rawPrice === "string" || (rawPrice && typeof rawPrice === "object") ? rawPrice : undefined;
  return {
    id,
    display_name: str(raw?.display_name) ?? id,
    description: str(raw?.description),
    highlights: Array.isArray(raw?.highlights) ? raw.highlights.filter((item: unknown): item is string => typeof item === "string") : [],
    limits: raw?.limits && typeof raw.limits === "object" ? raw.limits : {},
    model_count: num(raw?.model_count),
    concurrency_limit: num(raw?.concurrency_limit),
    providers: Array.isArray(raw?.providers) ? raw.providers.filter((item: unknown): item is string => typeof item === "string") : [],
    models: Array.isArray(raw?.models) ? raw.models.filter((item: unknown): item is string => typeof item === "string") : [],
    billing_period: str(raw?.billing_period) ?? str(raw?.period) ?? str(raw?.price?.period),
    price,
    price_usd: num(raw?.price_usd),
    price_usd_milli: num(raw?.price_usd_milli),
    purchasable: raw?.purchasable !== false,
  };
};

const normalizeModel = (raw: any): PaidModel | null => {
  const id = str(raw?.id);
  if (!id) return null;
  const unit = num(raw?.pricing_units) ?? num(raw?.pricing?.unit_cost) ?? num(raw?.unit_cost) ?? 1;
  const display = str(raw?.pricing?.display) ?? str(raw?.unit_label) ?? `${formatUnitCost(unit)} request units`;
  const model = {
    id,
    name: str(raw?.name),
    unit_cost: unit,
    unit_label: display,
    route: str(raw?.route) ?? routeForModel(id),
    plans: Array.isArray(raw?.plans) ? raw.plans.filter((item: unknown): item is string => typeof item === "string") : [],
    context_window: num(raw?.context_window),
    max_input_tokens: num(raw?.max_input_tokens),
    max_output_tokens: num(raw?.max_output_tokens),
    supports_images: raw?.supports_images === true,
    supports_streaming: raw?.supports_streaming === true,
    supports_tool_call: raw?.supports_tool_call === true,
    supports_response_schema: raw?.supports_response_schema === true,
  };
  const context = siteModelContextWindow(model);
  if (context > 0) {
    model.context_window = context;
    model.max_input_tokens = context;
  }
  return model;
};

const groupModels = (models: PaidModel[]): PaidModelGroup[] => {
  const byPrefix = new Map<string, PaidModel[]>();
  for (const model of models) {
    const prefix = modelPrefix(model.id);
    const list = byPrefix.get(prefix) ?? [];
    list.push(model);
    byPrefix.set(prefix, list);
  }
  return [...byPrefix.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([id, list]) => ({
      id,
      label: `${id.toUpperCase()} models`,
      description: "paid model pool",
      models: list.sort((a, b) => a.unit_cost - b.unit_cost || a.id.localeCompare(b.id)),
    }));
};

const snapshotState = (snapshot: PaidPlanSnapshot): CatalogState => ({
  plans: (snapshot.plans ?? []).map(normalizePlan).filter((plan): plan is PaidPlan => plan !== null),
  groups: snapshot.model_groups ?? [],
});

const fetchLiveCatalog = async (): Promise<CatalogState> => {
  const headers = { Accept: "application/json", Authorization: `Bearer ${SITE_KEY}` };
  const [modelsRes, plansRes] = await Promise.all([
    fetch(CATALOG_ENDPOINT, { headers }),
    fetch(PLANS_ENDPOINT, { headers }),
  ]);
  if (!modelsRes.ok) throw new Error(`Paid catalog status ${modelsRes.status}`);
  if (!plansRes.ok) throw new Error(`Paid plans status ${plansRes.status}`);
  const [modelsPayload, plansPayload] = await Promise.all([modelsRes.json(), plansRes.json()]);
  const plans = (plansPayload?.data ?? modelsPayload?.plans ?? [])
    .map(normalizePlan)
    .filter((plan: PaidPlan | null): plan is PaidPlan => plan !== null);
  const groups = groupModels(
    (modelsPayload?.data ?? [])
      .map(normalizeModel)
      .filter((model: PaidModel | null): model is PaidModel => model !== null),
  );
  return {
    plans,
    groups,
  };
};

function PlanCard(props: {
  plan: PaidPlan;
  active: boolean;
  period?: string;
  onSelect: () => void;
}) {
  const copy = PLAN_COPY[props.plan.id] ?? {
    tag: "Paid plan",
    bestFor: props.plan.description ?? "Paid API access.",
    accent: "Request-unit pricing with a dedicated paid model catalog.",
  };
  return (
    <article class={`paid-plan-option${props.active ? " is-active" : ""}`}>
      <div class="paid-plan-option-top">
        <span class="pricing-route-pill">{copy.tag}</span>
        <span class="paid-plan-option-price">
          {formatPlanPrice(props.plan)}
          <small>{planPeriod(props.plan, props.period) ? ` / ${planPeriod(props.plan, props.period)}` : ""}</small>
        </span>
      </div>
      <h3>{props.plan.display_name}</h3>
      <p>{copy.bestFor}</p>
      <div class="paid-plan-stat-grid">
        <span>
          <strong>{formatNumber(props.plan.model_count ?? props.plan.models?.length ?? 0)}</strong>
          models
        </span>
        <span>
          <strong>{props.plan.concurrency_limit ?? "-"}</strong>
          concurrent
        </span>
      </div>
      <div class="paid-plan-limit-strip">
        <For each={limitEntries(props.plan).slice(0, 3)}>
          {(entry) => (
            <span>
              <strong>{formatNumber(entry.value.limit ?? 0)}</strong>
              {LIMIT_LABELS[entry.key] ?? entry.key}
            </span>
          )}
        </For>
      </div>
      <p class="paid-plan-option-note">{copy.accent}</p>
      <button
        type="button"
        class="paid-plan-select"
        onClick={props.onSelect}
        data-sound="interaction.tap"
      >
        {props.active ? "Selected" : `Compare ${props.plan.display_name}`}
      </button>
    </article>
  );
}

export default function PaidPlanExplorer(props: PaidPlanExplorerProps) {
  const initialCatalog = snapshotState(props.snapshot);
  const [catalog, setCatalog] = createSignal<CatalogState>(initialCatalog);
  const [selectedPlan, setSelectedPlan] = createSignal(initialCatalog.plans[0]?.id ?? PLAN_ORDER[0]);

  onMount(() => {
    fetchLiveCatalog()
      .then((next) => {
        setCatalog(next);
      })
      .catch((error) => {
        if (import.meta.env.DEV) console.warn("Paid catalog refresh failed.", error);
      });
  });

  const plans = createMemo(() =>
    [...catalog().plans].sort((a, b) => {
      const ai = PLAN_ORDER.indexOf(a.id);
      const bi = PLAN_ORDER.indexOf(b.id);
      return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi) || a.display_name.localeCompare(b.display_name);
    }),
  );

  createEffect(() => {
    const ids = new Set(plans().map((plan) => plan.id));
    if (!ids.has(selectedPlan()) && plans().length > 0) setSelectedPlan(plans()[0].id);
  });

  const selected = createMemo(() => plans().find((plan) => plan.id === selectedPlan()) ?? plans()[0]);
  const selectedModelIds = createMemo(() => new Set(selected()?.models ?? []));
  const selectedModelCount = createMemo(() =>
    catalog().groups.reduce((total, group) =>
      total + group.models.filter((model) => (model.plans ?? []).includes(selectedPlan()) || selectedModelIds().has(model.id)).length,
      0,
    ),
  );
  const selectedMinCost = createMemo(() => {
    const costs = catalog().groups.flatMap((group) =>
      group.models
        .filter((model) => (model.plans ?? []).includes(selectedPlan()) || selectedModelIds().has(model.id))
        .map((model) => model.unit_cost),
    );
    return costs.length ? Math.min(...costs) : 0;
  });

  return (
    <div class="paid-plan-explorer">
      <section class="paid-plan-chooser shell" aria-labelledby="paid-plan-title">
        <div class="paid-plan-chooser-copy">
          <span class="eyebrow">Paid plans</span>
          <h2 id="paid-plan-title">Pick the lane that matches how you use the API.</h2>
          <Show
            when={plans().length > 1}
            fallback={<p>{selected()?.description ?? "Available paid plans use request units and refresh from the live paid API catalog."}</p>}
          >
            <p>
              Available plans use request units. Pick the lane that matches your client, context size,
              and usage pattern.
            </p>
          </Show>
        </div>

        <div class={`paid-plan-options${plans().length === 1 ? " is-single" : ""}`}>
          <For each={plans()}>
            {(plan) => (
              <PlanCard
                plan={plan}
                active={selectedPlan() === plan.id}
                period={props.snapshot.plan?.period}
                onSelect={() => setSelectedPlan(plan.id)}
              />
            )}
          </For>
        </div>
      </section>

      <section class="section shell pricing-section paid-selected-section">
        <div class="paid-selected-summary">
          <div>
            <span class="eyebrow">Selected plan</span>
            <h2>{selected()?.display_name ?? "Paid plan"}</h2>
            <p>{selected()?.description}</p>
          </div>
          <div class="paid-selected-metrics">
            <span>
              <strong>{formatNumber(selectedModelCount())}</strong>
              aliases
            </span>
            <span>
              <strong>{selectedMinCost() ? formatUnitCost(selectedMinCost()) : "-"}</strong>
              starting units
            </span>
            <span>
              <strong>{selected()?.concurrency_limit ?? "-"}</strong>
              concurrent
            </span>
          </div>
          <a class="primary-button pricing-plan-cta" href={props.discordUrl} target="_blank" rel="noreferrer">
            <span>Get a paid key</span>
            <span class="cta-arrow" aria-hidden="true">&rarr;</span>
          </a>
        </div>

        <PaidModelTable groups={catalog().groups} activePlan={selectedPlan()} />
      </section>
    </div>
  );
}

// site/src/features/paid-plan-explorer/ui/PaidPlanExplorer.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import type { CatalogState, PaidPlanSnapshot } from "@/entities/paid-plan";
import { PLAN_ORDER, fetchLiveCatalog, formatNumber, formatUnitCost, snapshotState } from "@/entities/paid-plan";
import PlanCard from "./PlanCard.vue";
import PaidModelTable from "./PaidModelTable.vue";

const props = defineProps<{ snapshot: PaidPlanSnapshot; discordUrl: string }>();

const initialCatalog = snapshotState(props.snapshot);
const catalog = ref<CatalogState>(initialCatalog);
const selectedPlan = ref(initialCatalog.plans[0]?.id ?? PLAN_ORDER[0]);

onMounted(async () => {
    try {
        catalog.value = await fetchLiveCatalog();
    } catch (error) {
        if (import.meta.env.DEV) console.warn("Paid catalog refresh failed.", error);
    }
});

const plans = computed(() =>
    [...catalog.value.plans].sort((a, b) => {
        const ai = PLAN_ORDER.indexOf(a.id);
        const bi = PLAN_ORDER.indexOf(b.id);
        return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi) || a.display_name.localeCompare(b.display_name);
    }),
);

const selected = computed(() => plans.value.find((plan) => plan.id === selectedPlan.value) ?? plans.value[0]);
const selectedModelIds = computed(() => new Set(selected.value?.models ?? []));

const selectedModelCount = computed(() =>
    catalog.value.groups.reduce(
        (total, group) => total + group.models.filter((model) => (model.plans ?? []).includes(selectedPlan.value) || selectedModelIds.value.has(model.id)).length,
        0,
    ),
);

const selectedMinCost = computed(() => {
    const costs = catalog.value.groups.flatMap((group) =>
        group.models.filter((model) => (model.plans ?? []).includes(selectedPlan.value) || selectedModelIds.value.has(model.id)).map((model) => model.unit_cost),
    );
    return costs.length ? Math.min(...costs) : 0;
});
</script>

<template>
    <div class="paid-plan-explorer">
        <section class="paid-plan-chooser shell" aria-labelledby="paid-plan-title">
            <div class="paid-plan-chooser-copy">
                <span class="eyebrow">Paid plans</span>
                <h2 id="paid-plan-title">Pick the lane that matches how you use the API.</h2>
                <p v-if="plans.length > 1">
                    Available plans use request units. Pick the lane that matches your client, context size, and usage pattern.
                </p>
                <p v-else>{{ selected?.description ?? "Available paid plans use request units and refresh from the live paid API catalog." }}</p>
            </div>

            <div :class="['paid-plan-options', { 'is-single': plans.length === 1 }]">
                <PlanCard
                    v-for="plan in plans"
                    :key="plan.id"
                    :plan="plan"
                    :active="selectedPlan === plan.id"
                    :period="props.snapshot.plan?.period"
                    @select="selectedPlan = plan.id"
                />
            </div>
        </section>

        <section class="section shell pricing-section paid-selected-section">
            <div class="paid-selected-summary">
                <div>
                    <span class="eyebrow">Selected plan</span>
                    <h2>{{ selected?.display_name ?? "Paid plan" }}</h2>
                </div>
                <div class="paid-selected-metrics">
                    <span>
                        <strong>{{ formatNumber(selectedModelCount) }}</strong>
                        aliases
                    </span>
                    <span>
                        <strong>{{ selectedMinCost ? formatUnitCost(selectedMinCost) : "-" }}</strong>
                        starting units
                    </span>
                    <span>
                        <strong>{{ selected?.concurrency_limit ?? "-" }}</strong>
                        concurrent
                    </span>
                </div>
                <a class="primary-button pricing-plan-cta" :href="discordUrl" target="_blank" rel="noreferrer">
                    <span>Get a paid key</span>
                    <span class="cta-arrow" aria-hidden="true">&rarr;</span>
                </a>
            </div>

            <PaidModelTable :groups="catalog.groups" :active-plan="selectedPlan" />
        </section>
    </div>
</template>

<style>
/* Unscoped: styles cover this feature's own markup plus its PlanCard and
   PaidModelTable children, ported verbatim from the former pricing.astro
   global style block. */
.pricing-note {
    max-width: 56ch;
    margin: 0;
    color: var(--dim);
    font-size: 0.96rem;
    line-height: 1.55;
    text-wrap: pretty;
}

.pricing-plan-cta {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    width: fit-content;
}

.pricing-plan-cta .cta-arrow {
    opacity: 0.65;
    font-size: 0.9rem;
}

.pricing-section {
    gap: clamp(22px, 3vw, 30px);
    padding: clamp(24px, 4vw, 38px);
}

.paid-plan-explorer {
    display: grid;
    gap: 28px;
}

.paid-plan-chooser {
    position: relative;
    overflow: hidden;
    display: grid;
    grid-template-columns: minmax(250px, 0.8fr) minmax(0, 1.2fr);
    gap: clamp(20px, 3vw, 34px);
    padding: clamp(22px, 4vw, 38px);
}

.paid-plan-chooser::before {
    content: "";
    position: absolute;
    inset: -120px auto auto 18%;
    width: 420px;
    height: 420px;
    border-radius: 50%;
    background:
        radial-gradient(circle, oklch(0.659 0.192 40.1 / 0.2), transparent 62%),
        radial-gradient(circle at 70% 65%, oklch(0.827 0.113 55.9 / 0.12), transparent 48%);
    pointer-events: none;
}

.paid-plan-chooser-copy,
.paid-plan-options {
    position: relative;
    z-index: 1;
}

.paid-plan-chooser-copy {
    display: grid;
    align-content: start;
    gap: 14px;
}

.paid-plan-chooser-copy h2,
.paid-selected-summary h2 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: clamp(2rem, 4vw, 3.1rem);
    line-height: 1;
    letter-spacing: -0.045em;
}

.paid-plan-chooser-copy p,
.paid-selected-summary p {
    margin: 0;
    color: var(--muted);
    line-height: 1.65;
}

.paid-plan-options {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 14px;
}

.paid-plan-options.is-single {
    grid-template-columns: minmax(0, min(100%, 520px));
    justify-content: center;
}

.paid-plan-option {
    position: relative;
    display: grid;
    gap: 14px;
    min-width: 0;
    padding: clamp(16px, 2.4vw, 22px);
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: oklch(0.145 0 90.1 / 0.42);
    box-shadow: var(--sk-inset-shadow);
    transition:
        border-color 180ms var(--ease-out-smooth),
        box-shadow 180ms var(--ease-out-smooth),
        transform 180ms var(--ease-out-smooth);
}

.paid-plan-option.is-active {
    border-color: oklch(0.659 0.192 40.1 / 0.72);
    box-shadow:
        var(--sk-raised-shadow),
        0 0 0 1px oklch(0.659 0.192 40.1 / 0.18),
        0 20px 50px oklch(0.659 0.192 40.1 / 0.08);
    transform: translateY(-2px);
}

.paid-plan-badge {
    position: absolute;
    top: -10px;
    right: 14px;
    padding: 4px 10px;
    border: 1px solid var(--accent);
    border-radius: var(--radius-sm);
    background: var(--accent);
    color: var(--accent-text-strong);
    font-family: var(--font-mono);
    font-size: 0.65rem;
    font-weight: 700;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    text-shadow: var(--accent-text-glow);
}

.paid-plan-option-top,
.paid-selected-summary {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 14px;
}

.paid-plan-option-price {
    color: var(--accent-text-strong);
    font-family: var(--font-serif);
    font-size: 1.45rem;
    line-height: 1;
    letter-spacing: -0.05em;
    text-shadow: var(--accent-text-glow);
    white-space: nowrap;
}

.paid-plan-option-price small {
    color: var(--muted);
    font-family: var(--font-mono);
    font-size: 0.62rem;
    letter-spacing: 0.04em;
    text-transform: uppercase;
}

.paid-plan-option h3 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: clamp(1.45rem, 2.4vw, 2rem);
    line-height: 1;
    letter-spacing: -0.035em;
}

.paid-plan-option p {
    margin: 0;
    color: var(--muted);
    font-size: 0.9rem;
    line-height: 1.55;
    text-wrap: pretty;
}

.paid-plan-stat-grid,
.paid-selected-metrics {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 8px;
}

.paid-plan-stat-grid span,
.paid-plan-limit-strip span,
.paid-selected-metrics span {
    display: grid;
    gap: 3px;
    min-width: 0;
    padding: 10px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-inset-bg);
    color: var(--dim);
    font-family: var(--font-mono);
    font-size: 0.68rem;
    line-height: 1.2;
    text-transform: uppercase;
}

.paid-plan-stat-grid strong,
.paid-plan-limit-strip strong,
.paid-selected-metrics strong {
    color: var(--accent-text);
    font-size: 0.92rem;
    text-shadow: var(--accent-text-glow);
}

.paid-plan-limit-strip {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 8px;
}

.paid-plan-option-note {
    padding-top: 2px;
}

.paid-plan-select {
    width: 100%;
    min-height: 42px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-shell-bg);
    color: var(--text);
    box-shadow: var(--sk-raised-shadow);
    font-family: var(--font-mono);
    font-size: 0.76rem;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    cursor: pointer;
    transition:
        border-color 150ms var(--ease-out-smooth),
        background 150ms var(--ease-out-smooth),
        color 150ms var(--ease-out-smooth),
        text-shadow 150ms var(--ease-out-smooth),
        transform var(--press-dur) var(--ease-out-smooth);
}

.paid-plan-select:active {
    transform: scale(var(--press-scale));
}

.paid-plan-option.is-active .paid-plan-select {
    border-color: var(--accent);
    background: var(--accent);
    color: var(--accent-text-strong);
    text-shadow: var(--accent-text-glow);
}

.paid-selected-section {
    position: relative;
}

.paid-selected-summary {
    flex-wrap: wrap;
    padding-bottom: 2px;
}

.paid-selected-summary > div:first-child {
    display: grid;
    gap: 9px;
    max-width: 560px;
}

.paid-selected-metrics {
    grid-template-columns: repeat(3, minmax(110px, 1fr));
    min-width: min(100%, 430px);
}

.paid-table-panel {
    display: grid;
    gap: 16px;
    min-width: 0;
}

.paid-model-table {
    display: grid;
    gap: 6px;
    max-width: 100%;
    min-width: 0;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    padding-bottom: 2px;
}

.paid-model-table::-webkit-scrollbar {
    height: 6px;
}

.paid-model-table::-webkit-scrollbar-thumb {
    border-radius: 3px;
    background: var(--sk-border);
}

.paid-model-row {
    display: grid;
    grid-template-columns: minmax(260px, 1fr) 82px 98px 132px 136px 42px;
    gap: 12px;
    align-items: center;
    min-width: 900px;
    padding: 10px 12px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
}

.paid-model-row-head {
    padding: 2px 12px 6px;
    border: 0;
    background: transparent;
    box-shadow: none;
    color: var(--dim);
    font-family: var(--font-mono);
    font-size: 0.68rem;
    letter-spacing: 0.08em;
    text-transform: uppercase;
}

.paid-model-name {
    min-width: 0;
    display: grid;
    gap: 6px;
}

.paid-model-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
}

.paid-model-row code {
    min-width: 0;
    overflow: hidden;
    color: var(--text);
    font-family: var(--font-mono);
    font-size: 0.78rem;
    text-overflow: ellipsis;
    white-space: nowrap;
}

.pricing-route-pill {
    width: fit-content;
    max-width: 100%;
    padding: 4px 7px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: oklch(1 0 0 / 0.035);
    color: var(--muted);
    font-family: var(--font-mono);
    font-size: 0.7rem;
    text-transform: uppercase;
}

.paid-model-plans {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
    min-width: 0;
}

.paid-model-row strong {
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.74rem;
    font-weight: 700;
    text-shadow: var(--accent-text-glow);
    white-space: nowrap;
}

.paid-model-empty {
    padding: 18px;
    border: 1px dashed var(--sk-border);
    border-radius: var(--radius-sm);
    color: var(--muted);
    font-size: 0.9rem;
}

.pricing-model-copy {
    flex: 0 0 auto;
    width: 30px;
    height: 30px;
    min-height: 30px;
    padding: 0;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-inset-bg);
    color: var(--muted);
    box-shadow: var(--sk-inset-shadow);
    cursor: pointer;
    transition:
        border-color 150ms var(--ease-out-smooth),
        color 150ms var(--ease-out-smooth),
        transform var(--press-dur) var(--ease-out-smooth);
}

.pricing-model-copy:hover {
    color: var(--text);
    border-color: oklch(0.659 0.192 40.1 / 0.42);
}

.pricing-model-copy:active {
    transform: scale(var(--press-scale));
}

@media (max-width: 1120px) {
    .paid-plan-chooser {
        grid-template-columns: 1fr;
    }
}

@media (max-width: 640px) {
    .paid-model-table {
        gap: 10px;
        overflow-x: visible;
    }

    .paid-model-row {
        grid-template-columns: 1fr 1fr;
        gap: 10px;
        min-width: 0;
        padding: 14px;
        border-radius: var(--radius);
        background: var(--sk-inset-bg);
        box-shadow: var(--sk-inset-shadow);
    }

    .paid-model-row-head {
        display: none;
    }

    .paid-model-row > * {
        display: flex;
        flex-direction: column;
        gap: 4px;
        min-width: 0;
    }

    .paid-model-row > *::before {
        content: attr(data-label);
        color: var(--dim);
        font-family: var(--font-mono);
        font-size: 0.62rem;
        letter-spacing: 0.08em;
        text-transform: uppercase;
    }

    .paid-model-row > :nth-child(1),
    .paid-model-row > :nth-child(6) {
        grid-column: 1 / -1;
    }

    .paid-model-row > :nth-child(6) {
        align-items: flex-end;
    }

    .paid-model-name {
        gap: 8px;
    }

    .paid-model-name code {
        font-size: 0.85rem;
    }
}

@media (max-width: 560px) {
    .paid-plan-options,
    .paid-plan-stat-grid,
    .paid-plan-limit-strip,
    .paid-selected-metrics {
        grid-template-columns: 1fr;
    }

    .paid-plan-chooser {
        padding: 18px;
    }

    .pricing-section {
        padding: 18px;
    }
}

@media (prefers-reduced-motion: reduce) {
    .paid-plan-option,
    .paid-plan-option.is-active,
    .paid-plan-select,
    .paid-plan-select:active,
    .pricing-model-copy,
    .pricing-model-copy:active {
        transition: none;
        transform: none;
    }
}
</style>
