// site/src/pages/home/ui/HomePage.vue
<script setup lang="ts">
import { useSeo } from "@/shared/lib/seo";
import { siteConfig } from "@/shared/config/site";
import { highlightedCode } from "@/shared/config/highlighted.generated";
import { CtaButton, DitherButton, Logo } from "@/shared/ui";
import { LiveStats } from "@/features/live-stats";
import {
    buildWebsiteJsonLd,
    buildOrganizationJsonLd,
    buildSoftwareJsonLd,
    buildWebApiJsonLd,
    buildMachineReadableResourcesJsonLd,
    buildSignupHowToJsonLd,
    buildBreadcrumbJsonLd,
} from "@/shared/lib/jsonLd";

const snippetHtml = highlightedCode.home;

const pageTitle = "FreeTheAi (Free The AI) - Free OpenAI-Compatible AI API";
const pageDescription =
    "FreeTheAi, also searched as Free The AI, is a free OpenAI-compatible AI API with 80+ active models, Discord key signup, streaming chat, tool calling, and Anthropic-style messages. No credit card or billing.";

useSeo({
    title: pageTitle,
    description: pageDescription,
    path: "/home",
    jsonLd: [
        buildWebsiteJsonLd(),
        buildOrganizationJsonLd(),
        buildSoftwareJsonLd(),
        buildWebApiJsonLd(),
        buildMachineReadableResourcesJsonLd(),
        buildSignupHowToJsonLd(),
        buildBreadcrumbJsonLd([{ name: "FreeTheAi", url: "https://freetheai.xyz/home" }]),
    ],
});
</script>

<template>
    <main>
        <section class="home-hero">
            <div class="home-hero-grid">
                <div class="home-hero-copy">
                    <h1 class="home-hero-logo">
                        <Logo :width="520" label="FreeTheAi" class="home-hero-logo-svg" />
                        <span class="sr-only">FreeTheAi — free OpenAI-compatible API</span>
                    </h1>
                    <p class="home-hero-lead">OpenAI-compatible AI API with 80+ active models. One Discord key, one base URL, zero billing.</p>
                    <div class="home-hero-cta">
                        <DitherButton
                            :href="siteConfig.socials.discord"
                            target="_blank"
                            rel="noreferrer"
                            color="orange"
                            size="lg"
                            bloom="low"
                            data-sound="interaction.confirm"
                        >
                            Get a free API key
                            <span class="hero-cta-arrow">&rarr;</span>
                        </DitherButton>
                        <DitherButton to="/docs" color="grey" variant="dotted" size="lg" data-sound="interaction.tap">Read docs</DitherButton>
                    </div>
                    <div class="home-hero-links">
                        <router-link to="/models" class="hero-link">Browse Models</router-link>
                        <router-link to="/pricing" class="hero-link">Pricing</router-link>
                    </div>
                    <div class="home-hero-stats">
                        <LiveStats />
                    </div>
                </div>
                <div class="home-hero-demo">
                    <div class="code-card home-code-card">
                        <div class="card-head">
                            <div class="dot-row"><span></span><span></span><span></span></div>
                            <div class="card-label">Try it</div>
                        </div>
                        <div class="docs-code-group">
                            <div class="shiki-wrapper" v-html="snippetHtml" />
                            <button class="copy-btn" type="button" aria-label="Copy code">
                                <span class="material-symbols-outlined">content_copy</span>
                            </button>
                        </div>
                    </div>
                    <a :href="siteConfig.socials.discord" target="_blank" rel="noreferrer" class="home-discord-link">
                        Join Discord <span class="home-discord-link-arrow">&rarr;</span>
                    </a>
                </div>
            </div>
        </section>

        <section class="section shell home-paths" aria-labelledby="home-paths-title">
            <div>
                <span class="home-paths-eyebrow">Popular setup paths</span>
                <h2 id="home-paths-title">Pick the client you are actually using.</h2>
                <p>FreeTheAi works as a custom OpenAI-compatible API across roleplay frontends, coding agents, and regular SDK apps.</p>
            </div>
            <div class="home-path-grid stagger-children">
                <router-link to="/roleplay-api">
                    <strong>Roleplay API</strong>
                    <span>SillyTavern, Janitor AI, Chub AI, RisuAI.</span>
                </router-link>
                <router-link to="/coding-agent-api">
                    <strong>Coding agent API</strong>
                    <span>OpenCode, Cline, Roo Code, Kilo Code, Zed.</span>
                </router-link>
                <router-link to="/openai-compatible-api">
                    <strong>OpenAI-compatible API</strong>
                    <span>Python, JavaScript, bots, and custom clients.</span>
                </router-link>
            </div>
        </section>

        <section class="home-content">
            <div class="rhythm stagger-children">
                <div class="beat whisper">
                    <h2 class="beat-heading">What Is FreeTheAi?</h2>
                    <p class="beat-prose">
                        FreeTheAi is a <strong>free AI API gateway</strong> with 80+ active models behind a single
                        OpenAI-compatible endpoint. No credit card, no billing, no daily caps — just a free Discord key and a
                        base URL that works with any OpenAI SDK. No prompt storage, no card required. Optional paid slots exist
                        for builders who need separate higher-power models. Built to <strong>free the AI</strong> for
                        developers, students, and builders.
                    </p>
                </div>

                <div class="beat">
                    <h2 class="beat-heading">What Can You Build?</h2>
                    <div class="diptych">
                        <div class="diptych-panel">
                            <h3 class="diptych-label">API features</h3>
                            <p>Streaming chat, tool calling and structured outputs, and Anthropic messages - all OpenAI-compatible.</p>
                        </div>
                        <div class="diptych-panel">
                            <h3 class="diptych-label">Use cases</h3>
                            <p>
                                Chatbots, coding agents, content pipelines, and multi-model orchestrations. Students prototype,
                                developers ship, researchers evaluate — all against one free endpoint.
                            </p>
                        </div>
                    </div>
                </div>

                <div class="beat shout">
                    <h2 class="beat-heading">Getting Started</h2>
                    <ol class="steps">
                        <li>Join the <a :href="siteConfig.socials.discord" target="_blank" rel="noreferrer">FreeTheAi Discord</a></li>
                        <li>Run <code>/signup</code> and complete the modal with your use case, bot answer, and human challenge</li>
                        <li>Run <code>/checkin</code> with your API key once per UTC day before using the free API</li>
                        <li>Set <code>FREETHEAI_API_KEY</code> in your environment</li>
                        <li>Point any OpenAI SDK at <code>https://api.freetheai.xyz/v1</code></li>
                        <li>Browse the <router-link to="/docs">API docs</router-link> for endpoint-specific examples</li>
                    </ol>
                    <div class="cta-wrap">
                        <CtaButton :href="siteConfig.socials.discord" target="_blank" rel="noreferrer">Get your free API key</CtaButton>
                    </div>
                </div>
            </div>
        </section>

        <section class="section shell home-support">
            <div class="home-support-card">
                <span class="home-support-eyebrow">Community funded</span>
                <h2>Keep the free tier alive.</h2>
                <p>
                    If FreeTheAi saves you a subscription or unblocks a project, a small donation helps cover servers and keeps
                    more free capacity online.
                </p>
                <div class="home-support-cta">
                    <CtaButton :href="siteConfig.socials.donate" target="_blank" rel="noreferrer" color="pink" :arrow="false">
                        <span aria-hidden="true">&#9825;</span>
                        Donate
                    </CtaButton>
                    <a class="home-support-link" :href="siteConfig.socials.github" target="_blank" rel="noreferrer">Star the repo</a>
                </div>
            </div>
        </section>
    </main>
</template>

<style scoped>
.home-hero {
    position: relative;
    overflow: hidden;
    padding: 80px 16px 48px;
    text-align: center;
}
.home-hero-grid {
    position: relative;
    z-index: 1;
    max-width: 1100px;
    margin: 0 auto;
    display: grid;
    grid-template-columns: 1fr;
    gap: 48px;
    align-items: start;
}
.home-hero-copy {
    display: grid;
    justify-items: center;
}
.home-hero-logo {
    position: relative;
    margin: 0;
}
.home-hero-logo .home-hero-logo-svg {
    display: block;
    margin: 0 auto;
    max-width: 100%;
}
.home-hero-lead {
    color: var(--muted);
    font-size: 1.15rem;
    margin: 20px auto 0;
    line-height: 1.6;
    max-width: 480px;
    text-wrap: pretty;
}
.home-hero-cta {
    margin-top: 40px;
    display: flex;
    gap: 12px;
    flex-wrap: wrap;
    justify-content: center;
}
.secondary-button {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    height: var(--control-height);
    padding: var(--control-padding);
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: transparent;
    color: var(--text);
    font-size: 0.95rem;
    font-weight: 500;
    text-decoration: none;
    transition: border-color 160ms var(--ease-out-smooth), background 160ms var(--ease-out-smooth), color 160ms var(--ease-out-smooth);
}
.secondary-button:hover {
    border-color: var(--border-strong);
    background: var(--control-bg);
}
.hero-cta-arrow {
    opacity: 0.6;
    font-size: 0.85rem;
    margin-left: 4px;
}
.home-hero-links {
    display: flex;
    gap: 16px;
    margin-top: 16px;
    justify-content: center;
}
.home-hero-demo {
    display: grid;
    justify-items: center;
    gap: 16px;
}
.home-code-card {
    text-align: left;
    width: 100%;
    max-width: 540px;
}
.home-hero-stats {
    margin-top: 40px;
    width: 100%;
    max-width: 540px;
}
.home-discord-link {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
    font-size: 0.85rem;
    text-decoration: none;
    font-weight: 500;
}
.home-discord-link-arrow {
    font-size: 1rem;
}
@media (min-width: 980px) {
    .home-hero {
        padding-top: 100px;
        text-align: left;
    }
    .home-hero-grid {
        grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
        gap: 64px;
        align-items: center;
    }
    .home-hero-copy,
    .home-hero-demo {
        justify-items: start;
    }
    .home-hero-cta,
    .home-hero-links,
    .home-hero-logo .home-hero-logo-svg {
        justify-content: flex-start;
        margin-left: 0;
    }
    .home-hero-lead {
        margin-left: 0;
    }
    .home-hero-stats {
        max-width: none;
    }
}
.home-support {
    margin-top: 8px;
}
.home-support-card {
    position: relative;
    display: grid;
    gap: 12px;
    padding: clamp(22px, 3.4vw, 32px);
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    overflow: hidden;
}
.home-support-card::before {
    content: "";
    position: absolute;
    inset: 0 auto 0 0;
    width: 3px;
    background: linear-gradient(180deg, oklch(0.75 0.173 353.8), oklch(0.659 0.192 40.1));
    pointer-events: none;
}
.home-support-eyebrow {
    position: relative;
    z-index: 1;
    color: oklch(0.803 0.128 354.3);
    font-family: var(--font-mono);
    font-size: 0.72rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    text-shadow: 0 0 8px oklch(0.75 0.173 353.8 / 0.24);
}
.home-support-card h2 {
    position: relative;
    z-index: 1;
    margin: 0;
    font-family: var(--font-serif);
    font-size: clamp(1.7rem, 3.4vw, 2.4rem);
    line-height: 1.1;
    letter-spacing: -0.02em;
}
.home-support-card p {
    position: relative;
    z-index: 1;
    margin: 0;
    max-width: 64ch;
    color: var(--muted);
    font-size: 0.98rem;
    line-height: 1.6;
    text-wrap: pretty;
}
.home-support-cta {
    position: relative;
    z-index: 1;
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
    margin-top: 6px;
}
.home-support-button {
    border-color: oklch(0.75 0.173 353.8 / 0.55);
    background: oklch(0.75 0.173 353.8 / 0.1);
    color: oklch(0.916 0 0);
    text-shadow: 0 0 10px oklch(0.75 0.173 353.8 / 0.32);
    transition: border-color 160ms var(--ease-out-smooth), background 160ms var(--ease-out-smooth), color 160ms var(--ease-out-smooth);
}
.home-support-button:hover {
    border-color: oklch(0.75 0.173 353.8 / 0.82);
    background: oklch(0.75 0.173 353.8 / 0.16);
    color: oklch(0.952 0 0);
}
.home-support-link {
    color: var(--muted);
    font-family: var(--font-mono);
    font-size: 0.86rem;
    text-decoration: none;
    border-bottom: 1px solid var(--sk-border);
    padding-bottom: 2px;
    transition: color 160ms var(--ease-out-smooth), border-color 160ms var(--ease-out-smooth);
}
.home-support-link:hover {
    color: oklch(0.803 0.128 354.3);
    border-color: oklch(0.75 0.173 353.8 / 0.45);
}
.home-paths {
    display: grid;
    gap: 18px;
    width: min(820px, 100%);
    margin: 58px auto 0;
    padding: clamp(22px, 3.8vw, 36px);
}
.home-paths h2 {
    margin: 4px 0 0;
    font-family: var(--font-serif);
    font-size: clamp(1.4rem, 2.8vw, 2rem);
    letter-spacing: -0.02em;
}
.home-paths p {
    max-width: 58ch;
    margin: 8px 0 0;
    color: var(--muted);
    font-size: 0.95rem;
    line-height: 1.55;
    text-wrap: pretty;
}
.home-paths-eyebrow {
    color: var(--dim);
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
}
.home-path-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 12px;
}
.home-path-grid a {
    display: grid;
    gap: 8px;
    min-height: 128px;
    padding: 18px 20px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    color: var(--text);
    text-decoration: none;
    transition: border-color 160ms var(--ease-out-smooth), transform 160ms var(--ease-out-smooth);
}
.home-path-grid a:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.42);
}
.home-path-grid a:active {
    transform: scale(var(--press-scale));
}
.home-path-grid strong {
    color: var(--accent-text);
    font-family: var(--font-serif);
    font-size: 1.12rem;
    letter-spacing: -0.01em;
    text-shadow: var(--accent-text-glow);
}
.home-path-grid span {
    color: var(--muted);
    font-size: 0.9rem;
    line-height: 1.5;
}
@media (hover: hover) and (pointer: fine) {
    .home-path-grid a:hover {
        transform: translateY(-2px);
    }
}
@media (prefers-reduced-motion: reduce) {
    .home-path-grid a,
    .home-path-grid a:hover,
    .home-path-grid a:active,
    .hero-link,
    .home-support-button,
    .home-support-link {
        transition: none;
        transform: none;
    }
}
@media (max-width: 820px) {
    .home-path-grid {
        grid-template-columns: 1fr;
    }
    .home-path-grid a {
        min-height: 0;
    }
}
.home-content {
    max-width: 720px;
    margin: 80px auto 0;
    padding: 0 24px 80px;
    position: relative;
    z-index: 1;
}
.rhythm {
    display: grid;
    gap: 48px;
}
.beat-heading {
    margin: 0 0 16px;
    color: var(--text);
    font-family: var(--font-serif);
    font-size: 1.6rem;
    font-weight: 600;
}
.whisper {
    padding: 20px 20px 20px 20px;
    border-left: 1px solid var(--border);
    background: var(--surface);
    border-radius: var(--radius);
}
.beat-prose {
    margin: 0;
    color: var(--muted);
    font-size: 1.05rem;
    line-height: 1.8;
}
.beat-prose strong {
    color: var(--text);
}
.diptych {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
}
.diptych-panel {
    padding: 20px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
}
.diptych-label {
    margin: 0 0 10px;
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.68rem;
    font-weight: 700;
    letter-spacing: 0.1em;
    text-transform: uppercase;
}
.diptych-panel p {
    margin: 0;
    color: var(--muted);
    font-size: 0.95rem;
    line-height: 1.65;
    text-wrap: pretty;
}
.shout {
    padding: 24px 24px 24px 28px;
    border: 1px solid var(--sk-border);
    border-left: 2px solid var(--accent);
    border-radius: 0 var(--radius) var(--radius) 0;
    background: var(--sk-shell-bg);
    box-shadow: var(--sk-raised-shadow);
}
.shout .beat-heading {
    margin-bottom: 16px;
}
.steps {
    margin: 0 0 24px;
    padding-left: 24px;
    color: var(--muted);
    line-height: 2;
}
.steps a {
    color: var(--accent-text);
    text-underline-offset: 3px;
}
.steps code {
    color: var(--accent-text);
    background: var(--accent-muted);
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 0.9em;
}
.cta-wrap {
    margin-top: 28px;
}
.cta-arrow {
    opacity: 0.6;
    font-size: 0.85rem;
    margin-left: 4px;
}
.hero-link {
    color: var(--muted);
    font-size: 0.9rem;
    text-decoration: underline;
    text-underline-offset: 3px;
    transition: color 120ms var(--ease-out-smooth);
}
@media (hover: hover) and (pointer: fine) {
    .hero-link:hover {
        color: var(--text);
    }
}
@media (max-width: 640px) {
    .diptych {
        grid-template-columns: 1fr;
        gap: 12px;
    }
    .shout {
        padding: 20px 16px 20px 20px;
    }
    .whisper {
        padding-left: 14px;
    }
    .rhythm {
        gap: 40px;
    }
}
</style>

// site/src/lib/pages/home/ui/HomePage.svelte
<script lang="ts">
    import { spotlight } from "@/shared/lib/spotlight";
    import {
        siAnthropic,
        siGooglegemini,
        siDeepseek,
        siMeta,
        siMistralai,
        siQwen,
        siX,
        siNvidia,
        siMinimax,
        siKimi,
        siOllama,
        siHuggingface,
    } from "simple-icons";
    import { buildSeo } from "@/shared/lib/seo";
    import { siteConfig } from "@/shared/config/site";
    import { CtaButton, DitherButton, SeoHead } from "@/shared/ui";
    import { LiveStats } from "@/features/live-stats";
    import {
        buildWebsiteJsonLd,
        buildOrganizationJsonLd,
        buildSoftwareJsonLd,
        buildWebApiJsonLd,
        buildMachineReadableResourcesJsonLd,
        buildSignupHowToJsonLd,
        buildBreadcrumbJsonLd,
    } from "@/shared/lib/jsonLd";

    const pageTitle = "FreeTheAi (Free The AI) - Free OpenAI-Compatible AI API";
    const pageDescription =
        "FreeTheAi, also searched as Free The AI, is a free OpenAI-compatible AI API with 80+ active models, Discord key signup, streaming chat, tool calling, and Anthropic-style messages. No credit card or billing.";

    const seo = buildSeo({
        title: pageTitle,
        description: pageDescription,
        path: "/home",
        jsonLd: [
            buildWebsiteJsonLd(),
            buildOrganizationJsonLd(),
            buildSoftwareJsonLd(),
            buildWebApiJsonLd(),
            buildMachineReadableResourcesJsonLd(),
            buildSignupHowToJsonLd(),
            buildBreadcrumbJsonLd([{ name: "FreeTheAi", url: "https://freetheai.xyz/home" }]),
        ],
    });

    const providerIcons = [
        siAnthropic,
        siGooglegemini,
        siDeepseek,
        siMeta,
        siMistralai,
        siQwen,
        siX,
        siNvidia,
        siMinimax,
        siKimi,
        siOllama,
        siHuggingface,
    ];

    const howItWorks: [string, string, string][] = [
        ["Join the Discord", "Run /signup in the FreeTheAi Discord and get your API key in a minute. No card, no billing.", "forum"],
        ["Call any model", "OpenAI, Anthropic, Google, and more through one API. Three formats share one key and one base URL.", "code"],
        ["Check in daily", "Run /checkin once per UTC day to keep your key hot. Fair-use limits keep capacity fast for everyone.", "check_circle"],
    ];

    const whyCards: [string, string, string][] = [
        ["One key, zero billing", "Every model on the catalog answers to the same Discord key. No subscriptions, no meters, no invoices.", "key"],
        ["Free by design", "Donated and sponsored capacity keeps the free tier online. Daily check-in keeps it shared fairly.", "favorite"],
        ["Paid slots when you need more", "Optional paid slots unlock separate higher-power models. The free tier stays free either way.", "speed"],
        ["Your clients already work", "SillyTavern, OpenCode, Cline, Zed, and any OpenAI SDK point at one base URL. Setup guides cover 20+ apps.", "devices"],
        ["Three formats, one API", "OpenAI Chat Completions, OpenAI Responses, and Anthropic Messages use one account and one base URL.", "toc"],
        ["Community funded", "A small donation covers servers and keeps more free capacity online. Issues and requests land on the support page.", "support_agent"],
    ];

</script>

<svelte:head>
    <link rel="preload" as="image" href="/hero-dune.webp" />
</svelte:head>

<SeoHead {seo} />

<main>
    <section class="hp-hero">
        <div class="hp-hero-art" aria-hidden="true">
            <img src="/hero-dune.webp" alt="" width="1080" height="878" />
        </div>
        <div class="hp-hero-content">
            <h1>The models you want. The bill <span class="hp-underline">you&nbsp;never&nbsp;see.</span></h1>
            <p class="hp-hero-sub">
                Free OpenAI-compatible API. One Discord key, one base URL, daily check-in, zero billing.
            </p>
            <div class="hp-cta-row">
                <DitherButton
                    href={siteConfig.socials.discord}
                    target="_blank"
                    rel="noreferrer"
                    color="grey"
                    size="lg"
                    data-sound="interaction.confirm">Get a free key</DitherButton>
                <a class="hp-btn-ghost" href="/models" data-sound="interaction.tap">Browse models</a>
            </div>
        </div>
    </section>

    <div class="hp-reveal">
        <LiveStats />
    </div>

    <section class="hp-section hp-reveal" aria-labelledby="hp-how-title">
        <div class="hp-split">
            <div class="hp-split-head">
                <h2 id="hp-how-title">How it works</h2>
                <p>One key, one base URL, a catalog full of models.</p>
            </div>
            <div class="hp-card-grid hp-card-grid-3">
                {#each howItWorks as [title, text, icon] (title)}
                    <article class="hp-card" use:spotlight>
                        <span class="hp-card-icon material-symbols-outlined" aria-hidden="true">{icon}</span>
                        <h3>{title}</h3>
                        <p>{text}</p>
                    </article>
                {/each}
            </div>
        </div>
    </section>

    <section class="hp-section hp-providers hp-reveal" aria-labelledby="hp-providers-title">
        <h2 id="hp-providers-title">The providers you already&nbsp;know</h2>
        <div class="hp-provider-row">
            {#each providerIcons as icon (icon.slug)}
                <span class="hp-provider-icon" title={icon.title}>
                    <svg viewBox="0 0 24 24" fill="currentColor" role="img" aria-label={icon.title}><path d={icon.path} /></svg>
                </span>
            {/each}
        </div>
    </section>

    <section class="hp-section hp-reveal" aria-labelledby="hp-why-title">
        <div class="hp-split">
            <div class="hp-split-head">
                <h2 id="hp-why-title">Why FreeTheAI</h2>
                <p>One free key, every major model family, no billing anywhere.</p>
            </div>
            <div class="hp-card-grid hp-card-grid-3">
                {#each whyCards as [title, text, icon] (title)}
                    <article class="hp-card" use:spotlight>
                        <span class="hp-card-icon material-symbols-outlined" aria-hidden="true">{icon}</span>
                        <h3>{title}</h3>
                        <p>{text}</p>
                    </article>
                {/each}
            </div>
        </div>
    </section>

    <section class="hp-cta hp-crop hp-reveal" aria-labelledby="hp-cta-title">
        <div class="hp-cta-copy">
            <h2 id="hp-cta-title">Stop paying list price for&nbsp;AI</h2>
            <p>Join the Discord, run /signup, and call top models free in minutes. The v2 marketplace is on the way.</p>
        </div>
        <div class="hp-cta-row">
            <DitherButton
                href={siteConfig.socials.discord}
                target="_blank"
                rel="noreferrer"
                color="grey"
                size="lg"
                data-sound="interaction.confirm">Get a free key</DitherButton>
            <a class="hp-btn-ghost" href="/models" data-sound="interaction.tap">Browse models</a>
        </div>
    </section>

    <section class="hp-start hp-crop hp-reveal" aria-labelledby="hp-start-title">
        <h2 id="hp-start-title">Get started<br />with FreeTheAI</h2>
        <CtaButton to="/quickstart" color="grey" size="lg" bloom="off">Quickstart</CtaButton>
    </section>
</main>

<style>
    main {
        gap: clamp(56px, 8vw, 96px);
    }

    /* ── Hero ── */
    .hp-hero {
        position: relative;
        overflow: hidden;
        border: 1px solid var(--border);
        border-radius: var(--radius);
        min-height: clamp(440px, 52vw, 540px);
        display: flex;
        align-items: center;
        background: var(--bg);
    }
    .hp-hero-art {
        position: absolute;
        inset: 0;
    }
    .hp-hero-art img {
        position: absolute;
        top: 0;
        left: 10%;
        width: 124%;
        max-width: none;
        height: 100%;
        object-fit: cover;
        object-position: center 14%;
    }
    /* Blend the artwork into the card so the copy keeps AA contrast. */
    .hp-hero-art::after {
        content: "";
        position: absolute;
        inset: 0;
        background:
            linear-gradient(90deg, oklch(0.13 0 0 / 0.96) 0%, oklch(0.13 0 0 / 0.82) 32%, oklch(0.13 0 0 / 0.25) 62%, transparent 82%),
            linear-gradient(0deg, oklch(0.13 0 0 / 0.55) 0%, transparent 32%);
    }
    .hp-hero-content {
        position: relative;
        z-index: 1;
        max-width: 660px;
        padding: clamp(24px, 4.5vw, 56px);
    }
    .hp-hero-content h1 {
        font-size: clamp(2.3rem, 4.6vw, 3.9rem);
        font-weight: 600;
        line-height: 1.02;
        letter-spacing: -0.04em;
    }
    .hp-underline {
        text-decoration: none;
        background-image: linear-gradient(
            90deg,
            oklch(0.72 0.11 265 / 0.85),
            oklch(0.78 0.1 195 / 0.85),
            oklch(0.82 0.12 145 / 0.85),
            oklch(0.85 0.13 100 / 0.85)
        );
        background-repeat: no-repeat;
        background-size: 100% 0.07em;
        background-position: 0 96%;
    }
    .hp-hero-sub {
        margin: 20px 0 0;
        max-width: 46ch;
        font-family: var(--font-mono);
        font-size: 0.8rem;
        line-height: 1.7;
        color: var(--muted);
    }
    .hp-cta-row {
        display: flex;
        flex-wrap: wrap;
        gap: 12px;
        margin-top: 28px;
    }
    .hp-btn-ghost {
        font-family: var(--font-mono);
        font-size: 0.78rem;
        min-height: var(--control-height);
    }
    .hp-btn-ghost {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        padding: var(--control-padding);
        border: 1px solid var(--border-strong);
        border-radius: var(--radius);
        background: oklch(1 0 0 / 0.04);
        color: var(--text);
        font-weight: 500;
        text-decoration: none;
        cursor: pointer;
        transition:
            background 200ms var(--ease-out-smooth),
            border-color 200ms var(--ease-out-smooth),
            transform var(--press-dur) var(--ease-out-smooth);
    }
    .hp-btn-ghost:hover {
        background: oklch(1 0 0 / 0.09);
    }
    .hp-btn-ghost:active {
        transform: scale(var(--press-scale));
    }

    /* ── Sections ── */
    .hp-section {
        display: grid;
        gap: clamp(28px, 4vw, 44px);
    }
    .hp-split {
        display: grid;
        grid-template-columns: minmax(220px, 0.8fr) minmax(0, 2fr);
        gap: clamp(24px, 4vw, 48px);
        align-items: start;
    }
    .hp-split-head {
        position: sticky;
        top: 96px;
    }
    .hp-split-head h2,
    .hp-providers h2 {
        font-size: clamp(1.7rem, 3vw, 2.3rem);
        font-weight: 600;
        letter-spacing: -0.03em;
        line-height: 1.1;
    }
    .hp-split-head p {
        margin: 14px 0 0;
        max-width: 30ch;
        font-family: var(--font-mono);
        font-size: 0.74rem;
        line-height: 1.7;
        color: var(--muted);
    }

    /* ── Cards ── */
    .hp-card-grid {
        display: grid;
        gap: 14px;
    }
    .hp-card-grid-3 {
        grid-template-columns: repeat(3, minmax(0, 1fr));
    }
    .hp-card {
        position: relative;
        overflow: hidden;
        border: 1px solid var(--border);
        border-radius: var(--radius);
        background: oklch(1 0 0 / 0.02);
        padding: 20px;
        display: grid;
        gap: 12px;
        align-content: start;
    }
    .hp-card::before {
        content: "";
        position: absolute;
        inset: 0;
        border-radius: inherit;
        background: radial-gradient(180px circle at var(--spotlight-x, 50%) var(--spotlight-y, 50%), oklch(1 0 0 / 0.07), transparent 70%);
        opacity: 0;
        transition: opacity 250ms var(--ease-out-smooth);
        pointer-events: none;
    }
    .hp-card:hover::before {
        opacity: 1;
    }
    @media (prefers-reduced-motion: reduce), (hover: none) {
        .hp-card::before {
            display: none;
        }
    }
    .hp-card-icon {
        font-size: 17px;
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 34px;
        height: 34px;
        border: 1px solid var(--border);
        border-radius: var(--radius-sm);
        background: var(--sk-inset-bg);
        color: var(--muted);
    }
    .hp-card h3 {
        font-size: 0.92rem;
        font-weight: 600;
        letter-spacing: -0.01em;
    }
    .hp-card p {
        margin: 0;
        font-family: var(--font-mono);
        font-size: 0.7rem;
        line-height: 1.65;
        color: var(--muted);
    }

    /* ── Providers ── */
    .hp-providers {
        justify-items: center;
        text-align: center;
    }
    .hp-provider-row {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        gap: clamp(22px, 4vw, 44px);
    }
    .hp-provider-icon {
        display: inline-flex;
        color: var(--dim);
    }
    .hp-provider-icon:hover {
        color: var(--text);
    }
    .hp-provider-icon svg {
        width: 26px;
        height: 26px;
    }

    /* ── CTA panels with crop marks ── */
    .hp-crop {
        position: relative;
    }
    .hp-crop::before,
    .hp-crop::after {
        content: "";
        position: absolute;
        top: 0;
        width: 14px;
        height: 14px;
        border-top: 1.5px solid var(--border-strong);
        pointer-events: none;
    }
    .hp-crop::before {
        left: 0;
        border-left: 1.5px solid var(--border-strong);
    }
    .hp-crop::after {
        right: 0;
        border-right: 1.5px solid var(--border-strong);
    }
    .hp-cta,
    .hp-start {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 24px;
        padding: clamp(20px, 3vw, 32px) 0;
    }
    .hp-cta-copy h2 {
        font-size: clamp(1.8rem, 3.4vw, 2.6rem);
        font-weight: 600;
        letter-spacing: -0.03em;
        line-height: 1.08;
    }
    .hp-cta-copy p {
        margin: 14px 0 0;
        max-width: 52ch;
        font-family: var(--font-mono);
        font-size: 0.74rem;
        line-height: 1.7;
        color: var(--muted);
    }
    .hp-cta .hp-cta-row {
        margin-top: 0;
        flex-shrink: 0;
    }
    .hp-start h2 {
        font-size: clamp(2.2rem, 4.6vw, 3.6rem);
        font-weight: 600;
        letter-spacing: -0.04em;
        line-height: 1.04;
    }

    @media (max-width: 56em) {
        .hp-split {
            grid-template-columns: 1fr;
        }
        .hp-split-head {
            position: static;
        }
        .hp-card-grid-3 {
            grid-template-columns: repeat(2, minmax(0, 1fr));
        }
        .hp-cta,
        .hp-start {
            flex-direction: column;
            align-items: flex-start;
        }
    }
    @media (max-width: 34em) {
        .hp-card-grid-3 {
            grid-template-columns: 1fr;
        }
    }

    /* ── Flavor pass: dither glows, halftone, sheen, reveals ── */

    /* Halftone dot texture inside the icon boxes - printed, tactile feel. */
    .hp-card-icon {
        background-image: radial-gradient(circle, oklch(1 0 0 / 0.12) 1px, transparent 1.3px);
        background-size: 4px 4px;
    }

    /* Card and provider hover physics. */
    .hp-card {
        transition:
            transform 180ms var(--ease-out-smooth),
            border-color 180ms var(--ease-out-smooth),
            background-color 180ms var(--ease-out-smooth);
    }
    .hp-card:hover {
        transform: translateY(-2px);
        border-color: var(--border-strong);
        background: oklch(1 0 0 / 0.04);
    }
    .hp-provider-icon {
        transition:
            color 150ms var(--ease-out-smooth),
            transform 150ms var(--ease-out-smooth);
    }
    .hp-provider-icon:hover {
        transform: translateY(-2px) scale(1.08);
    }

    /* Hero entry + section scroll reveals. CSS scroll-driven animations with
     * an @supports gate so non-supporting engines just see static content. */
    @keyframes hp-rise {
        from {
            opacity: 0;
            transform: translateY(26px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }
    @media (prefers-reduced-motion: no-preference) {
        .hp-hero {
            animation: hp-rise 0.7s var(--ease-out-smooth) both;
        }
        @supports (animation-timeline: view()) {
            .hp-reveal {
                animation: hp-rise linear both;
                animation-timeline: view();
                animation-range: entry 0% entry 55%;
            }
        }
    }
</style>
