// site/src/lib/pages/what-is/ui/WhatIsPage.svelte
<script lang="ts">
    import { buildSeo } from "@/shared/lib/seo";
    import { siteConfig } from "@/shared/config/site";
    import { CtaButton, DitherGradient, SeoHead } from "@/shared/ui";
    import { buildBreadcrumbJsonLd, buildOrganizationJsonLd, buildSoftwareJsonLd, buildWebsiteJsonLd, buildWebApiJsonLd } from "@/shared/lib/jsonLd";

    const pageDescription =
        "FreeTheAi, also searched as Free The AI or Free The Ai, is a free OpenAI-compatible AI API built by Vibhek Soni to share AI tools with everyone. 80+ active models, Discord key signup, daily /checkin, no credit card.";

    const seo = buildSeo({
        title: "What Is Free The AI - FreeTheAi for Developers",
        description: pageDescription,
        path: "/what-is-free-the-ai",
        jsonLd: [
            buildWebsiteJsonLd(),
            buildOrganizationJsonLd(),
            buildSoftwareJsonLd(),
            buildWebApiJsonLd(),
            {
                "@context": "https://schema.org",
                "@type": "Article",
                headline: "What Is Free The AI",
                description: pageDescription,
                mainEntityOfPage: "https://freetheai.xyz/what-is-free-the-ai",
                author: {
                    "@type": "Person",
                    name: "Vibhek Soni",
                    url: "https://github.com/vibheksoni",
                    image: "https://avatars.githubusercontent.com/u/102437829?v=4",
                },
                publisher: { "@id": "https://freetheai.xyz/#organization" },
                image: "https://freetheai.xyz/FreeTheAi.png",
                inLanguage: "en-US",
            },
            buildBreadcrumbJsonLd([
                { name: "FreeTheAi", url: "https://freetheai.xyz/home" },
                { name: "What Is Free The AI", url: "https://freetheai.xyz/what-is-free-the-ai" },
            ]),
        ],
    });
</script>

<SeoHead {seo} />

<main class="explainer-main">
    <article class="explainer-shell shell">
        <header class="explainer-head">
            <DitherGradient class="explainer-glow" from="orange" direction="up" opacity={0.28} />
            <span class="eyebrow">About</span>
            <h1>What Is Free The AI?</h1>
            <p class="explainer-lede">
                <strong>FreeTheAi</strong> is a free OpenAI-compatible AI API built by
                <a href="https://github.com/vibheksoni" target="_blank" rel="noreferrer">Vibhek Soni</a>
                to share the AI tools he had access to with everyone. Free chat, free Anthropic-style messages, no credit
                card, no waiting list.
            </p>
            <p class="explainer-sub">
                If you searched for <em>FreeTheAi</em>, <em>Free The AI</em>, <em>Free The Ai</em>,
                <em>Free The AI API</em>, or <em>FreeTheAI</em>, this is the developer platform you want.
            </p>
            <div class="docs-hero-meta explainer-stats">
                <span class="docs-hero-stat"><strong>80+</strong> models</span>
                <span class="docs-hero-stat"><strong>0¢</strong> free tier</span>
                <span class="docs-hero-stat"><strong>Discord</strong> key signup</span>
            </div>
            <div class="explainer-cta-row">
                <CtaButton href={siteConfig.socials.discord} target="_blank" rel="noreferrer">Get a free API key</CtaButton>
                <a class="explainer-secondary" href="/quickstart">Read the quickstart</a>
            </div>
        </header>

        <section class="explainer-card">
            <h2>Why FreeTheAi exists</h2>
            <p>
                Vibhek had access to a lot of free AI resources spread across different platforms, providers, and trial
                pools. Most developers either never find them or stitch together a dozen APIs to use them. FreeTheAi pools
                all of that into one OpenAI-compatible endpoint so anyone can build with real models without paying upfront,
                signing up to ten dashboards, or fighting expired free tiers.
            </p>
            <p>
                The free tier stays free. The Discord-based signup and daily <code>/checkin</code> exist to keep automated
                abuse off the pool so it stays usable for actual builders.
            </p>
            <p>
                The project is open source on
                <a href="https://github.com/Free-The-Ai/free-ai" target="_blank" rel="noreferrer">GitHub</a>
                and run by a small team. Meet them on the <a href="/team">team page</a>.
            </p>
        </section>

        <section class="explainer-card">
            <h2>How FreeTheAi works</h2>
            <ul class="explainer-bullets">
                <li>Free OpenAI-compatible API at <code>https://api.freetheai.xyz/v1</code></li>
                <li>80+ active models across chat, tool calling, and compatibility routes</li>
                <li>Drop-in for the OpenAI Python and JavaScript SDKs - just change <code>base_url</code> and the API key</li>
                <li>Anthropic-style <code>/v1/messages</code> compatibility for Claude-style clients</li>
                <li>No credit card. Keys come from the FreeTheAi Discord with <code>/signup</code> and a one-tap daily <code>/checkin</code>.</li>
            </ul>
        </section>

        <section class="explainer-card">
            <h2>Where to go next</h2>
            <div class="explainer-links">
                <a class="explainer-link" href="/quickstart">
                    <strong>Quickstart</strong>
                    <span>Get a key, send your first OpenAI-compatible request, see a 200 in under a minute.</span>
                </a>
                <a class="explainer-link" href="/docs">
                    <strong>API docs</strong>
                    <span>Chat completions, Anthropic messages, model listing, images, errors, and rate limits.</span>
                </a>
                <a class="explainer-link" href="/models">
                    <strong>Model catalog</strong>
                    <span>Live searchable list of every public alias, with copyable IDs and provider prefixes.</span>
                </a>
                <a class="explainer-link" href="/team">
                    <strong>Team</strong>
                    <span>The people behind FreeTheAi: Vibhek, Dr. Vova, and Sai Revanth.</span>
                </a>
                <a class="explainer-link" href="/pricing">
                    <strong>Pricing</strong>
                    <span>The free tier stays free. Optional $8/month launch slots cover separate higher-power models.</span>
                </a>
                <a class="explainer-link" href="/status">
                    <strong>Status</strong>
                    <span>Live provider health by alias prefix, with filterable up / degraded / down state.</span>
                </a>
            </div>
        </section>

        <section class="explainer-card explainer-note">
            <h2>Frequently confused names</h2>
            <p>
                The brand can appear written as <code>FreeTheAi</code>, <code>FreeTheAI</code>, <code>Free The AI</code>,
                <code>Free The Ai</code>, or <code>Free TheAI</code>. They all point to the same project at
                <a href="https://freetheai.xyz">freetheai.xyz</a>. The canonical wordmark is <strong>FreeTheAi</strong>.
            </p>
            <p>
                FreeTheAi is unrelated to broader phrases like "free the AI" used in opinion writing or activism. If you
                came here looking for the developer API, you are in the right place.
            </p>
        </section>

        <footer class="explainer-foot">
            <CtaButton href={siteConfig.socials.discord} target="_blank" rel="noreferrer">Get a free API key</CtaButton>
            <a class="explainer-secondary" href="/quickstart">Read the quickstart</a>
        </footer>
    </article>
</main>

<style>
.explainer-main {
    gap: 28px;
    padding: 22px 0 64px;
}
.explainer-shell {
    display: grid;
    gap: 22px;
    padding: clamp(28px, 4.6vw, 52px);
}
.explainer-head {
    position: relative;
}
:global(.explainer-glow) {
    z-index: 0;
}
.explainer-head > :global(*:not(.explainer-glow)) {
    position: relative;
    z-index: 1;
}
.explainer-head h1 {
    margin: 0 0 12px;
    font-size: clamp(2.35rem, 4.6vw, 3.5rem);
    line-height: 1.04;
    letter-spacing: -0.045em;
}
.explainer-lede {
    margin: 0 0 8px;
    max-width: 62ch;
    color: var(--text);
    font-size: 1.05rem;
    line-height: 1.55;
}
.explainer-sub {
    margin: 0;
    max-width: 62ch;
    color: var(--muted);
    font-size: 0.95rem;
    line-height: 1.55;
}
.explainer-card {
    padding: 22px 24px;
    border: 1px solid var(--sk-border);
    border-left: 2px solid transparent;
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    transition: border-left-color 200ms var(--ease-out-smooth);
}
.explainer-card:hover {
    border-left-color: var(--accent);
}
.explainer-card h2 {
    margin: 0 0 12px;
    font-family: var(--font-serif);
    font-size: 1.35rem;
}
.explainer-card p {
    margin: 0 0 10px;
    color: var(--muted);
    line-height: 1.6;
}
.explainer-card p:last-child {
    margin-bottom: 0;
}
.explainer-card code {
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.85em;
}
.explainer-bullets {
    margin: 0;
    padding: 0 0 0 20px;
    color: var(--muted);
    line-height: 1.6;
}
.explainer-bullets li {
    margin-bottom: 6px;
}
.explainer-note {
    border-left: 2px solid var(--accent);
    background: linear-gradient(90deg, oklch(0.659 0.192 40.1 / 0.06) 0%, var(--sk-inset-bg) 40%);
}
.explainer-note:hover {
    border-left-color: var(--accent);
}
.explainer-links {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
    gap: 12px;
    margin-top: 4px;
}
.explainer-link {
    display: grid;
    gap: 4px;
    padding: 14px 16px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-shell-bg);
    color: var(--text);
    text-decoration: none;
    transition: border-color 150ms var(--ease-out-smooth), box-shadow 150ms var(--ease-out-smooth), transform 160ms var(--ease-out-smooth);
}
.explainer-link:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.42);
    box-shadow: var(--sk-inset-shadow), 0 0 0 1px oklch(0.659 0.192 40.1 / 0.18), 0 0 12px oklch(0.659 0.192 40.1 / 0.12);
    transform: translateY(-2px);
}
.explainer-stats {
    margin-top: 4px;
    padding: 14px 18px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-shell-bg);
    box-shadow: var(--sk-raised-shadow);
}
.explainer-stats :global(.docs-hero-stat strong) {
    font-size: 1.25rem;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
}
.explainer-cta-row {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
    margin-top: 4px;
}
.explainer-cta-row :global(.cta-arrow) {
    opacity: 0.65;
    font-size: 0.9rem;
}
.explainer-link strong {
    font-family: var(--font-mono);
    font-size: 0.92rem;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
}
.explainer-link span {
    color: var(--muted);
    font-size: 0.85rem;
    line-height: 1.5;
}
.explainer-foot {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
    padding: 28px 32px;
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    position: relative;
    overflow: hidden;
}
.explainer-foot::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 2px;
    background: linear-gradient(90deg, transparent, var(--accent), transparent);
}
.explainer-foot :global(.cta-arrow) {
    opacity: 0.65;
    font-size: 0.9rem;
}
.explainer-secondary {
    color: var(--muted);
    font-size: 0.92rem;
    text-decoration: none;
    border-bottom: 1px solid var(--sk-border);
    padding-bottom: 2px;
    transition: color 150ms var(--ease-out-smooth), border-color 150ms var(--ease-out-smooth);
}
.explainer-secondary:hover {
    color: var(--accent-text);
    border-color: oklch(0.659 0.192 40.1 / 0.42);
}
@media (max-width: 560px) {
    .explainer-shell {
        padding: 22px;
    }
}
@media (prefers-reduced-motion: reduce) {
    .explainer-link,
    .explainer-secondary,
    .explainer-card {
        transition: none;
    }
}
</style>

// site/src/pages/what-is/ui/WhatIsPage.vue
<script setup lang="ts">
import { useSeo } from "@/shared/lib/seo";
import { siteConfig } from "@/shared/config/site";
import { CtaButton, DitherGradient } from "@/shared/ui";
import { buildBreadcrumbJsonLd, buildOrganizationJsonLd, buildSoftwareJsonLd, buildWebsiteJsonLd, buildWebApiJsonLd } from "@/shared/lib/jsonLd";

const pageDescription =
    "FreeTheAi, also searched as Free The AI or Free The Ai, is a free OpenAI-compatible AI API built by Vibhek Soni to share AI tools with everyone. 80+ active models, Discord key signup, daily /checkin, no credit card.";

useSeo({
    title: "What Is Free The AI - FreeTheAi for Developers",
    description: pageDescription,
    path: "/what-is-free-the-ai",
    jsonLd: [
        buildWebsiteJsonLd(),
        buildOrganizationJsonLd(),
        buildSoftwareJsonLd(),
        buildWebApiJsonLd(),
        {
            "@context": "https://schema.org",
            "@type": "Article",
            headline: "What Is Free The AI",
            description: pageDescription,
            mainEntityOfPage: "https://freetheai.xyz/what-is-free-the-ai",
            author: {
                "@type": "Person",
                name: "Vibhek Soni",
                url: "https://github.com/vibheksoni",
                image: "https://avatars.githubusercontent.com/u/102437829?v=4",
            },
            publisher: { "@id": "https://freetheai.xyz/#organization" },
            image: "https://freetheai.xyz/FreeTheAi.png",
            inLanguage: "en-US",
        },
        buildBreadcrumbJsonLd([
            { name: "FreeTheAi", url: "https://freetheai.xyz/home" },
            { name: "What Is Free The AI", url: "https://freetheai.xyz/what-is-free-the-ai" },
        ]),
    ],
});
</script>

<template>
    <main class="explainer-main">
        <article class="explainer-shell shell">
            <header class="explainer-head">
                <DitherGradient class="explainer-glow" from="orange" direction="up" :opacity="0.28" />
                <span class="eyebrow">About</span>
                <h1>What Is Free The AI?</h1>
                <p class="explainer-lede">
                    <strong>FreeTheAi</strong> is a free OpenAI-compatible AI API built by
                    <a href="https://github.com/vibheksoni" target="_blank" rel="noreferrer">Vibhek Soni</a>
                    to share the AI tools he had access to with everyone. Free chat, free Anthropic-style messages, no credit
                    card, no waiting list.
                </p>
                <p class="explainer-sub">
                    If you searched for <em>FreeTheAi</em>, <em>Free The AI</em>, <em>Free The Ai</em>,
                    <em>Free The AI API</em>, or <em>FreeTheAI</em>, this is the developer platform you want.
                </p>
                <div class="docs-hero-meta explainer-stats">
                    <span class="docs-hero-stat"><strong>80+</strong> models</span>
                    <span class="docs-hero-stat"><strong>0¢</strong> free tier</span>
                    <span class="docs-hero-stat"><strong>Discord</strong> key signup</span>
                </div>
                <div class="explainer-cta-row">
                    <CtaButton :href="siteConfig.socials.discord" target="_blank" rel="noreferrer">Get a free API key</CtaButton>
                    <router-link class="explainer-secondary" to="/quickstart">Read the quickstart</router-link>
                </div>
            </header>

            <section class="explainer-card">
                <h2>Why FreeTheAi exists</h2>
                <p>
                    Vibhek had access to a lot of free AI resources spread across different platforms, providers, and trial
                    pools. Most developers either never find them or stitch together a dozen APIs to use them. FreeTheAi pools
                    all of that into one OpenAI-compatible endpoint so anyone can build with real models without paying upfront,
                    signing up to ten dashboards, or fighting expired free tiers.
                </p>
                <p>
                    The free tier stays free. The Discord-based signup and daily <code>/checkin</code> exist to keep automated
                    abuse off the pool so it stays usable for actual builders.
                </p>
                <p>
                    The project is open source on
                    <a href="https://github.com/Free-The-Ai/free-ai" target="_blank" rel="noreferrer">GitHub</a>
                    and run by a small team. Meet them on the <router-link to="/team">team page</router-link>.
                </p>
            </section>

            <section class="explainer-card">
                <h2>How FreeTheAi works</h2>
                <ul class="explainer-bullets">
                    <li>Free OpenAI-compatible API at <code>https://api.freetheai.xyz/v1</code></li>
                    <li>80+ active models across chat, tool calling, and compatibility routes</li>
                    <li>Drop-in for the OpenAI Python and JavaScript SDKs - just change <code>base_url</code> and the API key</li>
                    <li>Anthropic-style <code>/v1/messages</code> compatibility for Claude-style clients</li>
                    <li>No credit card. Keys come from the FreeTheAi Discord with <code>/signup</code> and a one-tap daily <code>/checkin</code>.</li>
                </ul>
            </section>

            <section class="explainer-card">
                <h2>Where to go next</h2>
                <div class="explainer-links">
                    <router-link class="explainer-link" to="/quickstart">
                        <strong>Quickstart</strong>
                        <span>Get a key, send your first OpenAI-compatible request, see a 200 in under a minute.</span>
                    </router-link>
                    <router-link class="explainer-link" to="/docs">
                        <strong>API docs</strong>
                        <span>Chat completions, Anthropic messages, model listing, images, errors, and rate limits.</span>
                    </router-link>
                    <router-link class="explainer-link" to="/models">
                        <strong>Model catalog</strong>
                        <span>Live searchable list of every public alias, with copyable IDs and provider prefixes.</span>
                    </router-link>
                    <router-link class="explainer-link" to="/team">
                        <strong>Team</strong>
                        <span>The people behind FreeTheAi: Vibhek, Dr. Vova, and Sai Revanth.</span>
                    </router-link>
                    <router-link class="explainer-link" to="/pricing">
                        <strong>Pricing</strong>
                        <span>The free tier stays free. Optional $8/month launch slots cover separate higher-power models.</span>
                    </router-link>
                    <router-link class="explainer-link" to="/status">
                        <strong>Status</strong>
                        <span>Live provider health by alias prefix, with filterable up / degraded / down state.</span>
                    </router-link>
                </div>
            </section>

            <section class="explainer-card explainer-note">
                <h2>Frequently confused names</h2>
                <p>
                    The brand can appear written as <code>FreeTheAi</code>, <code>FreeTheAI</code>, <code>Free The AI</code>,
                    <code>Free The Ai</code>, or <code>Free TheAI</code>. They all point to the same project at
                    <a href="https://freetheai.xyz">freetheai.xyz</a>. The canonical wordmark is <strong>FreeTheAi</strong>.
                </p>
                <p>
                    FreeTheAi is unrelated to broader phrases like "free the AI" used in opinion writing or activism. If you
                    came here looking for the developer API, you are in the right place.
                </p>
            </section>

            <footer class="explainer-foot">
                <CtaButton :href="siteConfig.socials.discord" target="_blank" rel="noreferrer">Get a free API key</CtaButton>
                <router-link class="explainer-secondary" to="/quickstart">Read the quickstart</router-link>
            </footer>
        </article>
    </main>
</template>

<style scoped>
.explainer-main {
    gap: 28px;
    padding: 22px 0 64px;
}
.explainer-shell {
    display: grid;
    gap: 22px;
    padding: clamp(28px, 4.6vw, 52px);
}
.explainer-head {
    position: relative;
}
.explainer-glow {
    z-index: 0;
}
.explainer-head > *:not(.explainer-glow) {
    position: relative;
    z-index: 1;
}
.explainer-head h1 {
    margin: 0 0 12px;
    font-size: clamp(2.35rem, 4.6vw, 3.5rem);
    line-height: 1.04;
    letter-spacing: -0.045em;
}
.explainer-lede {
    margin: 0 0 8px;
    max-width: 62ch;
    color: var(--text);
    font-size: 1.05rem;
    line-height: 1.55;
}
.explainer-sub {
    margin: 0;
    max-width: 62ch;
    color: var(--muted);
    font-size: 0.95rem;
    line-height: 1.55;
}
.explainer-card {
    padding: 22px 24px;
    border: 1px solid var(--sk-border);
    border-left: 2px solid transparent;
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    transition: border-left-color 200ms var(--ease-out-smooth);
}
.explainer-card:hover {
    border-left-color: var(--accent);
}
.explainer-card h2 {
    margin: 0 0 12px;
    font-family: var(--font-serif);
    font-size: 1.35rem;
}
.explainer-card p {
    margin: 0 0 10px;
    color: var(--muted);
    line-height: 1.6;
}
.explainer-card p:last-child {
    margin-bottom: 0;
}
.explainer-card code {
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.85em;
}
.explainer-bullets {
    margin: 0;
    padding: 0 0 0 20px;
    color: var(--muted);
    line-height: 1.6;
}
.explainer-bullets li {
    margin-bottom: 6px;
}
.explainer-note {
    border-left: 2px solid var(--accent);
    background: linear-gradient(90deg, oklch(0.659 0.192 40.1 / 0.06) 0%, var(--sk-inset-bg) 40%);
}
.explainer-note:hover {
    border-left-color: var(--accent);
}
.explainer-links {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
    gap: 12px;
    margin-top: 4px;
}
.explainer-link {
    display: grid;
    gap: 4px;
    padding: 14px 16px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-shell-bg);
    color: var(--text);
    text-decoration: none;
    transition: border-color 150ms var(--ease-out-smooth), box-shadow 150ms var(--ease-out-smooth), transform 160ms var(--ease-out-smooth);
}
.explainer-link:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.42);
    box-shadow: var(--sk-inset-shadow), 0 0 0 1px oklch(0.659 0.192 40.1 / 0.18), 0 0 12px oklch(0.659 0.192 40.1 / 0.12);
    transform: translateY(-2px);
}
.explainer-stats {
    margin-top: 4px;
    padding: 14px 18px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-shell-bg);
    box-shadow: var(--sk-raised-shadow);
}
.explainer-stats .docs-hero-stat strong {
    font-size: 1.25rem;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
}
.explainer-cta-row {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
    margin-top: 4px;
}
.explainer-cta-row .cta-arrow {
    opacity: 0.65;
    font-size: 0.9rem;
}
.explainer-link strong {
    font-family: var(--font-mono);
    font-size: 0.92rem;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
}
.explainer-link span {
    color: var(--muted);
    font-size: 0.85rem;
    line-height: 1.5;
}
.explainer-foot {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
    padding: 28px 32px;
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    position: relative;
    overflow: hidden;
}
.explainer-foot::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 2px;
    background: linear-gradient(90deg, transparent, var(--accent), transparent);
}
.explainer-foot .cta-arrow {
    opacity: 0.65;
    font-size: 0.9rem;
}
.explainer-secondary {
    color: var(--muted);
    font-size: 0.92rem;
    text-decoration: none;
    border-bottom: 1px solid var(--sk-border);
    padding-bottom: 2px;
    transition: color 150ms var(--ease-out-smooth), border-color 150ms var(--ease-out-smooth);
}
.explainer-secondary:hover {
    color: var(--accent-text);
    border-color: oklch(0.659 0.192 40.1 / 0.42);
}
@media (max-width: 560px) {
    .explainer-shell {
        padding: 22px;
    }
}
@media (prefers-reduced-motion: reduce) {
    .explainer-link,
    .explainer-secondary,
    .explainer-card {
        transition: none;
    }
}
</style>
