// site/src/lib/shared/ui/charts/RadarChart.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import PolarRoot from "./PolarRoot.svelte";
    import RadarCanvas from "./RadarCanvas.svelte";
    import RadarFrame from "./RadarFrame.svelte";
    import type { RadarChartProps } from "@/shared/lib/dither/chart-context";

    let {
        children,
        onselectionchange,
        ...rest
    }: RadarChartProps & { onselectionchange?: (key: string | null) => void; children?: Snippet } = $props();
</script>

<PolarRoot chartType="radar" {...rest} {onselectionchange}>
    {#snippet back()}
        <RadarFrame />
    {/snippet}
    {#snippet canvas()}
        <RadarCanvas />
    {/snippet}
    {@render children?.()}
</PolarRoot>

// site/src/shared/ui/charts/RadarChart.vue
<script setup lang="ts">
import PolarRoot from "./PolarRoot.vue";
import RadarCanvas from "./RadarCanvas.vue";
import RadarFrame from "./RadarFrame.vue";
import type { RadarChartProps } from "@/shared/lib/dither/chart-context";

defineProps<RadarChartProps>();
defineEmits<{ selectionChange: [string | null] }>();
</script>

<template>
    <PolarRoot chart-type="radar" v-bind="$props">
        <template #back><RadarFrame /></template>
        <template #canvas><RadarCanvas /></template>
        <slot />
    </PolarRoot>
</template>
