// site/src/lib/shared/ui/charts/Tooltip.svelte
<script lang="ts">
    import { fade } from "svelte/transition";
    import { useCommonChart } from "@/shared/lib/dither/chart-context";
    import { rgb } from "@/shared/lib/dither/palette";
    import { styleToCss } from "@/shared/lib/dom";

    let {
        labelKey,
        valueFormatter,
        variant = "default",
    }: {
        labelKey?: string;
        valueFormatter?: (value: number, name: string) => string;
        variant?: "default" | "frosted-glass";
    } = $props();

    const chart = useCommonChart();
    const show = $derived(chart.ready && chart.hoverIndex != null);
    const index = $derived(chart.hoverIndex ?? 0);
    const heading = $derived(chart.heading(index, labelKey));
    const items = $derived(chart.itemsAt(index));

    // Position glides via CSS transitions on top/left (declared in charts.css).
    const posStyle = $derived(
        styleToCss({
            top: `${chart.tooltipTop}px`,
            left: `${chart.tooltipLeft}px`,
            backdropFilter: variant === "frosted-glass" ? "blur(4px)" : undefined,
        }),
    );

    function formatValue(value: number, name: string): string {
        return valueFormatter ? valueFormatter(value, name) : value.toLocaleString();
    }
</script>

{#if show && items.length}
    <div class="dk-dom dk-tooltip" style={posStyle} transition:fade={{ duration: 160 }}>
        {#if heading}
            <div class="dk-tooltip-heading">{heading}</div>
        {/if}
        <div class="dk-tooltip-rows">
            {#each items as item (item.name)}
                <div class="dk-tooltip-row" style={styleToCss({ opacity: item.dimmed ? 0.4 : 1 })}>
                    <span class="dk-swatch" style={`background-color: ${rgb(item.seed.fill)}`}></span>
                    <span class="dk-tooltip-label">{item.label}</span>
                    <span class="dk-tooltip-value">{formatValue(item.value, item.name)}</span>
                </div>
            {/each}
        </div>
    </div>
{/if}

// site/src/shared/ui/charts/Tooltip.vue
<script setup lang="ts">
import { computed, type CSSProperties } from "vue";
import { useCommonChart } from "@/shared/lib/dither/chart-context";
import { rgb } from "@/shared/lib/dither/palette";

const props = withDefaults(
    defineProps<{
        labelKey?: string;
        valueFormatter?: (value: number, name: string) => string;
        variant?: "default" | "frosted-glass";
    }>(),
    { variant: "default" },
);

const chart = useCommonChart();
const show = computed(() => chart.ready && chart.hoverIndex != null);
const index = computed(() => chart.hoverIndex ?? 0);
const heading = computed(() => chart.heading(index.value, props.labelKey));
const items = computed(() => chart.itemsAt(index.value));

// Position glides via CSS transitions on top/left (replaces framer-motion).
const posStyle = computed<CSSProperties>(() => ({
    top: `${chart.tooltipTop}px`,
    left: `${chart.tooltipLeft}px`,
    backdropFilter: props.variant === "frosted-glass" ? "blur(4px)" : undefined,
}));

function formatValue(value: number, name: string): string {
    return props.valueFormatter ? props.valueFormatter(value, name) : value.toLocaleString();
}
</script>

<template>
    <Transition name="dk-fade">
        <div v-if="show && items.length" class="dk-dom dk-tooltip" :style="posStyle">
            <div v-if="heading" class="dk-tooltip-heading">{{ heading }}</div>
            <div class="dk-tooltip-rows">
                <div
                    v-for="item in items"
                    :key="item.name"
                    class="dk-tooltip-row"
                    :style="{ opacity: item.dimmed ? 0.4 : 1 }"
                >
                    <span class="dk-swatch" :style="{ backgroundColor: rgb(item.seed.fill) }" />
                    <span class="dk-tooltip-label">{{ item.label }}</span>
                    <span class="dk-tooltip-value">{{ formatValue(item.value, item.name) }}</span>
                </div>
            </div>
        </div>
    </Transition>
</template>
