// site/src/lib/shared/ui/charts/LineChart.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import CartesianCanvas from "./CartesianCanvas.svelte";
    import CartesianRoot from "./CartesianRoot.svelte";
    import type { CartesianChartProps } from "@/shared/lib/dither/chart-context";

    let {
        children,
        onhoverchange,
        onselectionchange,
        ...rest
    }: CartesianChartProps & {
        onhoverchange?: (index: number | null) => void;
        onselectionchange?: (key: string | null) => void;
        children?: Snippet;
    } = $props();
</script>

<CartesianRoot chartType="line" {...rest} {onhoverchange} {onselectionchange}>
    {#snippet canvas()}
        <CartesianCanvas />
    {/snippet}
    {@render children?.()}
</CartesianRoot>

// site/_src_vue_backup/shared/ui/charts/LineChart.vue
<script setup lang="ts">
import CartesianCanvas from "./CartesianCanvas.vue";
import CartesianRoot from "./CartesianRoot.vue";
import type { CartesianChartProps } from "@/shared/lib/dither/chart-context";

defineProps<CartesianChartProps>();
defineEmits<{ hoverChange: [number | null]; selectionChange: [string | null] }>();
</script>

<template>
    <CartesianRoot chart-type="line" v-bind="$props">
        <template #canvas><CartesianCanvas /></template>
        <slot />
    </CartesianRoot>
</template>
