// site/src/lib/shared/ui/charts/Pie.svelte
<script lang="ts">
    import { onDestroy } from "svelte";
    import { usePolarPart } from "@/shared/lib/dither/chart-context";
    import type { AreaVariant } from "@/shared/lib/dither/chart-types";
    import { watchDeps } from "@/shared/lib/watchDeps";

    let { variant = "gradient" }: { variant?: AreaVariant } = $props();

    const ctx = usePolarPart("Pie", "pie");
    const syncVariant = watchDeps(() => {
        ctx.registerVariant("*", variant);
    });
    onDestroy(() => ctx.unregisterVariant("*"));
</script>

<span hidden use:syncVariant={[variant]}></span>

// site/_src_vue_backup/shared/ui/charts/Pie.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, watch } from "vue";
import { usePolarPart } from "@/shared/lib/dither/chart-context";
import type { AreaVariant } from "@/shared/lib/dither/chart-types";

const props = withDefaults(defineProps<{ variant?: AreaVariant }>(), { variant: "gradient" });

const ctx = usePolarPart("Pie", "pie");
onMounted(() => ctx.registerVariant("*", props.variant));
watch(
    () => props.variant,
    (v) => ctx.registerVariant("*", v),
);
onBeforeUnmount(() => ctx.unregisterVariant("*"));
</script>

<template><span hidden /></template>
