// site/src/lib/shared/ui/charts/PieChart.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import PieCanvas from "./PieCanvas.svelte";
    import PolarRoot from "./PolarRoot.svelte";
    import type { PieChartProps } from "@/shared/lib/dither/chart-context";

    let {
        children,
        onselectionchange,
        ...rest
    }: PieChartProps & { onselectionchange?: (key: string | null) => void; children?: Snippet } = $props();
</script>

<PolarRoot chartType="pie" {...rest} {onselectionchange}>
    {#snippet canvas()}
        <PieCanvas />
    {/snippet}
    {@render children?.()}
</PolarRoot>

// site/_src_vue_backup/shared/ui/charts/PieChart.vue
<script setup lang="ts">
import PieCanvas from "./PieCanvas.vue";
import PolarRoot from "./PolarRoot.vue";
import type { PieChartProps } from "@/shared/lib/dither/chart-context";

defineProps<PieChartProps>();
defineEmits<{ selectionChange: [string | null] }>();
</script>

<template>
    <PolarRoot chart-type="pie" v-bind="$props">
        <template #canvas><PieCanvas /></template>
        <slot />
    </PolarRoot>
</template>
