// site/src/pages/team/ui/TeamPage.vue
<script setup lang="ts">
import { useSeo } from "@/shared/lib/seo";
import { siteConfig } from "@/shared/config/site";
import { CtaButton, DitherAvatar, DitherGradient } from "@/shared/ui";
import { buildBreadcrumbJsonLd, buildOrganizationJsonLd, buildSoftwareJsonLd, buildWebsiteJsonLd, buildWebApiJsonLd } from "@/shared/lib/jsonLd";

interface Member {
    name: string;
    role: string;
    bio: string;
    github: string;
    githubHandle: string;
    avatar: string;
}

const team: Member[] = [
    {
        name: "Vibhek Soni",
        role: "Founder",
        bio: "Wrote the full FreeTheAi API and most of the platform. Started the project to share the AI resources he had access to with everyone.",
        github: "https://github.com/vibheksoni",
        githubHandle: "vibheksoni",
        avatar: "https://avatars.githubusercontent.com/u/102437829?v=4",
    },
    {
        name: "Dr. Vova",
        role: "Co-Founder",
        bio: "Helps with frontend and the upcoming GoonPia roleplay site.",
        github: "https://github.com/drvova",
        githubHandle: "drvova",
        avatar: "https://avatars.githubusercontent.com/u/166897058?v=4",
    },
    {
        name: "Sai Revanth",
        role: "Discord Manager",
        bio: "Keeps the Discord moving day to day, helps users land their first key, and runs community-side moderation.",
        github: "https://github.com/svsairevanth",
        githubHandle: "svsairevanth",
        avatar: "https://avatars.githubusercontent.com/u/157276603?v=4",
    },
];

const pageDescription =
    "Meet the FreeTheAi team: Vibhek Soni built the full API and platform, and co-founder Dr. Vova helps with frontend and GoonPia. Built to share free AI with everyone.";

useSeo({
    title: "FreeTheAi Team - The People Behind the Free AI API",
    description: pageDescription,
    path: "/team",
    jsonLd: [
        buildWebsiteJsonLd(),
        buildOrganizationJsonLd(),
        buildSoftwareJsonLd(),
        buildWebApiJsonLd(),
        {
            "@context": "https://schema.org",
            "@type": "Organization",
            "@id": "https://freetheai.xyz/team#organization",
            name: siteConfig.title,
            url: "https://freetheai.xyz/",
            logo: "https://freetheai.xyz/FreeTheAi.png",
            sameAs: [siteConfig.socials.github, "https://github.com/Free-The-Ai", siteConfig.socials.discord],
            member: team.map((member) => ({
                "@type": "Person",
                name: member.name,
                jobTitle: member.role,
                url: member.github,
                image: member.avatar,
                description: member.bio,
                sameAs: [member.github],
            })),
        },
        buildBreadcrumbJsonLd([
            { name: "FreeTheAi", url: "https://freetheai.xyz/home" },
            { name: "Team", url: "https://freetheai.xyz/team" },
        ]),
    ],
});
</script>

<template>
    <main class="team-main">
        <section class="team-hero shell">
            <DitherGradient class="team-hero-glow" from="orange" direction="up" :opacity="0.4" />
            <span class="eyebrow">Team</span>
            <h1>The people behind FreeTheAi.</h1>
            <p class="team-lede">
                A small crew sharing free AI tools with everyone. Open source, community-run, and built in public on
                <a :href="siteConfig.socials.github" target="_blank" rel="noreferrer">GitHub</a> and
                <a href="https://github.com/Free-The-Ai" target="_blank" rel="noreferrer">Free-The-Ai</a>.
            </p>
        </section>

        <section class="team-stats shell" aria-label="Team and community stats">
            <div class="team-stat">
                <span class="team-stat-num">{{ team.length }}</span>
                <span class="team-stat-label">Team members</span>
            </div>
            <div class="team-stat">
                <span class="team-stat-num">100%</span>
                <span class="team-stat-label">Open source</span>
            </div>
            <div class="team-stat">
                <span class="team-stat-num">2,000+</span>
                <span class="team-stat-label">Discord community</span>
            </div>
        </section>

        <section class="section shell team-grid-section">
            <div class="team-grid">
                <article v-for="member in team" :key="member.githubHandle" class="team-card">
                    <DitherGradient class="team-card-glow" from="orange" direction="up" :opacity="0.5" />
                    <div class="team-card-top">
                        <DitherAvatar class="team-avatar" :name="member.name" :size="80" bloom="low" />
                        <div class="team-card-meta">
                            <h2>{{ member.name }}</h2>
                            <span class="team-role">{{ member.role }}</span>
                        </div>
                    </div>
                    <p class="team-bio">{{ member.bio }}</p>
                    <a class="team-github" :href="member.github" target="_blank" rel="noreferrer">
                        <span class="material-symbols-outlined" aria-hidden="true">code</span>
                        <span>github.com/{{ member.githubHandle }}</span>
                    </a>
                </article>
            </div>
        </section>

        <section class="section shell team-foot-section">
            <div class="team-foot-card">
                <header class="section-head">
                    <span class="eyebrow">Open source</span>
                    <h2>Build with us.</h2>
                </header>
                <p class="team-foot-lede">
                    FreeTheAi is open source. Issues, pull requests, and feature ideas are welcome on the public repo. The Discord
                    is the fastest way to reach the team.
                </p>
                <div class="team-foot-links">
                    <CtaButton :href="siteConfig.socials.github" target="_blank" rel="noreferrer">Star the repo</CtaButton>
                    <a class="team-secondary" :href="siteConfig.socials.discord" target="_blank" rel="noreferrer">Join the Discord</a>
                    <router-link class="team-secondary" to="/quickstart">Try the quickstart</router-link>
                </div>
            </div>
        </section>
    </main>
</template>

<style scoped>
.team-main {
    gap: 28px;
    padding: 22px 0 64px;
}

.team-hero {
    position: relative;
    display: grid;
    gap: 12px;
    padding: clamp(28px, 4.6vw, 52px);
    overflow: hidden;
}

.team-hero-glow {
    z-index: 0;
}

.team-hero > .eyebrow,
.team-hero > h1,
.team-hero > .team-lede {
    position: relative;
    z-index: 1;
}

.team-hero h1 {
    margin: 0;
    font-size: clamp(2.35rem, 4.7vw, 3.6rem);
    line-height: 1.04;
    letter-spacing: -0.045em;
}

.team-lede {
    margin: 0;
    max-width: 56ch;
    color: var(--muted);
    font-size: 1rem;
    line-height: 1.55;
}

.team-lede a {
    color: var(--accent-text);
    text-decoration: underline;
    text-underline-offset: 2px;
}

.team-stats {
    display: flex;
    flex-wrap: wrap;
    gap: 0;
    padding: 0 16px;
}

.team-stat {
    flex: 1 1 0;
    min-width: 120px;
    display: grid;
    gap: 2px;
    padding: 14px 16px;
    border: 1px solid var(--sk-border);
    border-right: none;
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
}

.team-stat:last-child {
    border-right: 1px solid var(--sk-border);
    border-radius: 0 var(--radius) var(--radius) 0;
}

.team-stat:first-child {
    border-radius: var(--radius) 0 0 var(--radius);
}

.team-stat-num {
    font-family: var(--font-mono);
    font-size: 1.3rem;
    font-weight: 600;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
    line-height: 1.2;
}

.team-stat-label {
    font-family: var(--font-mono);
    font-size: 0.68rem;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--dim);
}

.team-grid-section {
    padding: clamp(22px, 3.8vw, 36px);
}

.team-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 16px;
}

.team-card {
    position: relative;
    display: grid;
    gap: 12px;
    padding: 22px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    overflow: hidden;
    transition: border-color 200ms var(--ease-out-smooth), box-shadow 200ms var(--ease-out-smooth), transform 200ms var(--ease-out-smooth);
}

.team-card-glow {
    z-index: 0;
    opacity: 0;
    transition: opacity 200ms var(--ease-out-smooth);
}

.team-card:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.35);
    box-shadow: var(--sk-inset-shadow), 0 0 0 1px oklch(0.659 0.192 40.1 / 0.16);
    transform: translateY(-2px);
}

.team-card:hover .team-card-glow {
    opacity: 1;
}

.team-card > .team-card-top,
.team-card > .team-bio,
.team-card > .team-github {
    position: relative;
    z-index: 1;
}

.team-card-top {
    display: flex;
    align-items: center;
    gap: 14px;
}

.team-avatar {
    flex: none;
    border-radius: 50%;
    border: 2px solid oklch(0.659 0.192 40.1 / 0.3);
    background: var(--bg);
    overflow: hidden;
    box-shadow: var(--sk-inset-shadow), 0 0 12px oklch(0.659 0.192 40.1 / 0.12);
}

.team-card-meta h2 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: 1.2rem;
    line-height: 1.15;
}

.team-role {
    display: inline-block;
    margin-top: 4px;
    padding: 2px 10px;
    border: 1px solid oklch(0.659 0.192 40.1 / 0.28);
    border-radius: var(--radius-full);
    background: oklch(0.659 0.192 40.1 / 0.12);
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    text-shadow: 0 0 8px oklch(0.659 0.192 40.1 / 0.2);
}

.team-bio {
    margin: 0;
    color: var(--muted);
    font-size: 0.92rem;
    line-height: 1.55;
}

.team-github {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 7px 12px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-shell-bg);
    color: var(--text);
    font-family: var(--font-mono);
    font-size: 0.78rem;
    text-decoration: none;
    width: fit-content;
    transition: border-color 150ms var(--ease-out-smooth), color 150ms var(--ease-out-smooth), text-shadow 150ms var(--ease-out-smooth);
}

.team-github:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.42);
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
}

.team-github .material-symbols-outlined {
    font-size: 16px;
}

.team-foot-section {
    padding: clamp(22px, 3.8vw, 36px);
}

.team-foot-card {
    position: relative;
    display: grid;
    gap: 14px;
    padding: clamp(22px, 3.4vw, 32px);
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    overflow: hidden;
}

.team-foot-card::before {
    content: "";
    position: absolute;
    inset: 0 auto 0 0;
    width: 3px;
    background: linear-gradient(180deg, oklch(0.659 0.192 40.1), oklch(0.827 0.113 55.9));
    pointer-events: none;
}

.team-foot-card > * {
    position: relative;
    z-index: 1;
}

.team-foot-card .section-head {
    display: grid;
    gap: 4px;
}

.team-foot-card h2 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: 1.5rem;
    letter-spacing: -0.02em;
}

.team-foot-card .eyebrow {
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    text-shadow: var(--accent-text-glow);
}

.team-foot-lede {
    margin: 0;
    max-width: 60ch;
    color: var(--muted);
    font-size: 0.95rem;
    line-height: 1.55;
}

.team-foot-links {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
}

.team-foot-links .cta-arrow {
    opacity: 0.65;
    font-size: 0.9rem;
}

.team-secondary {
    color: var(--muted);
    font-size: 0.92rem;
    text-decoration: none;
    border-bottom: 1px solid var(--sk-border);
    padding-bottom: 2px;
    transition: color 150ms var(--ease-out-smooth), border-color 150ms var(--ease-out-smooth);
}

.team-secondary:hover {
    color: var(--accent-text);
    border-color: oklch(0.659 0.192 40.1 / 0.42);
}

@media (max-width: 560px) {
    .team-card {
        padding: 18px;
    }

    .team-stats {
        gap: 8px;
    }

    .team-stat {
        flex: 1 1 100%;
        border: 1px solid var(--sk-border);
        border-radius: var(--radius);
    }
}

@media (prefers-reduced-motion: reduce) {
    .team-card,
    .team-card:hover,
    .team-card-glow,
    .team-github,
    .team-secondary {
        transition: none;
        transform: none;
    }
}
</style>

// site/src/lib/pages/team/ui/TeamPage.svelte
<script lang="ts">
    import { buildSeo } from "@/shared/lib/seo";
    import { siteConfig } from "@/shared/config/site";
    import { CtaButton, DitherAvatar, DitherGradient, SeoHead } from "@/shared/ui";
    import { buildBreadcrumbJsonLd, buildOrganizationJsonLd, buildSoftwareJsonLd, buildWebsiteJsonLd, buildWebApiJsonLd } from "@/shared/lib/jsonLd";

    interface Member {
        name: string;
        role: string;
        bio: string;
        github: string;
        githubHandle: string;
        avatar: string;
    }

    const team: Member[] = [
        {
            name: "Vibhek Soni",
            role: "Founder",
            bio: "Wrote the full FreeTheAi API and most of the platform. Started the project to share the AI resources he had access to with everyone.",
            github: "https://github.com/vibheksoni",
            githubHandle: "vibheksoni",
            avatar: "https://avatars.githubusercontent.com/u/102437829?v=4",
        },
        {
            name: "Dr. Vova",
            role: "Co-Founder",
            bio: "Helps with frontend and the upcoming GoonPia roleplay site.",
            github: "https://github.com/drvova",
            githubHandle: "drvova",
            avatar: "https://avatars.githubusercontent.com/u/166897058?v=4",
        },
        {
            name: "Sai Revanth",
            role: "Discord Manager",
            bio: "Keeps the Discord moving day to day, helps users land their first key, and runs community-side moderation.",
            github: "https://github.com/svsairevanth",
            githubHandle: "svsairevanth",
            avatar: "https://avatars.githubusercontent.com/u/157276603?v=4",
        },
    ];

    const pageDescription =
        "Meet the FreeTheAi team: Vibhek Soni built the full API and platform, and co-founder Dr. Vova helps with frontend and GoonPia. Built to share free AI with everyone.";

    const seo = buildSeo({
        title: "FreeTheAi Team - The People Behind the Free AI API",
        description: pageDescription,
        path: "/team",
        jsonLd: [
            buildWebsiteJsonLd(),
            buildOrganizationJsonLd(),
            buildSoftwareJsonLd(),
            buildWebApiJsonLd(),
            {
                "@context": "https://schema.org",
                "@type": "Organization",
                "@id": "https://freetheai.xyz/team#organization",
                name: siteConfig.title,
                url: "https://freetheai.xyz/",
                logo: "https://freetheai.xyz/FreeTheAi.png",
                sameAs: [siteConfig.socials.github, "https://github.com/Free-The-Ai", siteConfig.socials.discord],
                member: team.map((member) => ({
                    "@type": "Person",
                    name: member.name,
                    jobTitle: member.role,
                    url: member.github,
                    image: member.avatar,
                    description: member.bio,
                    sameAs: [member.github],
                })),
            },
            buildBreadcrumbJsonLd([
                { name: "FreeTheAi", url: "https://freetheai.xyz/home" },
                { name: "Team", url: "https://freetheai.xyz/team" },
            ]),
        ],
    });
</script>

<SeoHead {seo} />

<main class="team-main">
    <section class="team-hero shell">
        <DitherGradient class="team-hero-glow" from="orange" direction="up" opacity={0.4} />
        <span class="eyebrow">Team</span>
        <h1>The people behind FreeTheAi.</h1>
        <p class="team-lede">
            A small crew sharing free AI tools with everyone. Open source, community-run, and built in public on
            <a href={siteConfig.socials.github} target="_blank" rel="noreferrer">GitHub</a> and
            <a href="https://github.com/Free-The-Ai" target="_blank" rel="noreferrer">Free-The-Ai</a>.
        </p>
    </section>

    <section class="team-stats shell" aria-label="Team and community stats">
        <div class="team-stat">
            <span class="team-stat-num">{team.length}</span>
            <span class="team-stat-label">Team members</span>
        </div>
        <div class="team-stat">
            <span class="team-stat-num">100%</span>
            <span class="team-stat-label">Open source</span>
        </div>
        <div class="team-stat">
            <span class="team-stat-num">2,000+</span>
            <span class="team-stat-label">Discord community</span>
        </div>
    </section>

    <section class="section shell team-grid-section">
        <div class="team-grid">
            {#each team as member (member.githubHandle)}
                <article class="team-card">
                    <DitherGradient class="team-card-glow" from="orange" direction="up" opacity={0.5} />
                    <div class="team-card-top">
                        <DitherAvatar class="team-avatar" name={member.name} size={80} bloom="low" />
                        <div class="team-card-meta">
                            <h2>{member.name}</h2>
                            <span class="team-role">{member.role}</span>
                        </div>
                    </div>
                    <p class="team-bio">{member.bio}</p>
                    <a class="team-github" href={member.github} target="_blank" rel="noreferrer">
                        <span class="material-symbols-outlined" aria-hidden="true">code</span>
                        <span>github.com/{member.githubHandle}</span>
                    </a>
                </article>
            {/each}
        </div>
    </section>

    <section class="section shell team-foot-section">
        <div class="team-foot-card">
            <header class="section-head">
                <span class="eyebrow">Open source</span>
                <h2>Build with us.</h2>
            </header>
            <p class="team-foot-lede">
                FreeTheAi is open source. Issues, pull requests, and feature ideas are welcome on the public repo. The Discord
                is the fastest way to reach the team.
            </p>
            <div class="team-foot-links">
                <CtaButton href={siteConfig.socials.github} target="_blank" rel="noreferrer">Star the repo</CtaButton>
                <a class="team-secondary" href={siteConfig.socials.discord} target="_blank" rel="noreferrer">Join the Discord</a>
                <a class="team-secondary" href="/quickstart">Try the quickstart</a>
            </div>
        </div>
    </section>
</main>

<style>
.team-main {
    gap: 28px;
    padding: 22px 0 64px;
}
.team-hero {
    position: relative;
    display: grid;
    gap: 12px;
    padding: clamp(28px, 4.6vw, 52px);
    overflow: hidden;
}
:global(.team-hero-glow) {
    z-index: 0;
}
.team-hero > .eyebrow,
.team-hero > h1,
.team-hero > .team-lede {
    position: relative;
    z-index: 1;
}
.team-hero h1 {
    margin: 0;
    font-size: clamp(2.35rem, 4.7vw, 3.6rem);
    line-height: 1.04;
    letter-spacing: -0.045em;
}
.team-lede {
    margin: 0;
    max-width: 56ch;
    color: var(--muted);
    font-size: 1rem;
    line-height: 1.55;
}
.team-lede a {
    color: var(--accent-text);
    text-decoration: underline;
    text-underline-offset: 2px;
}
.team-stats {
    display: flex;
    flex-wrap: wrap;
    gap: 0;
    padding: 0 16px;
}
.team-stat {
    flex: 1 1 0;
    min-width: 120px;
    display: grid;
    gap: 2px;
    padding: 14px 16px;
    border: 1px solid var(--sk-border);
    border-right: none;
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
}
.team-stat:last-child {
    border-right: 1px solid var(--sk-border);
    border-radius: 0 var(--radius) var(--radius) 0;
}
.team-stat:first-child {
    border-radius: var(--radius) 0 0 var(--radius);
}
.team-stat-num {
    font-family: var(--font-mono);
    font-size: 1.3rem;
    font-weight: 600;
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
    line-height: 1.2;
}
.team-stat-label {
    font-family: var(--font-mono);
    font-size: 0.68rem;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--dim);
}
.team-grid-section {
    padding: clamp(22px, 3.8vw, 36px);
}
.team-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 16px;
}
.team-card {
    position: relative;
    display: grid;
    gap: 12px;
    padding: 22px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    overflow: hidden;
    transition: border-color 200ms var(--ease-out-smooth), box-shadow 200ms var(--ease-out-smooth), transform 200ms var(--ease-out-smooth);
}
:global(.team-card-glow) {
    z-index: 0;
    opacity: 0;
    transition: opacity 200ms var(--ease-out-smooth);
}
.team-card:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.35);
    box-shadow: var(--sk-inset-shadow), 0 0 0 1px oklch(0.659 0.192 40.1 / 0.16);
    transform: translateY(-2px);
}
.team-card:hover :global(.team-card-glow) {
    opacity: 1;
}
.team-card > .team-card-top,
.team-card > .team-bio,
.team-card > .team-github {
    position: relative;
    z-index: 1;
}
.team-card-top {
    display: flex;
    align-items: center;
    gap: 14px;
}
:global(.team-avatar) {
    flex: none;
    border-radius: 50%;
    border: 2px solid oklch(0.659 0.192 40.1 / 0.3);
    background: var(--bg);
    overflow: hidden;
    box-shadow: var(--sk-inset-shadow), 0 0 12px oklch(0.659 0.192 40.1 / 0.12);
}
.team-card-meta h2 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: 1.2rem;
    line-height: 1.15;
}
.team-role {
    display: inline-block;
    margin-top: 4px;
    padding: 2px 10px;
    border: 1px solid oklch(0.659 0.192 40.1 / 0.28);
    border-radius: var(--radius-full);
    background: oklch(0.659 0.192 40.1 / 0.12);
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.04em;
    text-transform: uppercase;
    text-shadow: 0 0 8px oklch(0.659 0.192 40.1 / 0.2);
}
.team-bio {
    margin: 0;
    color: var(--muted);
    font-size: 0.92rem;
    line-height: 1.55;
}
.team-github {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 7px 12px;
    border: 1px solid var(--sk-border);
    border-radius: var(--radius-sm);
    background: var(--sk-shell-bg);
    color: var(--text);
    font-family: var(--font-mono);
    font-size: 0.78rem;
    text-decoration: none;
    width: fit-content;
    transition: border-color 150ms var(--ease-out-smooth), color 150ms var(--ease-out-smooth), text-shadow 150ms var(--ease-out-smooth);
}
.team-github:hover {
    border-color: oklch(0.659 0.192 40.1 / 0.42);
    color: var(--accent-text);
    text-shadow: var(--accent-text-glow);
}
.team-github .material-symbols-outlined {
    font-size: 16px;
}
.team-foot-section {
    padding: clamp(22px, 3.8vw, 36px);
}
.team-foot-card {
    position: relative;
    display: grid;
    gap: 14px;
    padding: clamp(22px, 3.4vw, 32px);
    border: 1px solid var(--sk-border);
    border-radius: var(--radius);
    background: var(--sk-inset-bg);
    box-shadow: var(--sk-inset-shadow);
    overflow: hidden;
}
.team-foot-card::before {
    content: "";
    position: absolute;
    inset: 0 auto 0 0;
    width: 3px;
    background: linear-gradient(180deg, oklch(0.659 0.192 40.1), oklch(0.827 0.113 55.9));
    pointer-events: none;
}
.team-foot-card > * {
    position: relative;
    z-index: 1;
}
.team-foot-card .section-head {
    display: grid;
    gap: 4px;
}
.team-foot-card h2 {
    margin: 0;
    font-family: var(--font-serif);
    font-size: 1.5rem;
    letter-spacing: -0.02em;
}
.team-foot-card .eyebrow {
    color: var(--accent-text);
    font-family: var(--font-mono);
    font-size: 0.7rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    text-shadow: var(--accent-text-glow);
}
.team-foot-lede {
    margin: 0;
    max-width: 60ch;
    color: var(--muted);
    font-size: 0.95rem;
    line-height: 1.55;
}
.team-foot-links {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 14px;
}
.team-foot-links :global(.cta-arrow) {
    opacity: 0.65;
    font-size: 0.9rem;
}
.team-secondary {
    color: var(--muted);
    font-size: 0.92rem;
    text-decoration: none;
    border-bottom: 1px solid var(--sk-border);
    padding-bottom: 2px;
    transition: color 150ms var(--ease-out-smooth), border-color 150ms var(--ease-out-smooth);
}
.team-secondary:hover {
    color: var(--accent-text);
    border-color: oklch(0.659 0.192 40.1 / 0.42);
}
@media (max-width: 560px) {
    .team-card {
        padding: 18px;
    }
    .team-stats {
        gap: 8px;
    }
    .team-stat {
        flex: 1 1 100%;
        border: 1px solid var(--sk-border);
        border-radius: var(--radius);
    }
}
@media (prefers-reduced-motion: reduce) {
    .team-card,
    .team-card:hover,
    .team-github,
    .team-secondary {
        transition: none;
        transform: none;
    }
}
</style>
