// site/src/components/DocsMobileNav.tsx
import { useState, useEffect, useRef, useCallback } from "react";
import { disconnectPointerDrag, lockBodyScroll, unlockBodyScroll } from "../lib/domUtils";
import { motionFor, motionApply } from "../lib/motion";

const SECTIONS = [
  { id: "auth", label: "Auth" },
  { id: "endpoints", label: "Endpoints" },
  { id: "chat", label: "Chat" },
  { id: "messages", label: "Messages" },
  { id: "models", label: "Models" },
  { id: "errors", label: "Errors" },
];

function useSheetDrag(onClose: () => void) {
  const [dragY, setDragY] = useState(0);
  const sheetRef = useRef<HTMLDivElement | null>(null);
  const startYRef = useRef(0);
  const startOffsetRef = useRef(0);
  const isDraggingRef = useRef(false);
  const dragYRef = useRef(0);
  const boundMoveRef = useRef<((e: PointerEvent) => void) | null>(null);
  const boundUpRef = useRef<((e: PointerEvent) => void) | null>(null);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  const onDragMove = useCallback((e: PointerEvent) => {
    if (!isDraggingRef.current) return;
    e.preventDefault();
    const next = Math.max(0, startOffsetRef.current + e.clientY - startYRef.current);
    dragYRef.current = next;
    setDragY(next);
  }, []);

  const onDragEnd = useCallback((e: PointerEvent) => {
    if (!isDraggingRef.current) return;
    isDraggingRef.current = false;
    e.preventDefault();
    disconnectPointerDrag(boundMoveRef.current, boundUpRef.current);
    boundMoveRef.current = boundUpRef.current = null;
    const sheet = sheetRef.current;
    if (!sheet) { setDragY(0); dragYRef.current = 0; return; }
    if (dragYRef.current > sheet.offsetHeight * 0.3) onCloseRef.current();
    else { setDragY(0); dragYRef.current = 0; }
  }, []);

  const onDragStart = useCallback((e: React.PointerEvent) => {
    const target = e.target as HTMLElement;
    if (target.closest("button:not(.docs-mobile-toc__handle), a")) return;
    e.preventDefault();
    isDraggingRef.current = true;
    startYRef.current = e.clientY;
    startOffsetRef.current = dragYRef.current;
    boundMoveRef.current = onDragMove;
    boundUpRef.current = onDragEnd;
    document.addEventListener("pointermove", onDragMove, { passive: false });
    document.addEventListener("pointerup", onDragEnd, { passive: false });
    document.addEventListener("pointercancel", onDragEnd, { passive: false });
  }, [onDragMove, onDragEnd]);

  useEffect(() => () => disconnectPointerDrag(boundMoveRef.current, boundUpRef.current), []);

  return { dragY, sheetRef, onDragStart };
}

export default function DocsMobileNav() {
  const [open, setOpen] = useState(false);
  const [activeId, setActiveId] = useState("");

  const close = useCallback(() => {
    setOpen(false);
    unlockBodyScroll("docs-toc-open");
  }, []);

  const drag = useSheetDrag(close);

  const setSheetRef = useCallback((el: HTMLDivElement | null) => {
    drag.sheetRef.current = el;
    if (el) motionApply(el, motionFor("panel", "enter", { size: el.offsetHeight }));
  }, [drag]);

  useEffect(() => {
    if (typeof window === "undefined") return;
    if (!("IntersectionObserver" in window)) return;

    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        }
      },
      { rootMargin: "-20% 0px -70% 0px" },
    );

    for (const s of SECTIONS) {
      const el = document.getElementById(s.id);
      if (el) observer.observe(el);
    }

    return () => observer.disconnect();
  }, []);

  const scrollTo = useCallback((id: string) => {
    const el = document.getElementById(id);
    if (el) {
      close();
      const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
      setTimeout(() => el.scrollIntoView({ behavior: reduce ? 'auto' : 'smooth' }), 50);
    }
  }, [close]);

  const toggle = useCallback(() => {
    if (open) close();
    else { setOpen(true); lockBodyScroll("docs-toc-open"); }
  }, [open, close]);

  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (e.key === "Escape") close();
  }, [close]);

  useEffect(() => () => { if (open) unlockBodyScroll("docs-toc-open"); }, [open]);

  return (
    <div className="docs-mobile-toc" onKeyDown={handleKeyDown}>
      <button
        type="button"
        className="docs-mobile-toc__trigger"
        onClick={toggle}
        aria-expanded={open}
        aria-label="Table of contents"
      >
        <span className="material-symbols-outlined">toc</span>
      </button>

      {open && (
        <>
          <div className="docs-mobile-toc__overlay" data-sound="overlay.close" onClick={close} />
          <div
            className="docs-mobile-toc__sheet"
            ref={setSheetRef}
            style={drag.dragY > 0 ? { transform: `translateY(${drag.dragY}px)`, transition: "none", touchAction: "none" } : {}}
            onPointerDown={drag.onDragStart}
          >
            <div className="docs-mobile-toc__handle" />
            <div className="docs-mobile-toc__label">On this page</div>
            <nav className="docs-mobile-toc__links">
              {SECTIONS.map((s) => (
                <button
                  key={s.id}
                  type="button"
                  className={`docs-mobile-toc__link${activeId === s.id ? " is-active" : ""}`}
                  onClick={() => scrollTo(s.id)}
                >
                  {s.label}
                </button>
              ))}
            </nav>
          </div>
        </>
      )}
    </div>
  );
}

// site/_src_vue_backup/features/docs-navigation/ui/DocsMobileNav.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { disconnectPointerDrag, lockBodyScroll, unlockBodyScroll } from "@/shared/lib/dom";
import { motionApply, motionFor } from "@/shared/lib/motion";

const SECTIONS = [
    { id: "auth", label: "Auth" },
    { id: "endpoints", label: "Endpoints" },
    { id: "chat", label: "Chat" },
    { id: "messages", label: "Messages" },
    { id: "models", label: "Models" },
    { id: "errors", label: "Errors" },
];

const open = ref(false);
const activeId = ref("");
const dragY = ref(0);
const sheetEl = ref<HTMLElement | null>(null);

let dragging = false;
let startY = 0;
let boundMove: ((e: PointerEvent) => void) | null = null;
let boundUp: ((e: PointerEvent) => void) | null = null;
let observer: IntersectionObserver | null = null;

function close(): void {
    open.value = false;
    unlockBodyScroll("docs-toc-open");
}

function toggle(): void {
    if (open.value) close();
    else {
        open.value = true;
        lockBodyScroll("docs-toc-open");
    }
}

function onSheetMounted(el: Element | null): void {
    sheetEl.value = el as HTMLElement | null;
    if (sheetEl.value) motionApply(sheetEl.value, motionFor("panel", "enter", { size: sheetEl.value.offsetHeight }));
}

function onDragStart(event: PointerEvent): void {
    const target = event.target as HTMLElement;
    if (target.closest("button:not(.docs-mobile-toc__handle), a")) return;
    event.preventDefault();
    dragging = true;
    startY = event.clientY;
    boundMove = onDragMove;
    boundUp = onDragEnd;
    document.addEventListener("pointermove", boundMove, { passive: false });
    document.addEventListener("pointerup", boundUp, { passive: false });
    document.addEventListener("pointercancel", boundUp, { passive: false });
}

function onDragMove(event: PointerEvent): void {
    if (!dragging) return;
    event.preventDefault();
    dragY.value = Math.max(0, event.clientY - startY);
}

function onDragEnd(): void {
    if (!dragging) return;
    dragging = false;
    disconnectPointerDrag(boundMove, boundUp);
    boundMove = boundUp = null;
    const sheet = sheetEl.value;
    if (!sheet) {
        dragY.value = 0;
        return;
    }
    if (dragY.value > sheet.offsetHeight * 0.3) close();
    dragY.value = 0;
}

function scrollTo(id: string): void {
    const el = document.getElementById(id);
    if (!el) return;
    close();
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    setTimeout(() => el.scrollIntoView({ behavior: reduce ? "auto" : "smooth" }), 50);
}

function onKeydown(event: KeyboardEvent): void {
    if (event.key === "Escape") close();
}

onMounted(() => {
    if (typeof window === "undefined" || !("IntersectionObserver" in window)) return;
    observer = new IntersectionObserver(
        (entries) => {
            for (const entry of entries) {
                if (entry.isIntersecting) activeId.value = entry.target.id;
            }
        },
        { rootMargin: "-20% 0px -70% 0px" },
    );
    for (const section of SECTIONS) {
        const el = document.getElementById(section.id);
        if (el) observer.observe(el);
    }
});

onBeforeUnmount(() => {
    observer?.disconnect();
    if (open.value) unlockBodyScroll("docs-toc-open");
    disconnectPointerDrag(boundMove, boundUp);
});
</script>

<template>
    <div class="docs-mobile-toc" @keydown="onKeydown">
        <button type="button" class="docs-mobile-toc__trigger" :aria-expanded="open" aria-label="Table of contents" @click="toggle">
            <span class="material-symbols-outlined">toc</span>
        </button>

        <template v-if="open">
            <div class="docs-mobile-toc__overlay" data-sound="overlay.close" @click="close" />
            <div
                class="docs-mobile-toc__sheet"
                :ref="(el) => onSheetMounted(el as Element | null)"
                :style="dragY > 0 ? { transform: `translateY(${dragY}px)`, transition: 'none', touchAction: 'none' } : undefined"
                @pointerdown="onDragStart"
            >
                <div class="docs-mobile-toc__handle" />
                <div class="docs-mobile-toc__label">On this page</div>
                <nav class="docs-mobile-toc__links">
                    <button
                        v-for="section in SECTIONS"
                        :key="section.id"
                        type="button"
                        :class="['docs-mobile-toc__link', { 'is-active': activeId === section.id }]"
                        @click="scrollTo(section.id)"
                    >
                        {{ section.label }}
                    </button>
                </nav>
            </div>
        </template>
    </div>
</template>
